// This file is generated by Shell for ops register
#import "backend/metal/MetalDefine.h"
   namespace MNN {
#if MNN_METAL_ENABLED
  extern void ___MetalRasterAndInterpolateCreator__OpType_RasterAndInterpolate__();
void registerMetalRenderOps() {
   ___MetalRasterAndInterpolateCreator__OpType_RasterAndInterpolate__();
}
#endif
}