#ifndef VK_GLSL_SHADER_AUTO_GENERATE_H
#define VK_GLSL_SHADER_AUTO_GENERATE_H
extern const unsigned char glsl_dwweightcopy_comp[];
extern unsigned int glsl_dwweightcopy_comp_len;
extern const unsigned char glsl_deconvCol2Im_comp[];
extern unsigned int glsl_deconvCol2Im_comp_len;
extern const unsigned char glsl_convolutionDepthwiseMali_comp[];
extern unsigned int glsl_convolutionDepthwiseMali_comp_len;
extern const unsigned char glsl_convolutionDepthwiseMali_RELU_comp[];
extern unsigned int glsl_convolutionDepthwiseMali_RELU_comp_len;
extern const unsigned char glsl_convolutionDepthwiseMali_RELU6_comp[];
extern unsigned int glsl_convolutionDepthwiseMali_RELU6_comp_len;
extern const unsigned char glsl_relu_comp[];
extern unsigned int glsl_relu_comp_len;
extern const unsigned char glsl_unaryImage_comp[];
extern unsigned int glsl_unaryImage_comp_len;
extern const unsigned char glsl_unaryImage_SIGMOID_comp[];
extern unsigned int glsl_unaryImage_SIGMOID_comp_len;
extern const unsigned char glsl_unaryImage_TANH_comp[];
extern unsigned int glsl_unaryImage_TANH_comp_len;
extern const unsigned char glsl_unaryImage_ABS_comp[];
extern unsigned int glsl_unaryImage_ABS_comp_len;
extern const unsigned char glsl_unaryImage_SQRT_comp[];
extern unsigned int glsl_unaryImage_SQRT_comp_len;
extern const unsigned char glsl_unaryImage_RSQRT_comp[];
extern unsigned int glsl_unaryImage_RSQRT_comp_len;
extern const unsigned char glsl_unaryImage_NEG_comp[];
extern unsigned int glsl_unaryImage_NEG_comp_len;
extern const unsigned char glsl_unaryImage_SQUARE_comp[];
extern unsigned int glsl_unaryImage_SQUARE_comp_len;
extern const unsigned char glsl_unaryImage_EXP_comp[];
extern unsigned int glsl_unaryImage_EXP_comp_len;
extern const unsigned char glsl_unaryImage_SIGN_comp[];
extern unsigned int glsl_unaryImage_SIGN_comp_len;
extern const unsigned char glsl_unaryImage_LOG_comp[];
extern unsigned int glsl_unaryImage_LOG_comp_len;
extern const unsigned char glsl_unaryImage_TAN_comp[];
extern unsigned int glsl_unaryImage_TAN_comp_len;
extern const unsigned char glsl_unaryImage_COS_comp[];
extern unsigned int glsl_unaryImage_COS_comp_len;
extern const unsigned char glsl_unaryImage_SIN_comp[];
extern unsigned int glsl_unaryImage_SIN_comp_len;
extern const unsigned char glsl_unaryImage_CEIL_comp[];
extern unsigned int glsl_unaryImage_CEIL_comp_len;
extern const unsigned char glsl_unaryImage_FLOOR_comp[];
extern unsigned int glsl_unaryImage_FLOOR_comp_len;
extern const unsigned char glsl_unaryImage_EXPM1_comp[];
extern unsigned int glsl_unaryImage_EXPM1_comp_len;
extern const unsigned char glsl_unaryImage_RECIPROCAL_comp[];
extern unsigned int glsl_unaryImage_RECIPROCAL_comp_len;
extern const unsigned char glsl_unaryImage_SINH_comp[];
extern unsigned int glsl_unaryImage_SINH_comp_len;
extern const unsigned char glsl_unaryImage_ASINH_comp[];
extern unsigned int glsl_unaryImage_ASINH_comp_len;
extern const unsigned char glsl_unaryImage_ASIN_comp[];
extern unsigned int glsl_unaryImage_ASIN_comp_len;
extern const unsigned char glsl_unaryImage_COSH_comp[];
extern unsigned int glsl_unaryImage_COSH_comp_len;
extern const unsigned char glsl_unaryImage_ACOS_comp[];
extern unsigned int glsl_unaryImage_ACOS_comp_len;
extern const unsigned char glsl_unaryImage_ACOSH_comp[];
extern unsigned int glsl_unaryImage_ACOSH_comp_len;
extern const unsigned char glsl_unaryImage_ATAN_comp[];
extern unsigned int glsl_unaryImage_ATAN_comp_len;
extern const unsigned char glsl_unaryImage_ATANH_comp[];
extern unsigned int glsl_unaryImage_ATANH_comp_len;
extern const unsigned char glsl_unaryImage_LOG1P_comp[];
extern unsigned int glsl_unaryImage_LOG1P_comp_len;
extern const unsigned char glsl_unaryImage_ROUND_comp[];
extern unsigned int glsl_unaryImage_ROUND_comp_len;
extern const unsigned char glsl_unaryImage_HARDSWISH_comp[];
extern unsigned int glsl_unaryImage_HARDSWISH_comp_len;
extern const unsigned char glsl_unaryImage_GELU_comp[];
extern unsigned int glsl_unaryImage_GELU_comp_len;
extern const unsigned char glsl_im2col_comp[];
extern unsigned int glsl_im2col_comp_len;
extern const unsigned char glsl_convolutionDepthwise_comp[];
extern unsigned int glsl_convolutionDepthwise_comp_len;
extern const unsigned char glsl_convolutionDepthwise_RELU_comp[];
extern unsigned int glsl_convolutionDepthwise_RELU_comp_len;
extern const unsigned char glsl_convolutionDepthwise_RELU6_comp[];
extern unsigned int glsl_convolutionDepthwise_RELU6_comp_len;
extern const unsigned char glsl_gridSampleBilinear_comp[];
extern unsigned int glsl_gridSampleBilinear_comp_len;
extern const unsigned char glsl_gridSampleBilinear_PAD_MODE_ZEROS_comp[];
extern unsigned int glsl_gridSampleBilinear_PAD_MODE_ZEROS_comp_len;
extern const unsigned char glsl_gridSampleNearest_comp[];
extern unsigned int glsl_gridSampleNearest_comp_len;
extern const unsigned char glsl_gridSampleNearest_PAD_MODE_ZEROS_comp[];
extern unsigned int glsl_gridSampleNearest_PAD_MODE_ZEROS_comp_len;
extern const unsigned char glsl_relu6_comp[];
extern unsigned int glsl_relu6_comp_len;
extern const unsigned char glsl_binaryImage_comp[];
extern unsigned int glsl_binaryImage_comp_len;
extern const unsigned char glsl_binaryImage_ADD_comp[];
extern unsigned int glsl_binaryImage_ADD_comp_len;
extern const unsigned char glsl_binaryImage_SUB_comp[];
extern unsigned int glsl_binaryImage_SUB_comp_len;
extern const unsigned char glsl_binaryImage_MUL_comp[];
extern unsigned int glsl_binaryImage_MUL_comp_len;
extern const unsigned char glsl_binaryImage_DIV_comp[];
extern unsigned int glsl_binaryImage_DIV_comp_len;
extern const unsigned char glsl_binaryImage_POW_comp[];
extern unsigned int glsl_binaryImage_POW_comp_len;
extern const unsigned char glsl_binaryImage_VMAX_comp[];
extern unsigned int glsl_binaryImage_VMAX_comp_len;
extern const unsigned char glsl_binaryImage_SQUDIFF_comp[];
extern unsigned int glsl_binaryImage_SQUDIFF_comp_len;
extern const unsigned char glsl_binaryImage_VMIN_comp[];
extern unsigned int glsl_binaryImage_VMIN_comp_len;
extern const unsigned char glsl_matmul_input_comp[];
extern unsigned int glsl_matmul_input_comp_len;
extern const unsigned char glsl_matmul_input_TRANSPOSE_comp[];
extern unsigned int glsl_matmul_input_TRANSPOSE_comp_len;
extern const unsigned char glsl_nchwToimage_comp[];
extern unsigned int glsl_nchwToimage_comp_len;
extern const unsigned char glsl_packAsImage4x4_comp[];
extern unsigned int glsl_packAsImage4x4_comp_len;
extern const unsigned char glsl_packAsImage4x4_TRANSPOSE_comp[];
extern unsigned int glsl_packAsImage4x4_TRANSPOSE_comp_len;
extern const unsigned char glsl_roipooling_comp[];
extern unsigned int glsl_roipooling_comp_len;
extern const unsigned char glsl_blit_comp[];
extern unsigned int glsl_blit_comp_len;
extern const unsigned char glsl_blit_image_comp[];
extern unsigned int glsl_blit_image_comp_len;
extern const unsigned char glsl_fill_image_comp[];
extern unsigned int glsl_fill_image_comp_len;
extern const unsigned char glsl_imageTonchw_comp[];
extern unsigned int glsl_imageTonchw_comp_len;
extern const unsigned char glsl_softmaxHeight_NHWC_comp[];
extern unsigned int glsl_softmaxHeight_NHWC_comp_len;
extern const unsigned char glsl_resizeNearest_comp[];
extern unsigned int glsl_resizeNearest_comp_len;
extern const unsigned char glsl_resizeNearest_NEAREST_ROUND_comp[];
extern unsigned int glsl_resizeNearest_NEAREST_ROUND_comp_len;
extern const unsigned char glsl_reduce_comp[];
extern unsigned int glsl_reduce_comp_len;
extern const unsigned char glsl_reduce_VMAX_comp[];
extern unsigned int glsl_reduce_VMAX_comp_len;
extern const unsigned char glsl_reduce_VMIN_comp[];
extern unsigned int glsl_reduce_VMIN_comp_len;
extern const unsigned char glsl_reduce_MEAN_comp[];
extern unsigned int glsl_reduce_MEAN_comp_len;
extern const unsigned char glsl_reduce_PROD_comp[];
extern unsigned int glsl_reduce_PROD_comp_len;
extern const unsigned char glsl_reduce_SUM_comp[];
extern unsigned int glsl_reduce_SUM_comp_len;
extern const unsigned char glsl_resizeBilinear_comp[];
extern unsigned int glsl_resizeBilinear_comp_len;
extern const unsigned char glsl_nchwTonc4hw4_comp[];
extern unsigned int glsl_nchwTonc4hw4_comp_len;
extern const unsigned char glsl_nc4hw4Tonchw_comp[];
extern unsigned int glsl_nc4hw4Tonchw_comp_len;
extern const unsigned char glsl_buffer2Image2D_comp[];
extern unsigned int glsl_buffer2Image2D_comp_len;
extern const unsigned char glsl_im2col1x1_comp[];
extern unsigned int glsl_im2col1x1_comp_len;
extern const unsigned char glsl_avgpool_comp[];
extern unsigned int glsl_avgpool_comp_len;
extern const unsigned char glsl_unPackImage4x4_comp[];
extern unsigned int glsl_unPackImage4x4_comp_len;
extern const unsigned char glsl_unPackImage4x4_TRANSPOSE_comp[];
extern unsigned int glsl_unPackImage4x4_TRANSPOSE_comp_len;
extern const unsigned char glsl_maxpool_comp[];
extern unsigned int glsl_maxpool_comp_len;
extern const unsigned char glsl_winogradTransformDest2_3_1_comp[];
extern unsigned int glsl_winogradTransformDest2_3_1_comp_len;
extern const unsigned char glsl_winogradTransformDest2_3_1_RELU_comp[];
extern unsigned int glsl_winogradTransformDest2_3_1_RELU_comp_len;
extern const unsigned char glsl_winogradTransformDest2_3_1_RELU6_comp[];
extern unsigned int glsl_winogradTransformDest2_3_1_RELU6_comp_len;
extern const unsigned char glsl_winogradTransformSource2_3_1_comp[];
extern unsigned int glsl_winogradTransformSource2_3_1_comp_len;
extern const unsigned char glsl_col2Im_comp[];
extern unsigned int glsl_col2Im_comp_len;
extern const unsigned char glsl_col2Im_RELU_comp[];
extern unsigned int glsl_col2Im_RELU_comp_len;
extern const unsigned char glsl_col2Im_RELU6_comp[];
extern unsigned int glsl_col2Im_RELU6_comp_len;
extern const unsigned char glsl_nc4hw4toimage_comp[];
extern unsigned int glsl_nc4hw4toimage_comp_len;
extern const unsigned char glsl_imageTonc4hw4_comp[];
extern unsigned int glsl_imageTonc4hw4_comp_len;
extern const unsigned char glsl_matmul_output_comp[];
extern unsigned int glsl_matmul_output_comp_len;
extern const unsigned char glsl_matmul_output_BIAS_comp[];
extern unsigned int glsl_matmul_output_BIAS_comp_len;
extern const unsigned char glsl_matmul_output_TRANSPOSE_comp[];
extern unsigned int glsl_matmul_output_TRANSPOSE_comp_len;
extern const unsigned char glsl_matmul_output_TRANSPOSE_BIAS_comp[];
extern unsigned int glsl_matmul_output_TRANSPOSE_BIAS_comp_len;
extern const unsigned char glsl_gemm16x16_comp[];
extern unsigned int glsl_gemm16x16_comp_len;
extern const unsigned char glsl_gemm16x16_FP16_comp[];
extern unsigned int glsl_gemm16x16_FP16_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_comp[];
extern unsigned int glsl_deconvolutionDepthwise_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_RELU_comp[];
extern unsigned int glsl_deconvolutionDepthwise_RELU_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_RELU6_comp[];
extern unsigned int glsl_deconvolutionDepthwise_RELU6_comp_len;
extern const unsigned char glsl_preluWithChannel_comp[];
extern unsigned int glsl_preluWithChannel_comp_len;
extern const unsigned char glsl_deconvIm2Col_comp[];
extern unsigned int glsl_deconvIm2Col_comp_len;
extern const unsigned char glsl_deconvIm2Col_RELU_comp[];
extern unsigned int glsl_deconvIm2Col_RELU_comp_len;
extern const unsigned char glsl_deconvIm2Col_RELU6_comp[];
extern unsigned int glsl_deconvIm2Col_RELU6_comp_len;
extern const unsigned char glsl_buffer2Image1D_comp[];
extern unsigned int glsl_buffer2Image1D_comp_len;
extern const unsigned char glsl_scale_comp[];
extern unsigned int glsl_scale_comp_len;
extern const unsigned char glsl_buffer2Image3D_comp[];
extern unsigned int glsl_buffer2Image3D_comp_len;
#endif