# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class BinaryOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBinaryOp(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BinaryOp()
        x.Init(buf, n + offset)
        return x

    # BinaryOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BinaryOp
    def OpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # BinaryOp
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1

def BinaryOpStart(builder): builder.StartObject(2)
def BinaryOpAddOpType(builder, opType): builder.PrependInt32Slot(0, opType, 0)
def BinaryOpAddT(builder, T): builder.PrependInt32Slot(1, T, 1)
def BinaryOpEnd(builder): return builder.EndObject()
