# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

class FusedActivation(object):
    kTfLiteActNone = 0
    kTfLiteActRelu = 1
    kTfLiteActRelu1 = 2
    kTfLiteActRelu6 = 3
    kTfLiteActTanh = 4
    kTfLiteActSignBit = 5
    kTfLiteActSigmoid = 6

