# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class NonMaxSuppressionV2(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNonMaxSuppressionV2(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NonMaxSuppressionV2()
        x.Init(buf, n + offset)
        return x

    # NonMaxSuppressionV2
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def NonMaxSuppressionV2Start(builder): builder.StartObject(0)
def NonMaxSuppressionV2End(builder): return builder.EndObject()
