# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class PRelu(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsPRelu(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PRelu()
        x.Init(buf, n + offset)
        return x

    # PRelu
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PRelu
    def SlopeCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # PRelu
    def Slope(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Float32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # PRelu
    def SlopeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Float32Flags, o)
        return 0

    # PRelu
    def SlopeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def PReluStart(builder): builder.StartObject(2)
def PReluAddSlopeCount(builder, slopeCount): builder.PrependInt32Slot(0, slopeCount, 0)
def PReluAddSlope(builder, slope): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(slope), 0)
def PReluStartSlopeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def PReluEnd(builder): return builder.EndObject()
