# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class QuantizeMaxMin(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsQuantizeMaxMin(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuantizeMaxMin()
        x.Init(buf, n + offset)
        return x

    # QuantizeMaxMin
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # QuantizeMaxMin
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def QuantizeMaxMinStart(builder): builder.StartObject(1)
def QuantizeMaxMinAddT(builder, T): builder.PrependInt32Slot(0, T, 0)
def QuantizeMaxMinEnd(builder): return builder.EndObject()
