# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

class ReductionType(object):
    SUM = 0
    ASUM = 1
    SUMSQ = 2
    MEAN = 3
    MAXIMUM = 4
    MINIMUM = 5
    PROD = 6
    ANY = 7
    ALL = 8

