# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class ReverseSequenceParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsReverseSequenceParam(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReverseSequenceParam()
        x.Init(buf, n + offset)
        return x

    # ReverseSequenceParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReverseSequenceParam
    def BatchDim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ReverseSequenceParam
    def SeqDim(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ReverseSequenceParamStart(builder): builder.StartObject(2)
def ReverseSequenceParamAddBatchDim(builder, batchDim): builder.PrependInt32Slot(0, batchDim, 0)
def ReverseSequenceParamAddSeqDim(builder, seqDim): builder.PrependInt32Slot(1, seqDim, 0)
def ReverseSequenceParamEnd(builder): return builder.EndObject()
