// This file is generated by Shell for ops register
namespace MNN {
extern void ___NNAPIUnary__OpType_UnaryOp__();
extern void ___NNAPISoftmax__OpType_Softmax__();
extern void ___NNAPIConvolution__OpType_Convolution__();
extern void ___NNAPIConvolution__OpType_ConvolutionDepthwise__();
extern void ___NNAPIBinary__OpType_BinaryOp__();
extern void ___NNAPIPool__OpType_Pooling__();

void registerNNAPIOps() {
___NNAPIUnary__OpType_UnaryOp__();
___NNAPISoftmax__OpType_Softmax__();
___NNAPIConvolution__OpType_Convolution__();
___NNAPIConvolution__OpType_ConvolutionDepthwise__();
___NNAPIBinary__OpType_BinaryOp__();
___NNAPIPool__OpType_Pooling__();
}
}
