#ifndef VK_GLSL_SHADER_AUTO_GENERATE_H
#define VK_GLSL_SHADER_AUTO_GENERATE_H
extern const unsigned char glsl_float2int_comp[];
extern unsigned int glsl_float2int_comp_len;
extern const unsigned char glsl_rastersort_count_valid_number_comp[];
extern unsigned int glsl_rastersort_count_valid_number_comp_len;
extern const unsigned char glsl_rastersort_count_valid_number_USE_HALF_comp[];
extern unsigned int glsl_rastersort_count_valid_number_USE_HALF_comp_len;
extern const unsigned char glsl_texturecubegrad_comp[];
extern unsigned int glsl_texturecubegrad_comp_len;
extern const unsigned char glsl_texturecubegrad_NEAREST_comp[];
extern unsigned int glsl_texturecubegrad_NEAREST_comp_len;
extern const unsigned char glsl_load_render_unit_comp[];
extern unsigned int glsl_load_render_unit_comp_len;
extern const unsigned char glsl_copy_render_unit_comp[];
extern unsigned int glsl_copy_render_unit_comp_len;
extern const unsigned char glsl_texture2dgrad_comp[];
extern unsigned int glsl_texture2dgrad_comp_len;
extern const unsigned char glsl_texture2dgrad_NEAREST_comp[];
extern unsigned int glsl_texture2dgrad_NEAREST_comp_len;
extern const unsigned char glsl_dfdxdygrad_comp[];
extern unsigned int glsl_dfdxdygrad_comp_len;
extern const unsigned char glsl_texturecube_comp[];
extern unsigned int glsl_texturecube_comp_len;
extern const unsigned char glsl_texturecube_NEAREST_comp[];
extern unsigned int glsl_texturecube_NEAREST_comp_len;
extern const unsigned char glsl_radixsort_reorder_comp[];
extern unsigned int glsl_radixsort_reorder_comp_len;
extern const unsigned char glsl_radixsort_histogram_comp[];
extern unsigned int glsl_radixsort_histogram_comp_len;
extern const unsigned char glsl_dfdxdy_comp[];
extern unsigned int glsl_dfdxdy_comp_len;
extern const unsigned char glsl_cumsum_comp[];
extern unsigned int glsl_cumsum_comp_len;
extern const unsigned char glsl_rastersort_collect_key_comp[];
extern unsigned int glsl_rastersort_collect_key_comp_len;
extern const unsigned char glsl_rastersort_collect_key_USE_HALF_comp[];
extern unsigned int glsl_rastersort_collect_key_USE_HALF_comp_len;
extern const unsigned char glsl_int2float_comp[];
extern unsigned int glsl_int2float_comp_len;
extern const unsigned char glsl_texture2d_comp[];
extern unsigned int glsl_texture2d_comp_len;
extern const unsigned char glsl_texture2d_NEAREST_comp[];
extern unsigned int glsl_texture2d_NEAREST_comp_len;
extern const unsigned char glsl_render_frag_frag[];
extern unsigned int glsl_render_frag_frag_len;
extern const unsigned char glsl_render_vert_vert[];
extern unsigned int glsl_render_vert_vert_len;
#endif