// This file is generated by Shell for ops register
namespace MNN {
extern void ___OpType_Raster__BF16RasterFactory__();
extern void ___OpType_BinaryOp__BF16BinaryCreator__();
extern void ___OpType_Pooling__BF16PoolingCreator__();

void registerBF16Ops() {
___OpType_Raster__BF16RasterFactory__();
___OpType_BinaryOp__BF16BinaryCreator__();
___OpType_Pooling__BF16PoolingCreator__();
}
}
