# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class Crop(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCrop(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Crop()
        x.Init(buf, n + offset)
        return x

    # Crop
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Crop
    def Axis(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 2

    # Crop
    def Offset(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Crop
    def OffsetAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Crop
    def OffsetLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def CropStart(builder): builder.StartObject(2)
def CropAddAxis(builder, axis): builder.PrependInt32Slot(0, axis, 2)
def CropAddOffset(builder, offset): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(offset), 0)
def CropStartOffsetVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def CropEnd(builder): return builder.EndObject()
