# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class DepthSpaceParam(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDepthSpaceParam(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DepthSpaceParam()
        x.Init(buf, n + offset)
        return x

    # DepthSpaceParam
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DepthSpaceParam
    def BlockSize(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def DepthSpaceParamStart(builder): builder.StartObject(1)
def DepthSpaceParamAddBlockSize(builder, blockSize): builder.PrependInt32Slot(0, blockSize, 0)
def DepthSpaceParamEnd(builder): return builder.EndObject()
