# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class ELU(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsELU(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ELU()
        x.Init(buf, n + offset)
        return x

    # ELU
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ELU
    def Alpha(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def ELUStart(builder): builder.StartObject(1)
def ELUAddAlpha(builder, alpha): builder.PrependFloat32Slot(0, alpha, 0.0)
def ELUEnd(builder): return builder.EndObject()
