# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class GpuLibrary(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsGpuLibrary(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GpuLibrary()
        x.Init(buf, n + offset)
        return x

    # GpuLibrary
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GpuLibrary
    def Functions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .GpuFunction import GpuFunction
            obj = GpuFunction()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GpuLibrary
    def FunctionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GpuLibrary
    def Pipeline(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .GpuPipeline import GpuPipeline
            obj = GpuPipeline()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # GpuLibrary
    def PipelineLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # GpuLibrary
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GpuLibraryStart(builder): builder.StartObject(3)
def GpuLibraryAddFunctions(builder, functions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(functions), 0)
def GpuLibraryStartFunctionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GpuLibraryAddPipeline(builder, pipeline): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(pipeline), 0)
def GpuLibraryStartPipelineVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def GpuLibraryAddName(builder, name): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def GpuLibraryEnd(builder): return builder.EndObject()
