# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class TensorConvertInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTensorConvertInfo(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TensorConvertInfo()
        x.Init(buf, n + offset)
        return x

    # TensorConvertInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TensorConvertInfo
    def Source(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # TensorConvertInfo
    def Dest(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def TensorConvertInfoStart(builder): builder.StartObject(2)
def TensorConvertInfoAddSource(builder, source): builder.PrependInt8Slot(0, source, 0)
def TensorConvertInfoAddDest(builder, dest): builder.PrependInt8Slot(1, dest, 0)
def TensorConvertInfoEnd(builder): return builder.EndObject()
