# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MNN

import flatbuffers

class UnaryOp(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUnaryOp(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnaryOp()
        x.Init(buf, n + offset)
        return x

    # UnaryOp
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnaryOp
    def OpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # UnaryOp
    def T(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def UnaryOpStart(builder): builder.StartObject(2)
def UnaryOpAddOpType(builder, opType): builder.PrependInt32Slot(0, opType, 0)
def UnaryOpAddT(builder, T): builder.PrependInt32Slot(1, T, 0)
def UnaryOpEnd(builder): return builder.EndObject()
