#ifndef VK_GLSL_SHADER_AUTO_GENERATE_H
#define VK_GLSL_SHADER_AUTO_GENERATE_H
extern const unsigned char glsl_dwweightcopy_comp[];
extern unsigned int glsl_dwweightcopy_comp_len;
extern const unsigned char glsl_dwweightcopy_FP16_comp[];
extern unsigned int glsl_dwweightcopy_FP16_comp_len;
extern const unsigned char glsl_deconvolution_comp[];
extern unsigned int glsl_deconvolution_comp_len;
extern const unsigned char glsl_deconvolution_RELU_comp[];
extern unsigned int glsl_deconvolution_RELU_comp_len;
extern const unsigned char glsl_deconvolution_RELU6_comp[];
extern unsigned int glsl_deconvolution_RELU6_comp_len;
extern const unsigned char glsl_deconvolution_FP16_comp[];
extern unsigned int glsl_deconvolution_FP16_comp_len;
extern const unsigned char glsl_deconvolution_RELU_FP16_comp[];
extern unsigned int glsl_deconvolution_RELU_FP16_comp_len;
extern const unsigned char glsl_deconvolution_RELU6_FP16_comp[];
extern unsigned int glsl_deconvolution_RELU6_FP16_comp_len;
extern const unsigned char glsl_select_comp[];
extern unsigned int glsl_select_comp_len;
extern const unsigned char glsl_select_FP16_comp[];
extern unsigned int glsl_select_FP16_comp_len;
extern const unsigned char glsl_norm_comp[];
extern unsigned int glsl_norm_comp_len;
extern const unsigned char glsl_norm_LAYERNORM_SCALE_comp[];
extern unsigned int glsl_norm_LAYERNORM_SCALE_comp_len;
extern const unsigned char glsl_norm_FP16_comp[];
extern unsigned int glsl_norm_FP16_comp_len;
extern const unsigned char glsl_norm_LAYERNORM_SCALE_FP16_comp[];
extern unsigned int glsl_norm_LAYERNORM_SCALE_FP16_comp_len;
extern const unsigned char glsl_convolutionDepthwise_comp[];
extern unsigned int glsl_convolutionDepthwise_comp_len;
extern const unsigned char glsl_convolutionDepthwise_RELU_comp[];
extern unsigned int glsl_convolutionDepthwise_RELU_comp_len;
extern const unsigned char glsl_convolutionDepthwise_RELU6_comp[];
extern unsigned int glsl_convolutionDepthwise_RELU6_comp_len;
extern const unsigned char glsl_convolutionDepthwise_FP16_comp[];
extern unsigned int glsl_convolutionDepthwise_FP16_comp_len;
extern const unsigned char glsl_convolutionDepthwise_RELU_FP16_comp[];
extern unsigned int glsl_convolutionDepthwise_RELU_FP16_comp_len;
extern const unsigned char glsl_convolutionDepthwise_RELU6_FP16_comp[];
extern unsigned int glsl_convolutionDepthwise_RELU6_FP16_comp_len;
extern const unsigned char glsl_gridSampleBilinear_comp[];
extern unsigned int glsl_gridSampleBilinear_comp_len;
extern const unsigned char glsl_gridSampleBilinear_PAD_MODE_ZEROS_comp[];
extern unsigned int glsl_gridSampleBilinear_PAD_MODE_ZEROS_comp_len;
extern const unsigned char glsl_gridSampleBilinear_FP16_comp[];
extern unsigned int glsl_gridSampleBilinear_FP16_comp_len;
extern const unsigned char glsl_gridSampleBilinear_PAD_MODE_ZEROS_FP16_comp[];
extern unsigned int glsl_gridSampleBilinear_PAD_MODE_ZEROS_FP16_comp_len;
extern const unsigned char glsl_gridSampleNearest_comp[];
extern unsigned int glsl_gridSampleNearest_comp_len;
extern const unsigned char glsl_gridSampleNearest_PAD_MODE_ZEROS_comp[];
extern unsigned int glsl_gridSampleNearest_PAD_MODE_ZEROS_comp_len;
extern const unsigned char glsl_gridSampleNearest_FP16_comp[];
extern unsigned int glsl_gridSampleNearest_FP16_comp_len;
extern const unsigned char glsl_gridSampleNearest_PAD_MODE_ZEROS_FP16_comp[];
extern unsigned int glsl_gridSampleNearest_PAD_MODE_ZEROS_FP16_comp_len;
extern const unsigned char glsl_binary_comp[];
extern unsigned int glsl_binary_comp_len;
extern const unsigned char glsl_binary_ADD_comp[];
extern unsigned int glsl_binary_ADD_comp_len;
extern const unsigned char glsl_binary_ATAN2_comp[];
extern unsigned int glsl_binary_ATAN2_comp_len;
extern const unsigned char glsl_binary_SUB_comp[];
extern unsigned int glsl_binary_SUB_comp_len;
extern const unsigned char glsl_binary_MUL_comp[];
extern unsigned int glsl_binary_MUL_comp_len;
extern const unsigned char glsl_binary_DIV_comp[];
extern unsigned int glsl_binary_DIV_comp_len;
extern const unsigned char glsl_binary_POW_comp[];
extern unsigned int glsl_binary_POW_comp_len;
extern const unsigned char glsl_binary_VMAX_comp[];
extern unsigned int glsl_binary_VMAX_comp_len;
extern const unsigned char glsl_binary_SQUDIFF_comp[];
extern unsigned int glsl_binary_SQUDIFF_comp_len;
extern const unsigned char glsl_binary_VMIN_comp[];
extern unsigned int glsl_binary_VMIN_comp_len;
extern const unsigned char glsl_binary_LESS_comp[];
extern unsigned int glsl_binary_LESS_comp_len;
extern const unsigned char glsl_binary_LESSEQUAL_comp[];
extern unsigned int glsl_binary_LESSEQUAL_comp_len;
extern const unsigned char glsl_binary_GREATER_comp[];
extern unsigned int glsl_binary_GREATER_comp_len;
extern const unsigned char glsl_binary_GREATEREQUAL_comp[];
extern unsigned int glsl_binary_GREATEREQUAL_comp_len;
extern const unsigned char glsl_binary_EQUAL_comp[];
extern unsigned int glsl_binary_EQUAL_comp_len;
extern const unsigned char glsl_binary_NOTEQUAL_comp[];
extern unsigned int glsl_binary_NOTEQUAL_comp_len;
extern const unsigned char glsl_binary_VMOD_comp[];
extern unsigned int glsl_binary_VMOD_comp_len;
extern const unsigned char glsl_binary_FLOORDIV_comp[];
extern unsigned int glsl_binary_FLOORDIV_comp_len;
extern const unsigned char glsl_binary_FLOORMOD_comp[];
extern unsigned int glsl_binary_FLOORMOD_comp_len;
extern const unsigned char glsl_binary_FP16_comp[];
extern unsigned int glsl_binary_FP16_comp_len;
extern const unsigned char glsl_binary_ADD_FP16_comp[];
extern unsigned int glsl_binary_ADD_FP16_comp_len;
extern const unsigned char glsl_binary_ATAN2_FP16_comp[];
extern unsigned int glsl_binary_ATAN2_FP16_comp_len;
extern const unsigned char glsl_binary_SUB_FP16_comp[];
extern unsigned int glsl_binary_SUB_FP16_comp_len;
extern const unsigned char glsl_binary_MUL_FP16_comp[];
extern unsigned int glsl_binary_MUL_FP16_comp_len;
extern const unsigned char glsl_binary_DIV_FP16_comp[];
extern unsigned int glsl_binary_DIV_FP16_comp_len;
extern const unsigned char glsl_binary_POW_FP16_comp[];
extern unsigned int glsl_binary_POW_FP16_comp_len;
extern const unsigned char glsl_binary_VMAX_FP16_comp[];
extern unsigned int glsl_binary_VMAX_FP16_comp_len;
extern const unsigned char glsl_binary_SQUDIFF_FP16_comp[];
extern unsigned int glsl_binary_SQUDIFF_FP16_comp_len;
extern const unsigned char glsl_binary_VMIN_FP16_comp[];
extern unsigned int glsl_binary_VMIN_FP16_comp_len;
extern const unsigned char glsl_binary_LESS_FP16_comp[];
extern unsigned int glsl_binary_LESS_FP16_comp_len;
extern const unsigned char glsl_binary_LESSEQUAL_FP16_comp[];
extern unsigned int glsl_binary_LESSEQUAL_FP16_comp_len;
extern const unsigned char glsl_binary_GREATER_FP16_comp[];
extern unsigned int glsl_binary_GREATER_FP16_comp_len;
extern const unsigned char glsl_binary_GREATEREQUAL_FP16_comp[];
extern unsigned int glsl_binary_GREATEREQUAL_FP16_comp_len;
extern const unsigned char glsl_binary_EQUAL_FP16_comp[];
extern unsigned int glsl_binary_EQUAL_FP16_comp_len;
extern const unsigned char glsl_binary_NOTEQUAL_FP16_comp[];
extern unsigned int glsl_binary_NOTEQUAL_FP16_comp_len;
extern const unsigned char glsl_binary_VMOD_FP16_comp[];
extern unsigned int glsl_binary_VMOD_FP16_comp_len;
extern const unsigned char glsl_binary_FLOORDIV_FP16_comp[];
extern unsigned int glsl_binary_FLOORDIV_FP16_comp_len;
extern const unsigned char glsl_binary_FLOORMOD_FP16_comp[];
extern unsigned int glsl_binary_FLOORMOD_FP16_comp_len;
extern const unsigned char glsl_matmulunit_HAS_BIAS_comp[];
extern unsigned int glsl_matmulunit_HAS_BIAS_comp_len;
extern const unsigned char glsl_matmulunit_HAS_BIAS_FP16_comp[];
extern unsigned int glsl_matmulunit_HAS_BIAS_FP16_comp_len;
extern const unsigned char glsl_cast_float_int_comp[];
extern unsigned int glsl_cast_float_int_comp_len;
extern const unsigned char glsl_cast_float_int_REVERT_comp[];
extern unsigned int glsl_cast_float_int_REVERT_comp_len;
extern const unsigned char glsl_cast_float_int_FP16_comp[];
extern unsigned int glsl_cast_float_int_FP16_comp_len;
extern const unsigned char glsl_cast_float_int_REVERT_FP16_comp[];
extern unsigned int glsl_cast_float_int_REVERT_FP16_comp_len;
extern const unsigned char glsl_convolution_comp[];
extern unsigned int glsl_convolution_comp_len;
extern const unsigned char glsl_convolution_RELU_comp[];
extern unsigned int glsl_convolution_RELU_comp_len;
extern const unsigned char glsl_convolution_RELU6_comp[];
extern unsigned int glsl_convolution_RELU6_comp_len;
extern const unsigned char glsl_convolution_FP16_comp[];
extern unsigned int glsl_convolution_FP16_comp_len;
extern const unsigned char glsl_convolution_RELU_FP16_comp[];
extern unsigned int glsl_convolution_RELU_FP16_comp_len;
extern const unsigned char glsl_convolution_RELU6_FP16_comp[];
extern unsigned int glsl_convolution_RELU6_FP16_comp_len;
extern const unsigned char glsl_binary_int_comp[];
extern unsigned int glsl_binary_int_comp_len;
extern const unsigned char glsl_binary_int_ADD_comp[];
extern unsigned int glsl_binary_int_ADD_comp_len;
extern const unsigned char glsl_binary_int_SUB_comp[];
extern unsigned int glsl_binary_int_SUB_comp_len;
extern const unsigned char glsl_binary_int_MUL_comp[];
extern unsigned int glsl_binary_int_MUL_comp_len;
extern const unsigned char glsl_binary_int_DIV_comp[];
extern unsigned int glsl_binary_int_DIV_comp_len;
extern const unsigned char glsl_binary_int_VMAX_comp[];
extern unsigned int glsl_binary_int_VMAX_comp_len;
extern const unsigned char glsl_binary_int_SQUDIFF_comp[];
extern unsigned int glsl_binary_int_SQUDIFF_comp_len;
extern const unsigned char glsl_binary_int_VMIN_comp[];
extern unsigned int glsl_binary_int_VMIN_comp_len;
extern const unsigned char glsl_binary_int_LESS_comp[];
extern unsigned int glsl_binary_int_LESS_comp_len;
extern const unsigned char glsl_binary_int_LESSEQUAL_comp[];
extern unsigned int glsl_binary_int_LESSEQUAL_comp_len;
extern const unsigned char glsl_binary_int_GREATER_comp[];
extern unsigned int glsl_binary_int_GREATER_comp_len;
extern const unsigned char glsl_binary_int_GREATEREQUAL_comp[];
extern unsigned int glsl_binary_int_GREATEREQUAL_comp_len;
extern const unsigned char glsl_binary_int_EQUAL_comp[];
extern unsigned int glsl_binary_int_EQUAL_comp_len;
extern const unsigned char glsl_binary_int_NOTEQUAL_comp[];
extern unsigned int glsl_binary_int_NOTEQUAL_comp_len;
extern const unsigned char glsl_binary_int_VMOD_comp[];
extern unsigned int glsl_binary_int_VMOD_comp_len;
extern const unsigned char glsl_roipooling_comp[];
extern unsigned int glsl_roipooling_comp_len;
extern const unsigned char glsl_roipooling_FP16_comp[];
extern unsigned int glsl_roipooling_FP16_comp_len;
extern const unsigned char glsl_blit_comp[];
extern unsigned int glsl_blit_comp_len;
extern const unsigned char glsl_blit_C4_comp[];
extern unsigned int glsl_blit_C4_comp_len;
extern const unsigned char glsl_blit_FP16_comp[];
extern unsigned int glsl_blit_FP16_comp_len;
extern const unsigned char glsl_blit_C4_FP16_comp[];
extern unsigned int glsl_blit_C4_FP16_comp_len;
extern const unsigned char glsl_unary_comp[];
extern unsigned int glsl_unary_comp_len;
extern const unsigned char glsl_unary_SIGMOID_comp[];
extern unsigned int glsl_unary_SIGMOID_comp_len;
extern const unsigned char glsl_unary_TANH_comp[];
extern unsigned int glsl_unary_TANH_comp_len;
extern const unsigned char glsl_unary_ABS_comp[];
extern unsigned int glsl_unary_ABS_comp_len;
extern const unsigned char glsl_unary_SQRT_comp[];
extern unsigned int glsl_unary_SQRT_comp_len;
extern const unsigned char glsl_unary_RSQRT_comp[];
extern unsigned int glsl_unary_RSQRT_comp_len;
extern const unsigned char glsl_unary_NEG_comp[];
extern unsigned int glsl_unary_NEG_comp_len;
extern const unsigned char glsl_unary_SQUARE_comp[];
extern unsigned int glsl_unary_SQUARE_comp_len;
extern const unsigned char glsl_unary_EXP_comp[];
extern unsigned int glsl_unary_EXP_comp_len;
extern const unsigned char glsl_unary_SIGN_comp[];
extern unsigned int glsl_unary_SIGN_comp_len;
extern const unsigned char glsl_unary_LOG_comp[];
extern unsigned int glsl_unary_LOG_comp_len;
extern const unsigned char glsl_unary_TAN_comp[];
extern unsigned int glsl_unary_TAN_comp_len;
extern const unsigned char glsl_unary_COS_comp[];
extern unsigned int glsl_unary_COS_comp_len;
extern const unsigned char glsl_unary_SIN_comp[];
extern unsigned int glsl_unary_SIN_comp_len;
extern const unsigned char glsl_unary_CEIL_comp[];
extern unsigned int glsl_unary_CEIL_comp_len;
extern const unsigned char glsl_unary_FLOOR_comp[];
extern unsigned int glsl_unary_FLOOR_comp_len;
extern const unsigned char glsl_unary_EXPM1_comp[];
extern unsigned int glsl_unary_EXPM1_comp_len;
extern const unsigned char glsl_unary_RECIPROCAL_comp[];
extern unsigned int glsl_unary_RECIPROCAL_comp_len;
extern const unsigned char glsl_unary_SINH_comp[];
extern unsigned int glsl_unary_SINH_comp_len;
extern const unsigned char glsl_unary_ASINH_comp[];
extern unsigned int glsl_unary_ASINH_comp_len;
extern const unsigned char glsl_unary_ASIN_comp[];
extern unsigned int glsl_unary_ASIN_comp_len;
extern const unsigned char glsl_unary_COSH_comp[];
extern unsigned int glsl_unary_COSH_comp_len;
extern const unsigned char glsl_unary_ACOS_comp[];
extern unsigned int glsl_unary_ACOS_comp_len;
extern const unsigned char glsl_unary_ACOSH_comp[];
extern unsigned int glsl_unary_ACOSH_comp_len;
extern const unsigned char glsl_unary_ATAN_comp[];
extern unsigned int glsl_unary_ATAN_comp_len;
extern const unsigned char glsl_unary_ATANH_comp[];
extern unsigned int glsl_unary_ATANH_comp_len;
extern const unsigned char glsl_unary_LOG1P_comp[];
extern unsigned int glsl_unary_LOG1P_comp_len;
extern const unsigned char glsl_unary_ROUND_comp[];
extern unsigned int glsl_unary_ROUND_comp_len;
extern const unsigned char glsl_unary_RELU_comp[];
extern unsigned int glsl_unary_RELU_comp_len;
extern const unsigned char glsl_unary_CLAMP_comp[];
extern unsigned int glsl_unary_CLAMP_comp_len;
extern const unsigned char glsl_unary_HARDSWISH_comp[];
extern unsigned int glsl_unary_HARDSWISH_comp_len;
extern const unsigned char glsl_unary_GELU_comp[];
extern unsigned int glsl_unary_GELU_comp_len;
extern const unsigned char glsl_unary_SILU_comp[];
extern unsigned int glsl_unary_SILU_comp_len;
extern const unsigned char glsl_unary_FP16_comp[];
extern unsigned int glsl_unary_FP16_comp_len;
extern const unsigned char glsl_unary_SIGMOID_FP16_comp[];
extern unsigned int glsl_unary_SIGMOID_FP16_comp_len;
extern const unsigned char glsl_unary_TANH_FP16_comp[];
extern unsigned int glsl_unary_TANH_FP16_comp_len;
extern const unsigned char glsl_unary_ABS_FP16_comp[];
extern unsigned int glsl_unary_ABS_FP16_comp_len;
extern const unsigned char glsl_unary_SQRT_FP16_comp[];
extern unsigned int glsl_unary_SQRT_FP16_comp_len;
extern const unsigned char glsl_unary_RSQRT_FP16_comp[];
extern unsigned int glsl_unary_RSQRT_FP16_comp_len;
extern const unsigned char glsl_unary_NEG_FP16_comp[];
extern unsigned int glsl_unary_NEG_FP16_comp_len;
extern const unsigned char glsl_unary_SQUARE_FP16_comp[];
extern unsigned int glsl_unary_SQUARE_FP16_comp_len;
extern const unsigned char glsl_unary_EXP_FP16_comp[];
extern unsigned int glsl_unary_EXP_FP16_comp_len;
extern const unsigned char glsl_unary_SIGN_FP16_comp[];
extern unsigned int glsl_unary_SIGN_FP16_comp_len;
extern const unsigned char glsl_unary_LOG_FP16_comp[];
extern unsigned int glsl_unary_LOG_FP16_comp_len;
extern const unsigned char glsl_unary_TAN_FP16_comp[];
extern unsigned int glsl_unary_TAN_FP16_comp_len;
extern const unsigned char glsl_unary_COS_FP16_comp[];
extern unsigned int glsl_unary_COS_FP16_comp_len;
extern const unsigned char glsl_unary_SIN_FP16_comp[];
extern unsigned int glsl_unary_SIN_FP16_comp_len;
extern const unsigned char glsl_unary_CEIL_FP16_comp[];
extern unsigned int glsl_unary_CEIL_FP16_comp_len;
extern const unsigned char glsl_unary_FLOOR_FP16_comp[];
extern unsigned int glsl_unary_FLOOR_FP16_comp_len;
extern const unsigned char glsl_unary_EXPM1_FP16_comp[];
extern unsigned int glsl_unary_EXPM1_FP16_comp_len;
extern const unsigned char glsl_unary_RECIPROCAL_FP16_comp[];
extern unsigned int glsl_unary_RECIPROCAL_FP16_comp_len;
extern const unsigned char glsl_unary_SINH_FP16_comp[];
extern unsigned int glsl_unary_SINH_FP16_comp_len;
extern const unsigned char glsl_unary_ASINH_FP16_comp[];
extern unsigned int glsl_unary_ASINH_FP16_comp_len;
extern const unsigned char glsl_unary_ASIN_FP16_comp[];
extern unsigned int glsl_unary_ASIN_FP16_comp_len;
extern const unsigned char glsl_unary_COSH_FP16_comp[];
extern unsigned int glsl_unary_COSH_FP16_comp_len;
extern const unsigned char glsl_unary_ACOS_FP16_comp[];
extern unsigned int glsl_unary_ACOS_FP16_comp_len;
extern const unsigned char glsl_unary_ACOSH_FP16_comp[];
extern unsigned int glsl_unary_ACOSH_FP16_comp_len;
extern const unsigned char glsl_unary_ATAN_FP16_comp[];
extern unsigned int glsl_unary_ATAN_FP16_comp_len;
extern const unsigned char glsl_unary_ATANH_FP16_comp[];
extern unsigned int glsl_unary_ATANH_FP16_comp_len;
extern const unsigned char glsl_unary_LOG1P_FP16_comp[];
extern unsigned int glsl_unary_LOG1P_FP16_comp_len;
extern const unsigned char glsl_unary_ROUND_FP16_comp[];
extern unsigned int glsl_unary_ROUND_FP16_comp_len;
extern const unsigned char glsl_unary_RELU_FP16_comp[];
extern unsigned int glsl_unary_RELU_FP16_comp_len;
extern const unsigned char glsl_unary_CLAMP_FP16_comp[];
extern unsigned int glsl_unary_CLAMP_FP16_comp_len;
extern const unsigned char glsl_unary_HARDSWISH_FP16_comp[];
extern unsigned int glsl_unary_HARDSWISH_FP16_comp_len;
extern const unsigned char glsl_unary_GELU_FP16_comp[];
extern unsigned int glsl_unary_GELU_FP16_comp_len;
extern const unsigned char glsl_unary_SILU_FP16_comp[];
extern unsigned int glsl_unary_SILU_FP16_comp_len;
extern const unsigned char glsl_int4_weight_to_coop_comp[];
extern unsigned int glsl_int4_weight_to_coop_comp_len;
extern const unsigned char glsl_int4_weight_to_coop_FP16_comp[];
extern unsigned int glsl_int4_weight_to_coop_FP16_comp_len;
extern const unsigned char glsl_softmaxHeight_NHWC_comp[];
extern unsigned int glsl_softmaxHeight_NHWC_comp_len;
extern const unsigned char glsl_softmaxHeight_NHWC_FP16_comp[];
extern unsigned int glsl_softmaxHeight_NHWC_FP16_comp_len;
extern const unsigned char glsl_resizeNearest_comp[];
extern unsigned int glsl_resizeNearest_comp_len;
extern const unsigned char glsl_resizeNearest_NEAREST_ROUND_comp[];
extern unsigned int glsl_resizeNearest_NEAREST_ROUND_comp_len;
extern const unsigned char glsl_resizeNearest_FP16_comp[];
extern unsigned int glsl_resizeNearest_FP16_comp_len;
extern const unsigned char glsl_resizeNearest_NEAREST_ROUND_FP16_comp[];
extern unsigned int glsl_resizeNearest_NEAREST_ROUND_FP16_comp_len;
extern const unsigned char glsl_reduce_comp[];
extern unsigned int glsl_reduce_comp_len;
extern const unsigned char glsl_reduce_VMAX_comp[];
extern unsigned int glsl_reduce_VMAX_comp_len;
extern const unsigned char glsl_reduce_VMIN_comp[];
extern unsigned int glsl_reduce_VMIN_comp_len;
extern const unsigned char glsl_reduce_MEAN_comp[];
extern unsigned int glsl_reduce_MEAN_comp_len;
extern const unsigned char glsl_reduce_PROD_comp[];
extern unsigned int glsl_reduce_PROD_comp_len;
extern const unsigned char glsl_reduce_SUM_comp[];
extern unsigned int glsl_reduce_SUM_comp_len;
extern const unsigned char glsl_reduce_FP16_comp[];
extern unsigned int glsl_reduce_FP16_comp_len;
extern const unsigned char glsl_reduce_VMAX_FP16_comp[];
extern unsigned int glsl_reduce_VMAX_FP16_comp_len;
extern const unsigned char glsl_reduce_VMIN_FP16_comp[];
extern unsigned int glsl_reduce_VMIN_FP16_comp_len;
extern const unsigned char glsl_reduce_MEAN_FP16_comp[];
extern unsigned int glsl_reduce_MEAN_FP16_comp_len;
extern const unsigned char glsl_reduce_PROD_FP16_comp[];
extern unsigned int glsl_reduce_PROD_FP16_comp_len;
extern const unsigned char glsl_reduce_SUM_FP16_comp[];
extern unsigned int glsl_reduce_SUM_FP16_comp_len;
extern const unsigned char glsl_resizeBilinear_comp[];
extern unsigned int glsl_resizeBilinear_comp_len;
extern const unsigned char glsl_resizeBilinear_FP16_comp[];
extern unsigned int glsl_resizeBilinear_FP16_comp_len;
extern const unsigned char glsl_cast_int_bool_comp[];
extern unsigned int glsl_cast_int_bool_comp_len;
extern const unsigned char glsl_nchwTonc4hw4_comp[];
extern unsigned int glsl_nchwTonc4hw4_comp_len;
extern const unsigned char glsl_nchwTonc4hw4_FP16_comp[];
extern unsigned int glsl_nchwTonc4hw4_FP16_comp_len;
extern const unsigned char glsl_nc4hw4Tonchw_comp[];
extern unsigned int glsl_nc4hw4Tonchw_comp_len;
extern const unsigned char glsl_nc4hw4Tonchw_FP16_comp[];
extern unsigned int glsl_nc4hw4Tonchw_FP16_comp_len;
extern const unsigned char glsl_C4_to_COOP_comp[];
extern unsigned int glsl_C4_to_COOP_comp_len;
extern const unsigned char glsl_C4_to_COOP_FP16_comp[];
extern unsigned int glsl_C4_to_COOP_FP16_comp_len;
extern const unsigned char glsl_matmulunit_comp[];
extern unsigned int glsl_matmulunit_comp_len;
extern const unsigned char glsl_matmulunit_FP16_comp[];
extern unsigned int glsl_matmulunit_FP16_comp_len;
extern const unsigned char glsl_blitregion_comp[];
extern unsigned int glsl_blitregion_comp_len;
extern const unsigned char glsl_blitregion_FP16_comp[];
extern unsigned int glsl_blitregion_FP16_comp_len;
extern const unsigned char glsl_range_comp[];
extern unsigned int glsl_range_comp_len;
extern const unsigned char glsl_range_USE_INT_comp[];
extern unsigned int glsl_range_USE_INT_comp_len;
extern const unsigned char glsl_range_FP16_comp[];
extern unsigned int glsl_range_FP16_comp_len;
extern const unsigned char glsl_range_USE_INT_FP16_comp[];
extern unsigned int glsl_range_USE_INT_FP16_comp_len;
extern const unsigned char glsl_convolutionint4_comp[];
extern unsigned int glsl_convolutionint4_comp_len;
extern const unsigned char glsl_convolutionint4_RELU_comp[];
extern unsigned int glsl_convolutionint4_RELU_comp_len;
extern const unsigned char glsl_convolutionint4_RELU6_comp[];
extern unsigned int glsl_convolutionint4_RELU6_comp_len;
extern const unsigned char glsl_convolutionint4_FP16_comp[];
extern unsigned int glsl_convolutionint4_FP16_comp_len;
extern const unsigned char glsl_convolutionint4_RELU_FP16_comp[];
extern unsigned int glsl_convolutionint4_RELU_FP16_comp_len;
extern const unsigned char glsl_convolutionint4_RELU6_FP16_comp[];
extern unsigned int glsl_convolutionint4_RELU6_FP16_comp_len;
extern const unsigned char glsl_avgpool_comp[];
extern unsigned int glsl_avgpool_comp_len;
extern const unsigned char glsl_avgpool_FP16_comp[];
extern unsigned int glsl_avgpool_FP16_comp_len;
extern const unsigned char glsl_maxpool_comp[];
extern unsigned int glsl_maxpool_comp_len;
extern const unsigned char glsl_maxpool_FP16_comp[];
extern unsigned int glsl_maxpool_FP16_comp_len;
extern const unsigned char glsl_convolutionint8_comp[];
extern unsigned int glsl_convolutionint8_comp_len;
extern const unsigned char glsl_convolutionint8_RELU_comp[];
extern unsigned int glsl_convolutionint8_RELU_comp_len;
extern const unsigned char glsl_convolutionint8_RELU6_comp[];
extern unsigned int glsl_convolutionint8_RELU6_comp_len;
extern const unsigned char glsl_convolutionint8_FP16_comp[];
extern unsigned int glsl_convolutionint8_FP16_comp_len;
extern const unsigned char glsl_convolutionint8_RELU_FP16_comp[];
extern unsigned int glsl_convolutionint8_RELU_FP16_comp_len;
extern const unsigned char glsl_convolutionint8_RELU6_FP16_comp[];
extern unsigned int glsl_convolutionint8_RELU6_FP16_comp_len;
extern const unsigned char glsl_COOP_to_C4_comp[];
extern unsigned int glsl_COOP_to_C4_comp_len;
extern const unsigned char glsl_COOP_to_C4_FP16_comp[];
extern unsigned int glsl_COOP_to_C4_FP16_comp_len;
extern const unsigned char glsl_onehot_comp[];
extern unsigned int glsl_onehot_comp_len;
extern const unsigned char glsl_onehot_FP16_comp[];
extern unsigned int glsl_onehot_FP16_comp_len;
extern const unsigned char glsl_binary_blit_comp[];
extern unsigned int glsl_binary_blit_comp_len;
extern const unsigned char glsl_binary_blit_ADD_comp[];
extern unsigned int glsl_binary_blit_ADD_comp_len;
extern const unsigned char glsl_binary_blit_ATAN2_comp[];
extern unsigned int glsl_binary_blit_ATAN2_comp_len;
extern const unsigned char glsl_binary_blit_SUB_comp[];
extern unsigned int glsl_binary_blit_SUB_comp_len;
extern const unsigned char glsl_binary_blit_MUL_comp[];
extern unsigned int glsl_binary_blit_MUL_comp_len;
extern const unsigned char glsl_binary_blit_DIV_comp[];
extern unsigned int glsl_binary_blit_DIV_comp_len;
extern const unsigned char glsl_binary_blit_POW_comp[];
extern unsigned int glsl_binary_blit_POW_comp_len;
extern const unsigned char glsl_binary_blit_VMAX_comp[];
extern unsigned int glsl_binary_blit_VMAX_comp_len;
extern const unsigned char glsl_binary_blit_SQUDIFF_comp[];
extern unsigned int glsl_binary_blit_SQUDIFF_comp_len;
extern const unsigned char glsl_binary_blit_VMIN_comp[];
extern unsigned int glsl_binary_blit_VMIN_comp_len;
extern const unsigned char glsl_binary_blit_LESS_comp[];
extern unsigned int glsl_binary_blit_LESS_comp_len;
extern const unsigned char glsl_binary_blit_LESSEQUAL_comp[];
extern unsigned int glsl_binary_blit_LESSEQUAL_comp_len;
extern const unsigned char glsl_binary_blit_GREATER_comp[];
extern unsigned int glsl_binary_blit_GREATER_comp_len;
extern const unsigned char glsl_binary_blit_GREATEREQUAL_comp[];
extern unsigned int glsl_binary_blit_GREATEREQUAL_comp_len;
extern const unsigned char glsl_binary_blit_EQUAL_comp[];
extern unsigned int glsl_binary_blit_EQUAL_comp_len;
extern const unsigned char glsl_binary_blit_NOTEQUAL_comp[];
extern unsigned int glsl_binary_blit_NOTEQUAL_comp_len;
extern const unsigned char glsl_binary_blit_VMOD_comp[];
extern unsigned int glsl_binary_blit_VMOD_comp_len;
extern const unsigned char glsl_binary_blit_FLOORDIV_comp[];
extern unsigned int glsl_binary_blit_FLOORDIV_comp_len;
extern const unsigned char glsl_binary_blit_FLOORMOD_comp[];
extern unsigned int glsl_binary_blit_FLOORMOD_comp_len;
extern const unsigned char glsl_binary_blit_FP16_comp[];
extern unsigned int glsl_binary_blit_FP16_comp_len;
extern const unsigned char glsl_binary_blit_ADD_FP16_comp[];
extern unsigned int glsl_binary_blit_ADD_FP16_comp_len;
extern const unsigned char glsl_binary_blit_ATAN2_FP16_comp[];
extern unsigned int glsl_binary_blit_ATAN2_FP16_comp_len;
extern const unsigned char glsl_binary_blit_SUB_FP16_comp[];
extern unsigned int glsl_binary_blit_SUB_FP16_comp_len;
extern const unsigned char glsl_binary_blit_MUL_FP16_comp[];
extern unsigned int glsl_binary_blit_MUL_FP16_comp_len;
extern const unsigned char glsl_binary_blit_DIV_FP16_comp[];
extern unsigned int glsl_binary_blit_DIV_FP16_comp_len;
extern const unsigned char glsl_binary_blit_POW_FP16_comp[];
extern unsigned int glsl_binary_blit_POW_FP16_comp_len;
extern const unsigned char glsl_binary_blit_VMAX_FP16_comp[];
extern unsigned int glsl_binary_blit_VMAX_FP16_comp_len;
extern const unsigned char glsl_binary_blit_SQUDIFF_FP16_comp[];
extern unsigned int glsl_binary_blit_SQUDIFF_FP16_comp_len;
extern const unsigned char glsl_binary_blit_VMIN_FP16_comp[];
extern unsigned int glsl_binary_blit_VMIN_FP16_comp_len;
extern const unsigned char glsl_binary_blit_LESS_FP16_comp[];
extern unsigned int glsl_binary_blit_LESS_FP16_comp_len;
extern const unsigned char glsl_binary_blit_LESSEQUAL_FP16_comp[];
extern unsigned int glsl_binary_blit_LESSEQUAL_FP16_comp_len;
extern const unsigned char glsl_binary_blit_GREATER_FP16_comp[];
extern unsigned int glsl_binary_blit_GREATER_FP16_comp_len;
extern const unsigned char glsl_binary_blit_GREATEREQUAL_FP16_comp[];
extern unsigned int glsl_binary_blit_GREATEREQUAL_FP16_comp_len;
extern const unsigned char glsl_binary_blit_EQUAL_FP16_comp[];
extern unsigned int glsl_binary_blit_EQUAL_FP16_comp_len;
extern const unsigned char glsl_binary_blit_NOTEQUAL_FP16_comp[];
extern unsigned int glsl_binary_blit_NOTEQUAL_FP16_comp_len;
extern const unsigned char glsl_binary_blit_VMOD_FP16_comp[];
extern unsigned int glsl_binary_blit_VMOD_FP16_comp_len;
extern const unsigned char glsl_binary_blit_FLOORDIV_FP16_comp[];
extern unsigned int glsl_binary_blit_FLOORDIV_FP16_comp_len;
extern const unsigned char glsl_binary_blit_FLOORMOD_FP16_comp[];
extern unsigned int glsl_binary_blit_FLOORMOD_FP16_comp_len;
extern const unsigned char glsl_unary_int_comp[];
extern unsigned int glsl_unary_int_comp_len;
extern const unsigned char glsl_unary_int_ABS_comp[];
extern unsigned int glsl_unary_int_ABS_comp_len;
extern const unsigned char glsl_unary_int_NEG_comp[];
extern unsigned int glsl_unary_int_NEG_comp_len;
extern const unsigned char glsl_unary_int_SQUARE_comp[];
extern unsigned int glsl_unary_int_SQUARE_comp_len;
extern const unsigned char glsl_unary_int_SIGN_comp[];
extern unsigned int glsl_unary_int_SIGN_comp_len;
extern const unsigned char glsl_matmul_coop_comp[];
extern unsigned int glsl_matmul_coop_comp_len;
extern const unsigned char glsl_matmul_coop_FP16_comp[];
extern unsigned int glsl_matmul_coop_FP16_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_comp[];
extern unsigned int glsl_deconvolutionDepthwise_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_RELU_comp[];
extern unsigned int glsl_deconvolutionDepthwise_RELU_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_RELU6_comp[];
extern unsigned int glsl_deconvolutionDepthwise_RELU6_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_FP16_comp[];
extern unsigned int glsl_deconvolutionDepthwise_FP16_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_RELU_FP16_comp[];
extern unsigned int glsl_deconvolutionDepthwise_RELU_FP16_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_RELU6_FP16_comp[];
extern unsigned int glsl_deconvolutionDepthwise_RELU6_FP16_comp_len;
extern const unsigned char glsl_preluWithChannel_comp[];
extern unsigned int glsl_preluWithChannel_comp_len;
extern const unsigned char glsl_preluWithChannel_FP16_comp[];
extern unsigned int glsl_preluWithChannel_FP16_comp_len;
extern const unsigned char glsl_reduce_int_comp[];
extern unsigned int glsl_reduce_int_comp_len;
extern const unsigned char glsl_reduce_int_VMAX_comp[];
extern unsigned int glsl_reduce_int_VMAX_comp_len;
extern const unsigned char glsl_reduce_int_VMIN_comp[];
extern unsigned int glsl_reduce_int_VMIN_comp_len;
extern const unsigned char glsl_reduce_int_MEAN_comp[];
extern unsigned int glsl_reduce_int_MEAN_comp_len;
extern const unsigned char glsl_reduce_int_PROD_comp[];
extern unsigned int glsl_reduce_int_PROD_comp_len;
extern const unsigned char glsl_reduce_int_SUM_comp[];
extern unsigned int glsl_reduce_int_SUM_comp_len;
extern const unsigned char glsl_scale_comp[];
extern unsigned int glsl_scale_comp_len;
extern const unsigned char glsl_scale_FP16_comp[];
extern unsigned int glsl_scale_FP16_comp_len;
extern const unsigned char glsl_argmax_comp[];
extern unsigned int glsl_argmax_comp_len;
extern const unsigned char glsl_argmax_ARGMIN_comp[];
extern unsigned int glsl_argmax_ARGMIN_comp_len;
extern const unsigned char glsl_argmax_FP16_comp[];
extern unsigned int glsl_argmax_FP16_comp_len;
extern const unsigned char glsl_argmax_ARGMIN_FP16_comp[];
extern unsigned int glsl_argmax_ARGMIN_FP16_comp_len;
extern const unsigned char glsl_int8_weight_to_coop_comp[];
extern unsigned int glsl_int8_weight_to_coop_comp_len;
extern const unsigned char glsl_int8_weight_to_coop_FP16_comp[];
extern unsigned int glsl_int8_weight_to_coop_FP16_comp_len;
extern const unsigned char glsl_binary_blit_int_comp[];
extern unsigned int glsl_binary_blit_int_comp_len;
extern const unsigned char glsl_binary_blit_int_ADD_comp[];
extern unsigned int glsl_binary_blit_int_ADD_comp_len;
extern const unsigned char glsl_binary_blit_int_SUB_comp[];
extern unsigned int glsl_binary_blit_int_SUB_comp_len;
extern const unsigned char glsl_binary_blit_int_MUL_comp[];
extern unsigned int glsl_binary_blit_int_MUL_comp_len;
extern const unsigned char glsl_binary_blit_int_DIV_comp[];
extern unsigned int glsl_binary_blit_int_DIV_comp_len;
extern const unsigned char glsl_binary_blit_int_VMAX_comp[];
extern unsigned int glsl_binary_blit_int_VMAX_comp_len;
extern const unsigned char glsl_binary_blit_int_SQUDIFF_comp[];
extern unsigned int glsl_binary_blit_int_SQUDIFF_comp_len;
extern const unsigned char glsl_binary_blit_int_VMIN_comp[];
extern unsigned int glsl_binary_blit_int_VMIN_comp_len;
extern const unsigned char glsl_binary_blit_int_LESS_comp[];
extern unsigned int glsl_binary_blit_int_LESS_comp_len;
extern const unsigned char glsl_binary_blit_int_LESSEQUAL_comp[];
extern unsigned int glsl_binary_blit_int_LESSEQUAL_comp_len;
extern const unsigned char glsl_binary_blit_int_GREATER_comp[];
extern unsigned int glsl_binary_blit_int_GREATER_comp_len;
extern const unsigned char glsl_binary_blit_int_GREATEREQUAL_comp[];
extern unsigned int glsl_binary_blit_int_GREATEREQUAL_comp_len;
extern const unsigned char glsl_binary_blit_int_EQUAL_comp[];
extern unsigned int glsl_binary_blit_int_EQUAL_comp_len;
extern const unsigned char glsl_binary_blit_int_NOTEQUAL_comp[];
extern unsigned int glsl_binary_blit_int_NOTEQUAL_comp_len;
extern const unsigned char glsl_binary_blit_int_VMOD_comp[];
extern unsigned int glsl_binary_blit_int_VMOD_comp_len;
#endif