#ifndef DSP_OP_NAME_H
#define DSP_OP_NAME_H
#include "backend/hexagon/htp-ops-lib/include/htp_command.h"
inline const char* getDSPOpName(int type) {
    switch (type) {
        case DSP_OP_POOL2D_FP16:
            return "POOL2D_FP16";
        case DSP_OP_CONV_DEPTHWISE2D_FP16:
            return "CONV_DEPTHWISE2D_FP16";
        case DSP_OP_RASTER_BLIT:
            return "RASTER_BLIT";
        case DSP_OP_UNARY:
            return "UNARY";
        case DSP_OP_BINARY_BLIT:
            return "BINARY_BLIT";
        case DSP_OP_LOOP_BLIT:
            return "LOOP_BLIT";
        case DSP_OP_TENSOR_CONVERT:
            return "TENSOR_CONVERT";
        case DSP_OP_LAYER_NORM:
            return "LAYER_NORM";
        case DSP_OP_LAYER_NORM_PACKED:
            return "LAYER_NORM_PACKED";
        case DSP_OP_WEIGHT_REORDER:
            return "WEIGHT_REORDER";
        case DSP_OP_WEIGHT_REORDER_INT4:
            return "WEIGHT_REORDER_INT4";
        case DSP_OP_IM2COL_CONVOLUTION_FP16:
            return "IM2COL_CONVOLUTION_FP16";
        case DSP_OP_SCALE:
            return "SCALE";
        case DSP_OP_ROPE:
            return "ROPE";
        case DSP_OP_ROPE_FUSE_LAYERNORM:
            return "ROPE_FUSE_LAYERNORM";
        case DSP_OP_ADD_FUSE_LAYERNORM:
            return "ADD_FUSE_LAYERNORM";
        case DSP_OP_CONV1X1_DIRECT_FP16:
            return "CONV1X1_DIRECT_FP16";
        case DSP_OP_FLASH_ATTN:
            return "FLASH_ATTN";
        case DSP_OP_BINARY_ELEMENTWISE:
            return "BINARY_ELEMENTWISE";
        case DSP_OP_GET_INFO:
            return "GET_INFO";
        case DSP_OP_MATMUL_Q4A16_FP16:
            return "MATMUL_Q4A16_FP16";
        case DSP_OP_TMAC_A16W1:
            return "TMAC_A16W1";
        case DSP_OP_MATMUL_Q4A16_BLOCK_FP16:
            return "MATMUL_Q4A16_BLOCK_FP16";
        case DSP_OP_SHARED_GATHER:
            return "SHARED_GATHER";
        case DSP_OP_ZERO:
            return "ZERO";
        case DSP_OP_CAST:
            return "CAST";
        case DSP_OP_SELECT:
            return "SELECT";
        case DSP_OP_TOPKV2_K1_FP16:
            return "TOPKV2_K1_FP16";
        case DSP_OP_SOFTMAX:
            return "SOFTMAX";
        case DSP_OP_REDUCTION:
            return "REDUCTION";
        case DSP_OP_RELU6:
            return "RELU6";
        case DSP_OP_MASKED_REDUCTION:
            return "MASKED_REDUCTION";
        case DSP_OP_FLASH_ATTENTION_BLOCK:
            return "FLASH_ATTENTION_BLOCK";
        case DSP_OP_POST_ATTN_REDUCE_FUSE:
            return "POST_ATTN_REDUCE_FUSE";
        case DSP_OP_LSTM:
            return "LSTM";
        case DSP_OP_RELU:
            return "RELU";
        case DSP_OP_BATCH_MATMUL:
            return "BATCH_MATMUL";
        case DSP_OP_PRELU:
            return "PRELU";
        case DSP_OP_COMMAND_GROUP:
            return "COMMAND_GROUP";
        case 100:
            return "TENSOR_CONVERT_TYPE0_NC4HW4_TO_NCHW";
        case 101:
            return "TENSOR_CONVERT_TYPE1_NCHW_TO_NC4HW4";
        case 102:
            return "TENSOR_CONVERT_TYPE2_COPY";
        case 103:
            return "TENSOR_CONVERT_TYPE3_FLATTEN_CW";
        case 120:
            return "UNARY_ABS";
        case 121:
            return "UNARY_NEG";
        case 122:
            return "UNARY_GELU";
        case 123:
            return "UNARY_SIGMOID";
        case 124:
            return "UNARY_EXP";
        case 125:
            return "UNARY_LOG";
        case 126:
            return "UNARY_SILU";
        case 127:
            return "UNARY_TANH";
        case 128:
            return "UNARY_SQUARE";
        case 129:
            return "UNARY_SQRT";
        case 130:
            return "UNARY_RSQRT";
        case 131:
            return "UNARY_EXPM1";
        case 132:
            return "UNARY_COS";
        case 133:
            return "UNARY_SIN";
        default:
            return "UNKNOWN_DSP_OP";
    }
}
#endif
