#!/usr/bin/env python3
"""Pack Metal shader source into a compressed blob at build time.

Metal shaders are handed to newLibraryWithSource: at runtime, so their text has
to ship inside the binary. Stored as plain C string literals they land in
__TEXT,__cstring and dominate the Metal backend's contribution to the binary.
This script minifies each shader and re-encodes it with the byte-oriented LZ77
scheme that MetalShaderCodec.cpp decodes, then emits a generated source file
plus a header that redefines each shader symbol as an accessor.

Usage:
    packshader.py <metal-source-dir> <out.cpp> <out.hpp>

Deterministic: the same inputs always produce byte-identical outputs.
Depends only on the Python standard library.
"""

import os
import re
import sys

MIN_MATCH = 4
MAX_LITERAL_RUN = 0x7F
SHORT_MATCH_LIMIT = 0x3F
WINDOW = 1 << 16
MAX_CANDIDATES = 48

# Only files that gate their raw definitions behind MNN_METAL_PACK_SHADER may
# be listed here; packing an ungated file would ship the same shader text twice.
RAW_LITERAL_FILES = [
    "ConvSimdGroupShader.hpp",
    "MetalAttentionShader.hpp",
    "MetalLinearAttentionShader.hpp",
    "LayerNormSimdGroupShader.hpp",
    "MetalFlashAttnShader.hpp",
]
# AllShader.cpp is generated by makeshader.py and stores each shader as a run of
# concatenated C string literals instead of a raw literal.
ALLSHADER_FILE = "AllShader.cpp"

RAW_LITERAL_RE = re.compile(
    r'(?:static\s+)?const\s+char\s*\*\s*(\w+)\s*=\s*R"metal\((.*?)\)metal"\s*;',
    re.S,
)
ALLSHADER_RE = re.compile(
    r'const\s+char\s*\*\s*(\w+)\s*=\s*((?:"(?:[^"\\]|\\.)*"\s*)+);',
    re.S,
)
C_ESCAPES = {
    "n": "\n", "t": "\t", "r": "\r", "\\": "\\", '"': '"',
    "'": "'", "0": "\0", "a": "\a", "b": "\b", "f": "\f", "v": "\v",
}


def unescape_c(text):
    out = []
    i = 0
    while i < len(text):
        ch = text[i]
        if ch == "\\" and i + 1 < len(text):
            nxt = text[i + 1]
            if nxt in C_ESCAPES:
                out.append(C_ESCAPES[nxt])
                i += 2
                continue
        out.append(ch)
        i += 1
    return "".join(out)


def minify(text):
    """Strip comments and indentation from Metal source.

    Careful about three things that make a naive regex wrong:
      * `//` and `/*` inside string literals are not comments. Metal uses
        string literals in [[host_name("...")]] attributes.
      * A line ending in `\\` continues a preprocessor macro body, so its
        newline must survive or the macro silently changes meaning.
      * Preprocessor directives must stay on their own line.
    """
    out = []
    i = 0
    n = len(text)
    quote = None
    while i < n:
        ch = text[i]
        if quote is not None:
            out.append(ch)
            if ch == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 2
                continue
            if ch == quote:
                quote = None
            i += 1
            continue
        if ch in ('"', "'"):
            quote = ch
            out.append(ch)
            i += 1
            continue
        if ch == "/" and i + 1 < n and text[i + 1] == "/":
            end = text.find("\n", i)
            i = n if end < 0 else end
            continue
        if ch == "/" and i + 1 < n and text[i + 1] == "*":
            end = text.find("*/", i + 2)
            i = n if end < 0 else end + 2
            # A comment can join two tokens, so leave a separator behind.
            out.append(" ")
            continue
        out.append(ch)
        i += 1

    lines = []
    for line in "".join(out).split("\n"):
        stripped = line.strip()
        if not stripped:
            continue
        lines.append(stripped)
    # Call sites concatenate shaders directly, so the text must end on a line
    # boundary or the next shader's first line (often a #if) gets glued on.
    lines.append("")
    return "\n".join(lines)


def varint(value, out):
    while value >= 0x80:
        out.append((value & 0x7F) | 0x80)
        value >>= 7
    out.append(value)


def varint_len(value):
    count = 1
    while value >= 0x80:
        count += 1
        value >>= 7
    return count


def find_matches(data):
    """Longest previous match at each position, within WINDOW."""
    n = len(data)
    table = {}
    best = [(0, 0)] * n
    for i in range(n):
        if i + MIN_MATCH > n:
            continue
        key = data[i:i + MIN_MATCH]
        candidates = table.get(key)
        length = 0
        offset = 0
        if candidates:
            for cand in reversed(candidates[-MAX_CANDIDATES:]):
                distance = i - cand
                if distance >= WINDOW:
                    break
                probe = MIN_MATCH
                while i + probe < n and data[cand + probe] == data[i + probe]:
                    probe += 1
                if probe > length:
                    length = probe
                    offset = distance
                if length >= 255:
                    break
        table.setdefault(key, []).append(i)
        best[i] = (length, offset)
    return best


def encode(data):
    """LZ77-encode with a shortest-path parse over literal/match choices."""
    n = len(data)
    matches = find_matches(data)
    INF = float("inf")
    cost = [INF] * (n + 1)
    cost[n] = 0
    action = [None] * (n + 1)
    for i in range(n - 1, -1, -1):
        # A literal costs its own byte; the run's control byte is amortised and
        # slightly under-counted, which only makes the parse marginally greedy.
        best = cost[i + 1] + 1
        act = ("lit",)
        length, offset = matches[i]
        if length >= MIN_MATCH:
            for candidate in {length, MIN_MATCH, min(length, MIN_MATCH + SHORT_MATCH_LIMIT - 1)}:
                if candidate < MIN_MATCH or i + candidate > n:
                    continue
                extra = candidate - MIN_MATCH
                tokens = 1 + (0 if extra < SHORT_MATCH_LIMIT else varint_len(extra))
                total = tokens + varint_len(offset) + cost[i + candidate]
                if total < best:
                    best = total
                    act = ("match", candidate, offset)
        cost[i] = best
        action[i] = act

    out = bytearray()
    pending = bytearray()
    rep = 0
    i = 0

    def flush():
        while pending:
            take = min(len(pending), MAX_LITERAL_RUN)
            if take < MAX_LITERAL_RUN:
                out.append(take)
                out.extend(pending[:take])
                del pending[:take]
            else:
                out.append(0)
                varint(len(pending), out)
                out.extend(pending)
                del pending[:]

    def emit_match(length, offset, reuse):
        extra = length - MIN_MATCH
        ctrl = 0x80 | (0x40 if reuse else 0x00)
        if extra < SHORT_MATCH_LIMIT:
            out.append(ctrl | extra)
        else:
            out.append(ctrl | SHORT_MATCH_LIMIT)
            varint(extra, out)
        if not reuse:
            varint(offset, out)

    while i < n:
        act = action[i]
        if act[0] == "lit":
            pending.append(data[i])
            i += 1
            continue
        _, length, offset = act
        # Reusing the previous offset drops its varint, so take it whenever it
        # is not clearly worse than the offset the parse picked.
        if rep and rep <= i:
            probe = 0
            start = i - rep
            while i + probe < n and data[start + probe] == data[i + probe]:
                probe += 1
            if probe >= MIN_MATCH and probe + 1 >= length:
                flush()
                emit_match(probe, rep, True)
                i += probe
                continue
        flush()
        emit_match(length, offset, False)
        rep = offset
        i += length
    flush()
    return bytes(out)


def decode(packed, raw_size):
    """Reference decoder, mirrors MetalShaderCodec.cpp. Used for self-check."""
    out = bytearray()
    i = 0
    rep = 0

    def read_varint():
        nonlocal i
        result = 0
        shift = 0
        while True:
            byte = packed[i]
            i += 1
            result |= (byte & 0x7F) << shift
            shift += 7
            if byte < 0x80:
                return result

    while len(out) < raw_size:
        ctrl = packed[i]
        i += 1
        if ctrl < 0x80:
            length = ctrl if ctrl else read_varint()
            out.extend(packed[i:i + length])
            i += length
            continue
        extra = ctrl & 0x3F
        if extra == SHORT_MATCH_LIMIT:
            extra = read_varint()
        length = extra + MIN_MATCH
        if ctrl & 0x40:
            offset = rep
        else:
            offset = read_varint()
            rep = offset
        start = len(out) - offset
        for j in range(length):
            out.append(out[start + j])
    return bytes(out)


def collect(metal_dir):
    """Gather (symbol, source, pre_minified) in a stable order."""
    shaders = []
    seen = set()
    for name in RAW_LITERAL_FILES:
        path = os.path.join(metal_dir, name)
        if not os.path.exists(path):
            continue
        with open(path, "r", encoding="utf-8") as handle:
            text = handle.read()
        for match in RAW_LITERAL_RE.finditer(text):
            symbol = match.group(1)
            if symbol in seen:
                raise SystemExit("duplicate shader symbol: " + symbol)
            seen.add(symbol)
            shaders.append((symbol, match.group(2), False))

    allshader = os.path.join(metal_dir, ALLSHADER_FILE)
    if os.path.exists(allshader):
        with open(allshader, "r", encoding="utf-8") as handle:
            text = handle.read()
        for match in ALLSHADER_RE.finditer(text):
            symbol = match.group(1)
            if symbol in seen:
                raise SystemExit("duplicate shader symbol: " + symbol)
            seen.add(symbol)
            pieces = re.findall(r'"((?:[^"\\]|\\.)*)"', match.group(2))
            # makeshader.py already stripped comments and renamed identifiers,
            # so this text must be packed verbatim.
            shaders.append((symbol, unescape_c("".join(pieces)), True))
    return shaders


def c_array(data, indent="    "):
    lines = []
    for start in range(0, len(data), 20):
        chunk = data[start:start + 20]
        lines.append(indent + "".join("%d," % byte for byte in chunk))
    return "\n".join(lines)


def main():
    if len(sys.argv) != 4:
        raise SystemExit("usage: packshader.py <metal-dir> <out.cpp> <out.hpp>")
    metal_dir, out_cpp, out_hpp = sys.argv[1:4]

    shaders = collect(metal_dir)
    if not shaders:
        raise SystemExit("no shader definitions found under " + metal_dir)

    raw_total = 0
    packed_total = 0
    cpp = [
        "// Generated by source/backend/metal/packshader.py. Do not edit.",
        '#include "MetalShaderCodec.hpp"',
        "",
        "namespace MNN {",
        "",
    ]
    hpp = [
        "// Generated by source/backend/metal/packshader.py. Do not edit.",
        "#ifndef MNN_METAL_PACKED_SHADER_H",
        "#define MNN_METAL_PACKED_SHADER_H",
        '#include "MetalShaderCodec.hpp"',
        "",
        "namespace MNN {",
    ]
    for symbol, source, pre_minified in shaders:
        body = (source if pre_minified else minify(source)).encode("utf-8")
        packed = encode(body)
        if decode(packed, len(body)) != body:
            raise SystemExit("round-trip check failed for " + symbol)
        raw_total += len(source.encode("utf-8"))
        packed_total += len(packed)
        cpp.append("static const unsigned char gPacked_%s[] = {" % symbol)
        cpp.append(c_array(packed))
        cpp.append("};")
        cpp.append(
            "extern const MetalShaderBlob gBlob_%s;" % symbol
        )
        cpp.append(
            "const MetalShaderBlob gBlob_%s = {gPacked_%s, %du, %du};"
            % (symbol, symbol, len(packed), len(body))
        )
        cpp.append("")
        hpp.append("extern const MetalShaderBlob gBlob_%s;" % symbol)

    hpp.append("} // namespace MNN")
    hpp.append("")
    # Each shader symbol becomes an expression that decodes on first use, so
    # existing call sites keep working untouched.
    for symbol, _, _ in shaders:
        hpp.append(
            "#define %s (::MNN::MetalShaderGet(::MNN::gBlob_%s))" % (symbol, symbol)
        )
    hpp.append("")
    hpp.append("#endif")
    hpp.append("")
    cpp.append("} // namespace MNN")
    cpp.append("")

    for path, lines in ((out_cpp, cpp), (out_hpp, hpp)):
        directory = os.path.dirname(path)
        if directory:
            os.makedirs(directory, exist_ok=True)
        content = "\n".join(lines)
        # Avoid touching mtime when nothing changed, so incremental builds do
        # not rebuild the whole Metal backend.
        if os.path.exists(path):
            with open(path, "r", encoding="utf-8") as handle:
                if handle.read() == content:
                    continue
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(content)

    sys.stderr.write(
        "packshader: %d shaders, %d raw bytes -> %d packed bytes (%.1f%%)\n"
        % (len(shaders), raw_total, packed_total, 100.0 * packed_total / raw_total)
    )


if __name__ == "__main__":
    main()
