#ifndef VK_GLSL_SHADER_AUTO_GENERATE_H
#define VK_GLSL_SHADER_AUTO_GENERATE_H
extern const unsigned char glsl_nhwcToimage_comp[];
extern unsigned int glsl_nhwcToimage_comp_len;
extern const unsigned char glsl_lstm_comp[];
extern unsigned int glsl_lstm_comp_len;
extern const unsigned char glsl_deconvCol2Im_comp[];
extern unsigned int glsl_deconvCol2Im_comp_len;
extern const unsigned char glsl_lrnAcrossChannel_comp[];
extern unsigned int glsl_lrnAcrossChannel_comp_len;
extern const unsigned char glsl_softmaxHeight_comp[];
extern unsigned int glsl_softmaxHeight_comp_len;
extern const unsigned char glsl_normalizeChannel_comp[];
extern unsigned int glsl_normalizeChannel_comp_len;
extern const unsigned char glsl_convolutionDepthwiseMali_comp[];
extern unsigned int glsl_convolutionDepthwiseMali_comp_len;
extern const unsigned char glsl_convolutionDepthwiseMali_RELU_comp[];
extern unsigned int glsl_convolutionDepthwiseMali_RELU_comp_len;
extern const unsigned char glsl_convolutionDepthwiseMali_RELU6_comp[];
extern unsigned int glsl_convolutionDepthwiseMali_RELU6_comp_len;
extern const unsigned char glsl_relu_comp[];
extern unsigned int glsl_relu_comp_len;
extern const unsigned char glsl_relu_IMAGE_comp[];
extern unsigned int glsl_relu_IMAGE_comp_len;
extern const unsigned char glsl_unaryImage_comp[];
extern unsigned int glsl_unaryImage_comp_len;
extern const unsigned char glsl_unaryImage_SIGMOID_comp[];
extern unsigned int glsl_unaryImage_SIGMOID_comp_len;
extern const unsigned char glsl_unaryImage_TANH_comp[];
extern unsigned int glsl_unaryImage_TANH_comp_len;
extern const unsigned char glsl_unaryImage_ABS_comp[];
extern unsigned int glsl_unaryImage_ABS_comp_len;
extern const unsigned char glsl_unaryImage_SQRT_comp[];
extern unsigned int glsl_unaryImage_SQRT_comp_len;
extern const unsigned char glsl_unaryImage_RSQRT_comp[];
extern unsigned int glsl_unaryImage_RSQRT_comp_len;
extern const unsigned char glsl_unaryImage_NEG_comp[];
extern unsigned int glsl_unaryImage_NEG_comp_len;
extern const unsigned char glsl_unaryImage_SQUARE_comp[];
extern unsigned int glsl_unaryImage_SQUARE_comp_len;
extern const unsigned char glsl_unaryImage_EXP_comp[];
extern unsigned int glsl_unaryImage_EXP_comp_len;
extern const unsigned char glsl_unaryImage_SIGN_comp[];
extern unsigned int glsl_unaryImage_SIGN_comp_len;
extern const unsigned char glsl_unaryImage_LOG_comp[];
extern unsigned int glsl_unaryImage_LOG_comp_len;
extern const unsigned char glsl_im2col_comp[];
extern unsigned int glsl_im2col_comp_len;
extern const unsigned char glsl_convolutionDepthwise_comp[];
extern unsigned int glsl_convolutionDepthwise_comp_len;
extern const unsigned char glsl_convolutionDepthwise_RELU_comp[];
extern unsigned int glsl_convolutionDepthwise_RELU_comp_len;
extern const unsigned char glsl_convolutionDepthwise_RELU6_comp[];
extern unsigned int glsl_convolutionDepthwise_RELU6_comp_len;
extern const unsigned char glsl_permute_comp[];
extern unsigned int glsl_permute_comp_len;
extern const unsigned char glsl_imageTonhwc_comp[];
extern unsigned int glsl_imageTonhwc_comp_len;
extern const unsigned char glsl_BatchToSpaceND_comp[];
extern unsigned int glsl_BatchToSpaceND_comp_len;
extern const unsigned char glsl_relu6_comp[];
extern unsigned int glsl_relu6_comp_len;
extern const unsigned char glsl_relu6_IMAGE_comp[];
extern unsigned int glsl_relu6_IMAGE_comp_len;
extern const unsigned char glsl_convolution_comp[];
extern unsigned int glsl_convolution_comp_len;
extern const unsigned char glsl_convolution_RELU_comp[];
extern unsigned int glsl_convolution_RELU_comp_len;
extern const unsigned char glsl_convolution_RELU6_comp[];
extern unsigned int glsl_convolution_RELU6_comp_len;
extern const unsigned char glsl_concatBuffer_comp[];
extern unsigned int glsl_concatBuffer_comp_len;
extern const unsigned char glsl_binaryImage_comp[];
extern unsigned int glsl_binaryImage_comp_len;
extern const unsigned char glsl_binaryImage_ADD_comp[];
extern unsigned int glsl_binaryImage_ADD_comp_len;
extern const unsigned char glsl_binaryImage_SUB_comp[];
extern unsigned int glsl_binaryImage_SUB_comp_len;
extern const unsigned char glsl_binaryImage_MUL_comp[];
extern unsigned int glsl_binaryImage_MUL_comp_len;
extern const unsigned char glsl_binaryImage_DIV_comp[];
extern unsigned int glsl_binaryImage_DIV_comp_len;
extern const unsigned char glsl_binaryImage_VMAX_comp[];
extern unsigned int glsl_binaryImage_VMAX_comp_len;
extern const unsigned char glsl_binaryImage_VMIN_comp[];
extern unsigned int glsl_binaryImage_VMIN_comp_len;
extern const unsigned char glsl_nchwToimage_comp[];
extern unsigned int glsl_nchwToimage_comp_len;
extern const unsigned char glsl_packAsImage4x4_comp[];
extern unsigned int glsl_packAsImage4x4_comp_len;
extern const unsigned char glsl_packAsImage4x4_TRANSPOSE_comp[];
extern unsigned int glsl_packAsImage4x4_TRANSPOSE_comp_len;
extern const unsigned char glsl_roipooling_comp[];
extern unsigned int glsl_roipooling_comp_len;
extern const unsigned char glsl_softmax_comp[];
extern unsigned int glsl_softmax_comp_len;
extern const unsigned char glsl_lstmSave_comp[];
extern unsigned int glsl_lstmSave_comp_len;
extern const unsigned char glsl_imageTonchw_comp[];
extern unsigned int glsl_imageTonchw_comp_len;
extern const unsigned char glsl_softmaxHeight_NHWC_comp[];
extern unsigned int glsl_softmaxHeight_NHWC_comp_len;
extern const unsigned char glsl_resizeNearest_comp[];
extern unsigned int glsl_resizeNearest_comp_len;
extern const unsigned char glsl_reduce_comp[];
extern unsigned int glsl_reduce_comp_len;
extern const unsigned char glsl_reduce_VMAX_comp[];
extern unsigned int glsl_reduce_VMAX_comp_len;
extern const unsigned char glsl_reduce_VMIN_comp[];
extern unsigned int glsl_reduce_VMIN_comp_len;
extern const unsigned char glsl_reduce_MEAN_comp[];
extern unsigned int glsl_reduce_MEAN_comp_len;
extern const unsigned char glsl_reduce_PROD_comp[];
extern unsigned int glsl_reduce_PROD_comp_len;
extern const unsigned char glsl_reduce_SUM_comp[];
extern unsigned int glsl_reduce_SUM_comp_len;
extern const unsigned char glsl_unaryBuffer_comp[];
extern unsigned int glsl_unaryBuffer_comp_len;
extern const unsigned char glsl_unaryBuffer_SIGMOID_comp[];
extern unsigned int glsl_unaryBuffer_SIGMOID_comp_len;
extern const unsigned char glsl_unaryBuffer_TANH_comp[];
extern unsigned int glsl_unaryBuffer_TANH_comp_len;
extern const unsigned char glsl_unaryBuffer_ABS_comp[];
extern unsigned int glsl_unaryBuffer_ABS_comp_len;
extern const unsigned char glsl_unaryBuffer_SQRT_comp[];
extern unsigned int glsl_unaryBuffer_SQRT_comp_len;
extern const unsigned char glsl_unaryBuffer_RSQRT_comp[];
extern unsigned int glsl_unaryBuffer_RSQRT_comp_len;
extern const unsigned char glsl_unaryBuffer_NEG_comp[];
extern unsigned int glsl_unaryBuffer_NEG_comp_len;
extern const unsigned char glsl_unaryBuffer_SQUARE_comp[];
extern unsigned int glsl_unaryBuffer_SQUARE_comp_len;
extern const unsigned char glsl_unaryBuffer_EXP_comp[];
extern unsigned int glsl_unaryBuffer_EXP_comp_len;
extern const unsigned char glsl_unaryBuffer_SIGN_comp[];
extern unsigned int glsl_unaryBuffer_SIGN_comp_len;
extern const unsigned char glsl_unaryBuffer_LOG_comp[];
extern unsigned int glsl_unaryBuffer_LOG_comp_len;
extern const unsigned char glsl_resizeBilinear_comp[];
extern unsigned int glsl_resizeBilinear_comp_len;
extern const unsigned char glsl_nchwTonc4hw4_comp[];
extern unsigned int glsl_nchwTonc4hw4_comp_len;
extern const unsigned char glsl_nc4hw4Tonchw_comp[];
extern unsigned int glsl_nc4hw4Tonchw_comp_len;
extern const unsigned char glsl_buffer2Image2D_comp[];
extern unsigned int glsl_buffer2Image2D_comp_len;
extern const unsigned char glsl_lstmGate_comp[];
extern unsigned int glsl_lstmGate_comp_len;
extern const unsigned char glsl_SpatialProduct_comp[];
extern unsigned int glsl_SpatialProduct_comp_len;
extern const unsigned char glsl_im2col1x1_comp[];
extern unsigned int glsl_im2col1x1_comp_len;
extern const unsigned char glsl_binaryBroadcast_comp[];
extern unsigned int glsl_binaryBroadcast_comp_len;
extern const unsigned char glsl_binaryBroadcast_ADD_comp[];
extern unsigned int glsl_binaryBroadcast_ADD_comp_len;
extern const unsigned char glsl_binaryBroadcast_SUB_comp[];
extern unsigned int glsl_binaryBroadcast_SUB_comp_len;
extern const unsigned char glsl_binaryBroadcast_MUL_comp[];
extern unsigned int glsl_binaryBroadcast_MUL_comp_len;
extern const unsigned char glsl_binaryBroadcast_DIV_comp[];
extern unsigned int glsl_binaryBroadcast_DIV_comp_len;
extern const unsigned char glsl_binaryBroadcast_VMAX_comp[];
extern unsigned int glsl_binaryBroadcast_VMAX_comp_len;
extern const unsigned char glsl_binaryBroadcast_VMIN_comp[];
extern unsigned int glsl_binaryBroadcast_VMIN_comp_len;
extern const unsigned char glsl_avgpool_comp[];
extern unsigned int glsl_avgpool_comp_len;
extern const unsigned char glsl_unPackImage4x4_comp[];
extern unsigned int glsl_unPackImage4x4_comp_len;
extern const unsigned char glsl_unPackImage4x4_TRANSPOSE_comp[];
extern unsigned int glsl_unPackImage4x4_TRANSPOSE_comp_len;
extern const unsigned char glsl_SpaceToBatchND_comp[];
extern unsigned int glsl_SpaceToBatchND_comp_len;
extern const unsigned char glsl_maxpool_comp[];
extern unsigned int glsl_maxpool_comp_len;
extern const unsigned char glsl_winogradTransformDest2_3_1_comp[];
extern unsigned int glsl_winogradTransformDest2_3_1_comp_len;
extern const unsigned char glsl_winogradTransformDest2_3_1_RELU_comp[];
extern unsigned int glsl_winogradTransformDest2_3_1_RELU_comp_len;
extern const unsigned char glsl_winogradTransformDest2_3_1_RELU6_comp[];
extern unsigned int glsl_winogradTransformDest2_3_1_RELU6_comp_len;
extern const unsigned char glsl_winogradTransformSource2_3_1_comp[];
extern unsigned int glsl_winogradTransformSource2_3_1_comp_len;
extern const unsigned char glsl_blitC4_comp[];
extern unsigned int glsl_blitC4_comp_len;
extern const unsigned char glsl_col2Im_comp[];
extern unsigned int glsl_col2Im_comp_len;
extern const unsigned char glsl_col2Im_RELU_comp[];
extern unsigned int glsl_col2Im_RELU_comp_len;
extern const unsigned char glsl_col2Im_RELU6_comp[];
extern unsigned int glsl_col2Im_RELU6_comp_len;
extern const unsigned char glsl_nc4hw4toimage_comp[];
extern unsigned int glsl_nc4hw4toimage_comp_len;
extern const unsigned char glsl_imageTonc4hw4_comp[];
extern unsigned int glsl_imageTonc4hw4_comp_len;
extern const unsigned char glsl_gemm16x16_comp[];
extern unsigned int glsl_gemm16x16_comp_len;
extern const unsigned char glsl_gemm16x16_FP16_comp[];
extern unsigned int glsl_gemm16x16_FP16_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_comp[];
extern unsigned int glsl_deconvolutionDepthwise_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_RELU_comp[];
extern unsigned int glsl_deconvolutionDepthwise_RELU_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_RELU6_comp[];
extern unsigned int glsl_deconvolutionDepthwise_RELU6_comp_len;
extern const unsigned char glsl_preluWithChannel_comp[];
extern unsigned int glsl_preluWithChannel_comp_len;
extern const unsigned char glsl_deconvIm2Col_comp[];
extern unsigned int glsl_deconvIm2Col_comp_len;
extern const unsigned char glsl_deconvIm2Col_RELU_comp[];
extern unsigned int glsl_deconvIm2Col_RELU_comp_len;
extern const unsigned char glsl_deconvIm2Col_RELU6_comp[];
extern unsigned int glsl_deconvIm2Col_RELU6_comp_len;
extern const unsigned char glsl_buffer2Image1D_comp[];
extern unsigned int glsl_buffer2Image1D_comp_len;
extern const unsigned char glsl_scale_comp[];
extern unsigned int glsl_scale_comp_len;
extern const unsigned char glsl_buffer2Image3D_comp[];
extern unsigned int glsl_buffer2Image3D_comp_len;
extern const unsigned char glsl_softmaxWidth_comp[];
extern unsigned int glsl_softmaxWidth_comp_len;
extern const unsigned char glsl_softmaxChannel_comp[];
extern unsigned int glsl_softmaxChannel_comp_len;
#endif