#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* attention_kv_rearrange_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "#define GLOBAL_SIZE_3_DIMS "
    " __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
    "#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "
    " return; "
    " }\n"
    "#define GLOBAL_SIZE_2_DIMS "
    " __private const int global_size_dim0,__private const int global_size_dim1,\n"
    "#define DEAL_NON_UNIFORM_DIM2(input1, input2) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1) { "
    " return; "
    " }\n"
    "#define DEAL_OUTER_SEQLEN_NOT_ALIGN(length) "
    " if(4 * sl + 3 >= length) {"
    " temp_3 = (FLOAT4)0;"
    " }"
    " if(4 * sl + 2 >= length) {"
    " temp_2 = (FLOAT4)0;"
    " }"
    " if(4 * sl + 1 >= length) {"
    " temp_1 = (FLOAT4)0;"
    " }\n"
    "#define DEAL_INNER_HEADDIM_NOT_ALIGN(length) "
    " if(hd * 4 + 3 >= length) {"
    " temp_0.w = (FLOAT)0;"
    " temp_1.w = (FLOAT)0;"
    " temp_2.w = (FLOAT)0;"
    " temp_3.w = (FLOAT)0;"
    " }"
    " if(hd * 4 + 2 >= length) {"
    " temp_0.z = (FLOAT)0;"
    " temp_1.z = (FLOAT)0;"
    " temp_2.z = (FLOAT)0;"
    " temp_3.z = (FLOAT)0;"
    " }"
    " if(hd * 4 + 1 >= length) {"
    " temp_0.y = (FLOAT)0;"
    " temp_1.y = (FLOAT)0;"
    " temp_2.y = (FLOAT)0;"
    " temp_3.y = (FLOAT)0;"
    " }\n"
    "#ifdef VALUE_C4\n"
    "static inline FLOAT load_c4_value(__global const FLOAT* value,\n"
    " const int seq_storage,\n"
    " const int token,\n"
    " const int channel) {\n"
    " return value[((channel >> 2)*seq_storage+token)*4+(channel & 3)];\n"
    "}\n"
    "static inline FLOAT4 load_c4_value4(__global const FLOAT* value,\n"
    " const int seq_storage,\n"
    " const int token,\n"
    " const int channel,\n"
    " const int head_dim_offset,\n"
    " const int head_dim) {\n"
    " return (FLOAT4)(\n"
    " load_c4_value(value,seq_storage,token,channel),\n"
    " (head_dim_offset+1 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+1),\n"
    " (head_dim_offset+2 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+2),\n"
    " (head_dim_offset+3 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+3));\n"
    "}\n"
    "#endif\n"
    "#ifdef ATTENTION_C4\n"
    "static inline void store_attention_c4_4(__global FLOAT* output,const FLOAT4 value,const int seq_storage,\n"
    " const int token,const int channel,const int count) {\n"
    " if (((channel & 3) == 0) && count == 4) {\n"
    " const int offset=((channel >> 2)*seq_storage+token)*4;\n"
    " vstore4(value,0,output+offset);\n"
    " return;\n"
    " }\n"
    " int c=channel;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.x;\n"
    " if (count>1) {\n"
    " c=channel+1;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " c=channel+2;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.z;\n"
    " }\n"
    " if (count>3) {\n"
    " c=channel+3;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.w;\n"
    " }\n"
    "}\n"
    "static inline void store_attention_c4_8(__global FLOAT* output,const FLOAT8 value,const int seq_storage,\n"
    " const int token,const int channel,const int count) {\n"
    " const int low_count=min(count,4);\n"
    " store_attention_c4_4(output,value.lo,seq_storage,token,channel,low_count);\n"
    " if (count>4) {\n"
    " store_attention_c4_4(output,value.hi,seq_storage,token,channel+4,count-4);\n"
    " }\n"
    "}\n"
    "#endif\n"
    "// Store the first `count` (<=4) components of a FLOAT4 to contiguous addresses without vector subscript.\n"
    "static inline void store_scalar4(__global FLOAT* output,const int base,const FLOAT4 value,const int count) {\n"
    " output[base]=value.x;\n"
    " if (count>1) {\n"
    " output[base+1]=value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " output[base+2]=value.z;\n"
    " }\n"
    " if (count>3) {\n"
    " output[base+3]=value.w;\n"
    " }\n"
    "}\n"
    "// Store the first `count` (<=8) components of a FLOAT8 to contiguous addresses without vector subscript.\n"
    "static inline void store_scalar8(__global FLOAT* output,const int base,const FLOAT8 value,const int count) {\n"
    " output[base]=value.s0;\n"
    " if (count>1) {\n"
    " output[base+1]=value.s1;\n"
    " }\n"
    " if (count>2) {\n"
    " output[base+2]=value.s2;\n"
    " }\n"
    " if (count>3) {\n"
    " output[base+3]=value.s3;\n"
    " }\n"
    " if (count>4) {\n"
    " output[base+4]=value.s4;\n"
    " }\n"
    " if (count>5) {\n"
    " output[base+5]=value.s5;\n"
    " }\n"
    " if (count>6) {\n"
    " output[base+6]=value.s6;\n"
    " }\n"
    " if (count>7) {\n"
    " output[base+7]=value.s7;\n"
    " }\n"
    "}\n"
    "// Load the first `count` (1..4) components from contiguous addresses,zeroing the rest. Used on\n"
    "// the dim axis of the kv rearrange kernels,where head_dim is a runtime argument rather than a\n"
    "// macro,so the tail cannot be handled with #if the way the fused kernels do it.\n"
    "static inline FLOAT4 load_scalar4(__global const FLOAT* input,const int count) {\n"
    " FLOAT4 value=(FLOAT4)0;\n"
    " value.x=input[0];\n"
    " if (count>1) {\n"
    " value.y=input[1];\n"
    " }\n"
    " if (count>2) {\n"
    " value.z=input[2];\n"
    " }\n"
    " if (count>3) {\n"
    " value.w=input[3];\n"
    " }\n"
    " return value;\n"
    "}\n"
    "// The dim axis of the plain-buffer q/k/v inputs carries no padding and heads sit back to back,so a\n"
    "// vload4 on a partial tail group reads into the next head,and past the end of the buffer on the last\n"
    "// one. Only the tail group takes the scalar path,so the aligned groups keep their vector load. The\n"
    "// NC4HW4 value path already clamps this way inside load_c4_value4.\n"
    "static inline FLOAT4 load_dim4(__global const FLOAT* input,const int count) {\n"
    " return (count >= 4) ? vload4(0,input) : load_scalar4(input,count);\n"
    "}\n"
    "#ifndef NUMHEAD_GROUP_SIZE\n"
    "#define NUMHEAD_GROUP_SIZE 1\n"
    "#endif\n"
    "__kernel void rearrange_k(GLOBAL_SIZE_3_DIMS\n"
    " __global const FLOAT *key,// [batch key_seq_len kv_head_num head_dim]\n"
    " __global FLOAT *past_key,// [batch kv_head_num head_dim max_length]\n"
    " __private const int past_len,// 0 unless this is a chunked prefill\n"
    " __private const int max_len,\n"
    " __private const int seq_len,\n"
    " __private const int kv_head_num,\n"
    " __private const int head_num,\n"
    " __private const int head_dim) {\n"
    " \n"
    " const int x=get_global_id(0); // seq_len decode=1\n"
    " const int y=get_global_id(1); // head_dim\n"
    " int z=get_global_id(2); //\n"
    " DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
    " \n"
    " const int b=z/kv_head_num;\n"
    " z=z % kv_head_num;\n"
    " const int y4=y << 2;\n"
    " \n"
    " // The dim axis is walked four at a time,but head_dim need not be a multiple of four. Each of\n"
    " // the four components below belongs to a different dim,and past_key strides dims by max_len,\n"
    " // so an unguarded tail both reads into the next head and writes whole rows that do not exist.\n"
    " const int dims=min(4,head_dim-y4);\n"
    " const int x4=x << 2;\n"
    " const int stride=kv_head_num*head_dim;\n"
    " int key_offset=((b*seq_len+x4)*kv_head_num+z)*head_dim+y4;\n"
    " FLOAT4 key_vec0,key_vec1,key_vec2,key_vec3;\n"
    " if (4 == dims) {\n"
    " key_vec0=vload4(0,key+key_offset); key_offset += stride;\n"
    " key_vec1=(x4+1 >= seq_len) ? (FLOAT4)0 : vload4(0,key+key_offset); key_offset += stride;\n"
    " key_vec2=(x4+2 >= seq_len) ? (FLOAT4)0 : vload4(0,key+key_offset); key_offset += stride;\n"
    " key_vec3=(x4+3 >= seq_len) ? (FLOAT4)0 : vload4(0,key+key_offset);\n"
    " } else {\n"
    " key_vec0=load_scalar4(key+key_offset,dims); key_offset += stride;\n"
    " key_vec1=(x4+1 >= seq_len) ? (FLOAT4)0 : load_scalar4(key+key_offset,dims); key_offset += stride;\n"
    " key_vec2=(x4+2 >= seq_len) ? (FLOAT4)0 : load_scalar4(key+key_offset,dims); key_offset += stride;\n"
    " key_vec3=(x4+3 >= seq_len) ? (FLOAT4)0 : load_scalar4(key+key_offset,dims);\n"
    " }\n"
    " const int output_offset=((b*kv_head_num+z)*head_dim+y4)*max_len+past_len+x4;\n"
    " vstore4((FLOAT4)(key_vec0.s0,key_vec1.s0,key_vec2.s0,key_vec3.s0),0,past_key+output_offset);\n"
    " if (dims>1) {\n"
    " vstore4((FLOAT4)(key_vec0.s1,key_vec1.s1,key_vec2.s1,key_vec3.s1),0,past_key+output_offset+max_len);\n"
    " }\n"
    " if (dims>2) {\n"
    " vstore4((FLOAT4)(key_vec0.s2,key_vec1.s2,key_vec2.s2,key_vec3.s2),0,\n"
    " past_key+output_offset+max_len+max_len);\n"
    " }\n"
    " if (dims>3) {\n"
    " vstore4((FLOAT4)(key_vec0.s3,key_vec1.s3,key_vec2.s3,key_vec3.s3),0,\n"
    " past_key+output_offset+max_len+max_len+max_len);\n"
    " }\n"
    "}\n"
    "__kernel void rearrange_v(GLOBAL_SIZE_3_DIMS\n"
    " __global const FLOAT *value,// [batch value_seq_len kv_head_num head_dim]\n"
    " __global FLOAT *past_value,// [batch kv_head_num max_length head_dim]\n"
    " __private const int past_len,\n"
    " __private const int max_len,\n"
    " __private const int seq_len,\n"
    " __private const int kv_head_num,\n"
    " __private const int head_dim) {\n"
    " \n"
    " const int x=get_global_id(0); // head_dim\n"
    " const int y=get_global_id(1); // seq_len\n"
    " int z=get_global_id(2); // kv_head_num\n"
    " DEAL_NON_UNIFORM_DIM3(x,y,z);\n"
    " const int b=z/kv_head_num;\n"
    " z=z % kv_head_num;\n"
    " const int x4=x << 2;\n"
    " // head_dim need not be a multiple of four; the trailing group is short.\n"
    " const int dims=min(4,head_dim-x4);\n"
    " const int y4=y << 2;\n"
    " const int stride=kv_head_num*head_dim;\n"
    " #ifdef VALUE_C4\n"
    " const int value_seq_storage=(global_size_dim2/kv_head_num)*seq_len;\n"
    " const int value_channel=z*head_dim+x4;\n"
    " const int value_token=b*seq_len+y4;\n"
    " FLOAT4 value_vec0=load_c4_value4(value,value_seq_storage,value_token,value_channel,x4,head_dim);\n"
    " FLOAT4 value_vec1=(y4+1 >= seq_len) ? (FLOAT4)0 :\n"
    " load_c4_value4(value,value_seq_storage,value_token+1,value_channel,x4,head_dim);\n"
    " FLOAT4 value_vec2=(y4+2 >= seq_len) ? (FLOAT4)0 :\n"
    " load_c4_value4(value,value_seq_storage,value_token+2,value_channel,x4,head_dim);\n"
    " FLOAT4 value_vec3=(y4+3 >= seq_len) ? (FLOAT4)0 :\n"
    " load_c4_value4(value,value_seq_storage,value_token+3,value_channel,x4,head_dim);\n"
    " #else\n"
    " int value_offset=((b*seq_len+y4)*kv_head_num+z)*head_dim+x4;\n"
    " FLOAT4 value_vec0,value_vec1,value_vec2,value_vec3;\n"
    " if (4 == dims) {\n"
    " value_vec0=vload4(0,value+value_offset); value_offset += stride;\n"
    " value_vec1=(y4+1 >= seq_len) ? (FLOAT4)0 : vload4(0,value+value_offset); value_offset += stride;\n"
    " value_vec2=(y4+2 >= seq_len) ? (FLOAT4)0 : vload4(0,value+value_offset); value_offset += stride;\n"
    " value_vec3=(y4+3 >= seq_len) ? (FLOAT4)0 : vload4(0,value+value_offset);\n"
    " } else {\n"
    " value_vec0=load_scalar4(value+value_offset,dims); value_offset += stride;\n"
    " value_vec1=(y4+1 >= seq_len) ? (FLOAT4)0 : load_scalar4(value+value_offset,dims); value_offset += stride;\n"
    " value_vec2=(y4+2 >= seq_len) ? (FLOAT4)0 : load_scalar4(value+value_offset,dims); value_offset += stride;\n"
    " value_vec3=(y4+3 >= seq_len) ? (FLOAT4)0 : load_scalar4(value+value_offset,dims);\n"
    " }\n"
    " #endif\n"
    " // past_value is [..,maxLen,head_dim],so here the four components are contiguous dims of one\n"
    " // token and the tail spills into the next token's leading dims.\n"
    " const int output_offset=((b*kv_head_num+z)*max_len+past_len+y4)*head_dim+x4;\n"
    " if (4 == dims) {\n"
    " vstore4(value_vec0,0,past_value+output_offset);\n"
    " vstore4(value_vec1,0,past_value+output_offset+head_dim);\n"
    " vstore4(value_vec2,0,past_value+output_offset+head_dim+head_dim);\n"
    " vstore4(value_vec3,0,past_value+output_offset+head_dim+head_dim+head_dim);\n"
    " } else {\n"
    " store_scalar4(past_value,output_offset,value_vec0,dims);\n"
    " store_scalar4(past_value,output_offset+head_dim,value_vec1,dims);\n"
    " store_scalar4(past_value,output_offset+head_dim+head_dim,value_vec2,dims);\n"
    " store_scalar4(past_value,output_offset+head_dim+head_dim+head_dim,value_vec3,dims);\n"
    " }\n"
    "}\n";
#endif
} // namespace MNN
