#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* attention_flash_prefill_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "#define GLOBAL_SIZE_3_DIMS "
    " __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
    "#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "
    " return; "
    " }\n"
    "#define GLOBAL_SIZE_2_DIMS "
    " __private const int global_size_dim0,__private const int global_size_dim1,\n"
    "#define DEAL_NON_UNIFORM_DIM2(input1, input2) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1) { "
    " return; "
    " }\n"
    "#define DEAL_OUTER_SEQLEN_NOT_ALIGN(length) "
    " if(4 * sl + 3 >= length) {"
    " temp_3 = (FLOAT4)0;"
    " }"
    " if(4 * sl + 2 >= length) {"
    " temp_2 = (FLOAT4)0;"
    " }"
    " if(4 * sl + 1 >= length) {"
    " temp_1 = (FLOAT4)0;"
    " }\n"
    "#define DEAL_INNER_HEADDIM_NOT_ALIGN(length) "
    " if(hd * 4 + 3 >= length) {"
    " temp_0.w = (FLOAT)0;"
    " temp_1.w = (FLOAT)0;"
    " temp_2.w = (FLOAT)0;"
    " temp_3.w = (FLOAT)0;"
    " }"
    " if(hd * 4 + 2 >= length) {"
    " temp_0.z = (FLOAT)0;"
    " temp_1.z = (FLOAT)0;"
    " temp_2.z = (FLOAT)0;"
    " temp_3.z = (FLOAT)0;"
    " }"
    " if(hd * 4 + 1 >= length) {"
    " temp_0.y = (FLOAT)0;"
    " temp_1.y = (FLOAT)0;"
    " temp_2.y = (FLOAT)0;"
    " temp_3.y = (FLOAT)0;"
    " }\n"
    "#ifdef VALUE_C4\n"
    "static inline FLOAT load_c4_value(__global const FLOAT* value,\n"
    " const int seq_storage,\n"
    " const int token,\n"
    " const int channel) {\n"
    " return value[((channel >> 2)*seq_storage+token)*4+(channel & 3)];\n"
    "}\n"
    "static inline FLOAT4 load_c4_value4(__global const FLOAT* value,\n"
    " const int seq_storage,\n"
    " const int token,\n"
    " const int channel,\n"
    " const int head_dim_offset,\n"
    " const int head_dim) {\n"
    " return (FLOAT4)(\n"
    " load_c4_value(value,seq_storage,token,channel),\n"
    " (head_dim_offset+1 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+1),\n"
    " (head_dim_offset+2 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+2),\n"
    " (head_dim_offset+3 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+3));\n"
    "}\n"
    "#endif\n"
    "#ifdef ATTENTION_C4\n"
    "static inline void store_attention_c4_4(__global FLOAT* output,const FLOAT4 value,const int seq_storage,\n"
    " const int token,const int channel,const int count) {\n"
    " if (((channel & 3) == 0) && count == 4) {\n"
    " const int offset=((channel >> 2)*seq_storage+token)*4;\n"
    " vstore4(value,0,output+offset);\n"
    " return;\n"
    " }\n"
    " int c=channel;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.x;\n"
    " if (count>1) {\n"
    " c=channel+1;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " c=channel+2;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.z;\n"
    " }\n"
    " if (count>3) {\n"
    " c=channel+3;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.w;\n"
    " }\n"
    "}\n"
    "static inline void store_attention_c4_8(__global FLOAT* output,const FLOAT8 value,const int seq_storage,\n"
    " const int token,const int channel,const int count) {\n"
    " const int low_count=min(count,4);\n"
    " store_attention_c4_4(output,value.lo,seq_storage,token,channel,low_count);\n"
    " if (count>4) {\n"
    " store_attention_c4_4(output,value.hi,seq_storage,token,channel+4,count-4);\n"
    " }\n"
    "}\n"
    "#endif\n"
    "// Store the first `count` (<=4) components of a FLOAT4 to contiguous addresses without vector subscript.\n"
    "static inline void store_scalar4(__global FLOAT* output,const int base,const FLOAT4 value,const int count) {\n"
    " output[base]=value.x;\n"
    " if (count>1) {\n"
    " output[base+1]=value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " output[base+2]=value.z;\n"
    " }\n"
    " if (count>3) {\n"
    " output[base+3]=value.w;\n"
    " }\n"
    "}\n"
    "// Store the first `count` (<=8) components of a FLOAT8 to contiguous addresses without vector subscript.\n"
    "static inline void store_scalar8(__global FLOAT* output,const int base,const FLOAT8 value,const int count) {\n"
    " output[base]=value.s0;\n"
    " if (count>1) {\n"
    " output[base+1]=value.s1;\n"
    " }\n"
    " if (count>2) {\n"
    " output[base+2]=value.s2;\n"
    " }\n"
    " if (count>3) {\n"
    " output[base+3]=value.s3;\n"
    " }\n"
    " if (count>4) {\n"
    " output[base+4]=value.s4;\n"
    " }\n"
    " if (count>5) {\n"
    " output[base+5]=value.s5;\n"
    " }\n"
    " if (count>6) {\n"
    " output[base+6]=value.s6;\n"
    " }\n"
    " if (count>7) {\n"
    " output[base+7]=value.s7;\n"
    " }\n"
    "}\n"
    "// Load the first `count` (1..4) components from contiguous addresses,zeroing the rest. Used on\n"
    "// the dim axis of the kv rearrange kernels,where head_dim is a runtime argument rather than a\n"
    "// macro,so the tail cannot be handled with #if the way the fused kernels do it.\n"
    "static inline FLOAT4 load_scalar4(__global const FLOAT* input,const int count) {\n"
    " FLOAT4 value=(FLOAT4)0;\n"
    " value.x=input[0];\n"
    " if (count>1) {\n"
    " value.y=input[1];\n"
    " }\n"
    " if (count>2) {\n"
    " value.z=input[2];\n"
    " }\n"
    " if (count>3) {\n"
    " value.w=input[3];\n"
    " }\n"
    " return value;\n"
    "}\n"
    "// The dim axis of the plain-buffer q/k/v inputs carries no padding and heads sit back to back,so a\n"
    "// vload4 on a partial tail group reads into the next head,and past the end of the buffer on the last\n"
    "// one. Only the tail group takes the scalar path,so the aligned groups keep their vector load. The\n"
    "// NC4HW4 value path already clamps this way inside load_c4_value4.\n"
    "static inline FLOAT4 load_dim4(__global const FLOAT* input,const int count) {\n"
    " return (count >= 4) ? vload4(0,input) : load_scalar4(input,count);\n"
    "}\n"
    "#ifndef NUMHEAD_GROUP_SIZE\n"
    "#define NUMHEAD_GROUP_SIZE 1\n"
    "#endif\n"
    "// ---------------------------------------------------------------------------\n"
    "// Fused flash attention (prefill): qk+mask+softmax+qkv in one kernel,so the\n"
    "// O(seqLen*kvLen) qk and softmax buffers never have to exist at all.\n"
    "// A workgroup owns FA_TILE_Q query rows of one (batch,head) and walks kv in FA_TILE_KV\n"
    "// chunks,keeping the online-softmax state and the whole O tile alive across the loop.\n"
    "// The tile macros are interdependent; flashPrefillEligible() derives and documents them.\n"
    "#ifndef FA_TILE_Q\n"
    "#define FA_TILE_Q 16\n"
    "#endif\n"
    "#ifndef FA_TILE_KV\n"
    "#define FA_TILE_KV 64\n"
    "#endif\n"
    "#ifndef FA_HEAD_DIM\n"
    "#define FA_HEAD_DIM 128\n"
    "#endif\n"
    "#ifndef FA_WG_SIZE\n"
    "#define FA_WG_SIZE 64\n"
    "#endif\n"
    "// Work-items per query row in the softmax phase,and kv entries each one owns. Both\n"
    "// divisions must be exact; the host picks the triple so that they are.\n"
    "#define FA_TPR (FA_WG_SIZE/FA_TILE_Q)\n"
    "#define FA_KV_PER_THREAD (FA_TILE_KV/FA_TPR)\n"
    "// Dim counts rounded up to the vector widths the phases load with. lq is declared at the\n"
    "// padded width because phase 0 writes four dim rows at a time; the pad rows get zeros and\n"
    "// phase 1 never reads them. Phase 3 owns 8 dims per work-item,so its trailing group is\n"
    "// partial when headDim is not a multiple of 8.\n"
    "#define FA_HEAD_DIM_4 ((((FA_HEAD_DIM)+3) >> 2) << 2)\n"
    "#define FA_DIM_GROUPS (((FA_HEAD_DIM)+7) >> 3)\n"
    "// Phase 3 units,i.e. how many lanes actually carry an O tile. The work group can be larger\n"
    "// (it also has to be a multiple of FA_TILE_Q for phase 2),and when it is not,the surplus\n"
    "// lanes have to sit phase 3 out. Whether that guard exists at all is decided here rather than\n"
    "// at run time: wrapping the phase-3 loop in a run-time branch costs ~0.9% on pp2048 even when\n"
    "// the branch is always taken,because it changes how the O accumulators get allocated.\n"
    "#define FA_P3_UNITS ((FA_TILE_Q >> 2)*FA_DIM_GROUPS)\n"
    "// Storing one output row of the O tile. Only the trailing dim group can be partial,so the\n"
    "// aligned case keeps its single vstore8 and pays nothing for the general one.\n"
    "#if (FA_HEAD_DIM % 8) == 0\n"
    "#define STORE_FA_ROW(out,off,val,n) vstore8(CONVERT_FLOAT8(val),0,(out)+(off))\n"
    "#else\n"
    "#define STORE_FA_ROW(out,off,val,n) store_scalar8((out),(off),CONVERT_FLOAT8(val),(n))\n"
    "#endif\n"
    "// \"Masked out\" sentinel. Must stay exactly representable in half (the score tile is\n"
    "// COMPUTE_FLOAT),so that the FA_NEG_TEST probe is an exact compare in both precisions.\n"
    "#define FA_NEG_INF (-60000.0f)\n"
    "#define FA_NEG_TEST (-50000.0f)\n"
    "__kernel void flash_attention_prefill(\n"
    " __global const FLOAT *query,// [batch,seqLen,headNum,headDim]\n"
    " __global const FLOAT *past_key,// [batch,kvHeadNum,headDim,maxLen]\n"
    " __global const FLOAT *past_value,// [batch,kvHeadNum,maxLen,headDim]\n"
    " #ifdef SET_MASK\n"
    " __global const int* mask,// [maskBatch,maskQLen,maskKvLen]\n"
    " #else\n"
    " __global const FLOAT* mask,\n"
    " #endif\n"
    " __global FLOAT *output,// [batch,seqLen,headNum,headDim]\n"
    " __private const float scale,\n"
    " __private const int seq_len,\n"
    " __private const int kv_seq_len,\n"
    " __private const int mask_kv_len,\n"
    " __private const int max_len,\n"
    " __private const int head_num,\n"
    " __private const int kv_head_num,\n"
    " __private const int batch,\n"
    " // Appended,not inserted: the record path patches args 7 and 9 by index.\n"
    " __private const int mask_q_len,\n"
    " // maskQLen*maskKvLen when the plane is per batch,0 when it is shared.\n"
    " __private const int mask_batch_stride) {\n"
    " const int lid=get_local_id(0);\n"
    " const int q_start=get_group_id(0)*FA_TILE_Q;\n"
    " const int z=get_global_id(1); // batch*headNum\n"
    " const int b=z/head_num;\n"
    " const int hn=z % head_num;\n"
    " const int kv_hn=hn/NUMHEAD_GROUP_SIZE;\n"
    " __local FLOAT lq[FA_HEAD_DIM_4*FA_TILE_Q]; // Q tile,[headDim rounded to 4][FA_TILE_Q]\n"
    " __local COMPUTE_FLOAT ls[FA_TILE_KV*FA_TILE_Q]; // S then P,[FA_TILE_KV][FA_TILE_Q]\n"
    " __local float lred[FA_TILE_Q*FA_TPR]; // per-row partials of max/sum\n"
    " __local float ll[FA_TILE_Q]; // running row sum\n"
    " __local float la[FA_TILE_Q]; // this block's rescale factor\n"
    " // Q stays local for the whole kv loop,transposed to [dim][row] so phase 1 can\n"
    " // grab 4 rows per vload4.\n"
    " const int head_dim_4=FA_HEAD_DIM_4 >> 2;\n"
    " for (int idx=lid; idx<FA_TILE_Q*head_dim_4; idx += FA_WG_SIZE) {\n"
    " const int r=idx/head_dim_4;\n"
    " const int d4=(idx-r*head_dim_4) << 2;\n"
    " const int q=q_start+r;\n"
    " const int q_off=((b*seq_len+q)*head_num+hn)*FA_HEAD_DIM+d4;\n"
    "#if (FA_HEAD_DIM % 4) == 0\n"
    " FLOAT4 qv=(q<seq_len) ? vload4(0,query+q_off) : (FLOAT4)0;\n"
    "#else\n"
    " // Scalar loads for every group,not just the last one: this branch is compiled in for the\n"
    " // whole loop. Only the trailing group is short,and a vload4 there would cross into the\n"
    " // next head; the lanes past the end stay zero,which is what lq's pad rows want anyway.\n"
    " FLOAT4 qv=(FLOAT4)0;\n"
    " if (q<seq_len) {\n"
    " const int dcount=min(4,FA_HEAD_DIM-d4);\n"
    " qv.x=query[q_off];\n"
    " if (dcount>1) {\n"
    " qv.y=query[q_off+1];\n"
    " }\n"
    " if (dcount>2) {\n"
    " qv.z=query[q_off+2];\n"
    " }\n"
    " if (dcount>3) {\n"
    " qv.w=query[q_off+3];\n"
    " }\n"
    " }\n"
    "#endif\n"
    " lq[d4*FA_TILE_Q+r]=qv.x;\n"
    " lq[(d4+1)*FA_TILE_Q+r]=qv.y;\n"
    " lq[(d4+2)*FA_TILE_Q+r]=qv.z;\n"
    " lq[(d4+3)*FA_TILE_Q+r]=qv.w;\n"
    " }\n"
    " for (int r=lid; r<FA_TILE_Q; r += FA_WG_SIZE) {\n"
    " ll[r]=0.0f;\n"
    " }\n"
    " // phase 3 layout: work-item owns rows [r0,r0+4) and dims [d8,d8+8). Surplus lanes get\n"
    " // r0 clamped to 0 rather than left past the end of la/ll.\n"
    "#if FA_WG_SIZE>FA_P3_UNITS\n"
    " const bool p3_active=lid<FA_P3_UNITS;\n"
    " const int r0=p3_active ? ((lid/FA_DIM_GROUPS) << 2) : 0;\n"
    " const int d8=p3_active ? ((lid % FA_DIM_GROUPS) << 3) : 0;\n"
    "#else\n"
    " const bool p3_active=true;\n"
    " const int r0=(lid/FA_DIM_GROUPS) << 2;\n"
    " const int d8=(lid % FA_DIM_GROUPS) << 3;\n"
    "#endif\n"
    "#if (FA_HEAD_DIM % 8) == 0\n"
    " const int p3_dims=8;\n"
    "#else\n"
    " const int p3_dims=min(8,FA_HEAD_DIM-d8);\n"
    "#endif\n"
    " COMPUTE_FLOAT8 out0=0,out1=0,out2=0,out3=0;\n"
    " // phase 1 layout: work-item owns rows [qr0,qr0+4) and kv [kloc,kloc+4).\n"
    " const int num_kv_quad=FA_TILE_KV >> 2;\n"
    " const int p1_units=(FA_TILE_Q >> 2)*num_kv_quad;\n"
    " // phase 2 layout: FA_TPR work-items per row,FA_KV_PER_THREAD kv entries each.\n"
    " const int p2_row=lid % FA_TILE_Q;\n"
    " const int p2_sub=lid/FA_TILE_Q;\n"
    " const int p2_beg=p2_sub*FA_KV_PER_THREAD;\n"
    " // Running row max,kept private: the FA_TPR work-items of a row all reduce the same\n"
    " // lred partials,so they derive an identical m_new and never need to exchange it.\n"
    " float m_prev=FA_NEG_INF;\n"
    " const int key_base=((b*kv_head_num+kv_hn)*FA_HEAD_DIM)*max_len;\n"
    " const int value_base=((b*kv_head_num+kv_hn)*max_len)*FA_HEAD_DIM+d8;\n"
    "#if defined(ADD_MASK) || defined(SET_MASK)\n"
    " const int kv_end=kv_seq_len;\n"
    "#else\n"
    " // Causal mask: every kv past the last query row of this tile is masked out for\n"
    " // all of the tile's rows,so those blocks can be skipped outright.\n"
    " const int kv_end=min(kv_seq_len,kv_seq_len-seq_len+q_start+FA_TILE_Q);\n"
    "#endif\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " for (int k_start=0; k_start<kv_end; k_start += FA_TILE_KV) {\n"
    " // ---- phase 1: S=scale*Q.K^T ----\n"
    " for (int u=lid; u<p1_units; u += FA_WG_SIZE) {\n"
    " const int kloc=(u % num_kv_quad) << 2;\n"
    " const int qr0=(u/num_kv_quad) << 2;\n"
    " // Clamp,don't branch: phase 2 overwrites out-of-range scores anyway.\n"
    " const int kread=min(k_start+kloc,max_len-4);\n"
    " __local const FLOAT* qp=lq+qr0;\n"
    " __global const FLOAT* kp=past_key+key_base+kread;\n"
    " COMPUTE_FLOAT4 acc0=0,acc1=0,acc2=0,acc3=0;\n"
    " for (int d=0; d<FA_HEAD_DIM; ++d) {\n"
    " COMPUTE_FLOAT4 qv=CONVERT_COMPUTE_FLOAT4(vload4(0,qp+d*FA_TILE_Q));\n"
    " COMPUTE_FLOAT4 kv=CONVERT_COMPUTE_FLOAT4(vload4(0,kp+d*max_len));\n"
    " acc0=mad((COMPUTE_FLOAT4)kv.x,qv,acc0);\n"
    " acc1=mad((COMPUTE_FLOAT4)kv.y,qv,acc1);\n"
    " acc2=mad((COMPUTE_FLOAT4)kv.z,qv,acc2);\n"
    " acc3=mad((COMPUTE_FLOAT4)kv.w,qv,acc3);\n"
    " }\n"
    " const COMPUTE_FLOAT scale_c=(COMPUTE_FLOAT)scale;\n"
    " __local COMPUTE_FLOAT* sp=ls+kloc*FA_TILE_Q+qr0;\n"
    " vstore4(acc0*scale_c,0,sp);\n"
    " vstore4(acc1*scale_c,0,sp+FA_TILE_Q);\n"
    " vstore4(acc2*scale_c,0,sp+2*FA_TILE_Q);\n"
    " vstore4(acc3*scale_c,0,sp+3*FA_TILE_Q);\n"
    " }\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " // ---- phase 2: mask+online softmax,FA_TPR work-items per row ----\n"
    " {\n"
    " const int q=q_start+p2_row;\n"
    " const int kv_valid=kv_seq_len-k_start;\n"
    " #if defined(ADD_MASK) || defined(SET_MASK)\n"
    " const int mask_clp=k_start+mask_kv_len-kv_seq_len;\n"
    " const int mask_row=b*mask_batch_stride+q*mask_kv_len;\n"
    " // A plane shorter than the query leaves its trailing rows unmasked,the same way a\n"
    " // plane shorter than the kv axis leaves the history columns unmasked. Hoisted out of\n"
    " // the kv loop: it only depends on the row.\n"
    " const bool mask_on=q<mask_q_len;\n"
    " #else\n"
    " const int kv_valid_offset=kv_seq_len-seq_len;\n"
    " #endif\n"
    " float pmax=FA_NEG_INF;\n"
    " for (int j=0; j<FA_KV_PER_THREAD; ++j) {\n"
    " const int kk=p2_beg+j;\n"
    " float s=(float)ls[kk*FA_TILE_Q+p2_row];\n"
    " if (kk >= kv_valid || q >= seq_len) {\n"
    " s=FA_NEG_INF;\n"
    " } else {\n"
    " #ifdef ADD_MASK\n"
    " const int kc=mask_clp+kk;\n"
    " if (mask_on && kc >= 0 && kc<mask_kv_len) {\n"
    " s += (float)mask[mask_row+kc];\n"
    " }\n"
    " #elif defined(SET_MASK)\n"
    " const int kc=mask_clp+kk;\n"
    " if (mask_on && (!(kc >= 0 && kc<mask_kv_len) || mask[mask_row+kc] == 0)) {\n"
    " s=FA_NEG_INF;\n"
    " }\n"
    " #else\n"
    " if (k_start+kk>kv_valid_offset+q) {\n"
    " s=FA_NEG_INF;\n"
    " }\n"
    " #endif\n"
    " // Normalize -inf/-FLT_MAX/NaN onto the sentinel.\n"
    " s=fmax(s,FA_NEG_INF);\n"
    " }\n"
    " ls[kk*FA_TILE_Q+p2_row]=(COMPUTE_FLOAT)s;\n"
    " pmax=fmax(pmax,s);\n"
    " }\n"
    " lred[p2_sub*FA_TILE_Q+p2_row]=pmax;\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " float m_blk=FA_NEG_INF;\n"
    " for (int t=0; t<FA_TPR; ++t) {\n"
    " m_blk=fmax(m_blk,lred[t*FA_TILE_Q+p2_row]);\n"
    " }\n"
    " const float m_new=fmax(m_prev,m_blk);\n"
    " const float alpha=native_exp(m_prev-m_new);\n"
    " float psum=0.0f;\n"
    " for (int j=0; j<FA_KV_PER_THREAD; ++j) {\n"
    " const int kk=p2_beg+j;\n"
    " const float s=(float)ls[kk*FA_TILE_Q+p2_row];\n"
    " const float p=(s <= FA_NEG_TEST) ? 0.0f : native_exp(s-m_new);\n"
    " ls[kk*FA_TILE_Q+p2_row]=(COMPUTE_FLOAT)p;\n"
    " psum += p;\n"
    " }\n"
    " m_prev=m_new;\n"
    " // All reads of lred are done,so it can be reused now.\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " lred[p2_sub*FA_TILE_Q+p2_row]=psum;\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " if (0 == p2_sub) {\n"
    " float l_blk=0.0f;\n"
    " for (int t=0; t<FA_TPR; ++t) {\n"
    " l_blk += lred[t*FA_TILE_Q+p2_row];\n"
    " }\n"
    " ll[p2_row]=ll[p2_row]*alpha+l_blk;\n"
    " la[p2_row]=alpha;\n"
    " }\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " }\n"
    " // ---- phase 3: O=O*alpha+P.V ----\n"
    " // Guarded,but the barrier below stays outside: it has to be reached by every lane.\n"
    " if (p3_active) {\n"
    " out0 *= (COMPUTE_FLOAT)la[r0];\n"
    " out1 *= (COMPUTE_FLOAT)la[r0+1];\n"
    " out2 *= (COMPUTE_FLOAT)la[r0+2];\n"
    " out3 *= (COMPUTE_FLOAT)la[r0+3];\n"
    " // kv_end,not kv_seq_len: P is zero past it for every row of this tile.\n"
    " const int kv_valid=min(FA_TILE_KV,kv_end-k_start);\n"
    " __global const FLOAT* vp=past_value+value_base+k_start*FA_HEAD_DIM;\n"
    " for (int kk=0; kk<kv_valid; ++kk) {\n"
    " COMPUTE_FLOAT4 p=vload4(0,ls+kk*FA_TILE_Q+r0);\n"
    "#if (FA_HEAD_DIM % 8) == 0\n"
    " COMPUTE_FLOAT8 vv=CONVERT_COMPUTE_FLOAT8(vload8(0,vp+kk*FA_HEAD_DIM));\n"
    "#else\n"
    " // V is [.. ][maxLen][headDim] with no padding on the dim axis,so the trailing\n"
    " // group cannot be read as a whole vload8. Compile-time branch,so this covers\n"
    " // every group and not just the short one -- p3_dims is 8 for all but the last.\n"
    " // The aligned case above keeps its vector load in this hot loop.\n"
    " COMPUTE_FLOAT8 vv=0;\n"
    " {\n"
    " __global const FLOAT* vrow=vp+kk*FA_HEAD_DIM;\n"
    " vv.s0=(COMPUTE_FLOAT)vrow[0];\n"
    " if (p3_dims>1) { vv.s1=(COMPUTE_FLOAT)vrow[1]; }\n"
    " if (p3_dims>2) { vv.s2=(COMPUTE_FLOAT)vrow[2]; }\n"
    " if (p3_dims>3) { vv.s3=(COMPUTE_FLOAT)vrow[3]; }\n"
    " if (p3_dims>4) { vv.s4=(COMPUTE_FLOAT)vrow[4]; }\n"
    " if (p3_dims>5) { vv.s5=(COMPUTE_FLOAT)vrow[5]; }\n"
    " if (p3_dims>6) { vv.s6=(COMPUTE_FLOAT)vrow[6]; }\n"
    " if (p3_dims>7) { vv.s7=(COMPUTE_FLOAT)vrow[7]; }\n"
    " }\n"
    "#endif\n"
    " out0=mad((COMPUTE_FLOAT8)p.x,vv,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)p.y,vv,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)p.z,vv,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)p.w,vv,out3);\n"
    " }\n"
    " }\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " }\n"
    " // ---- normalize and store ----\n"
    " // Past the last barrier,so the surplus lanes can leave here.\n"
    " if (!p3_active) {\n"
    " return;\n"
    " }\n"
    " const float l0=ll[r0],l1=ll[r0+1],l2=ll[r0+2],l3=ll[r0+3];\n"
    " out0 *= (COMPUTE_FLOAT)((l0>0.0f) ? (1.0f/l0) : 0.0f);\n"
    " out1 *= (COMPUTE_FLOAT)((l1>0.0f) ? (1.0f/l1) : 0.0f);\n"
    " out2 *= (COMPUTE_FLOAT)((l2>0.0f) ? (1.0f/l2) : 0.0f);\n"
    " out3 *= (COMPUTE_FLOAT)((l3>0.0f) ? (1.0f/l3) : 0.0f);\n"
    " const int q0=q_start+r0;\n"
    "#ifdef ATTENTION_C4\n"
    " const int channel=hn*FA_HEAD_DIM+d8;\n"
    " const int seq_storage=seq_len*batch;\n"
    " int token=b*seq_len+q0;\n"
    " if (q0 >= seq_len) return;\n"
    " store_attention_c4_8(output,CONVERT_FLOAT8(out0),seq_storage,token,channel,p3_dims);\n"
    " if (q0+1 >= seq_len) return;\n"
    " store_attention_c4_8(output,CONVERT_FLOAT8(out1),seq_storage,++token,channel,p3_dims);\n"
    " if (q0+2 >= seq_len) return;\n"
    " store_attention_c4_8(output,CONVERT_FLOAT8(out2),seq_storage,++token,channel,p3_dims);\n"
    " if (q0+3 >= seq_len) return;\n"
    " store_attention_c4_8(output,CONVERT_FLOAT8(out3),seq_storage,++token,channel,p3_dims);\n"
    "#else\n"
    " const int stride=head_num*FA_HEAD_DIM;\n"
    " const int offset=((b*seq_len+q0)*head_num+hn)*FA_HEAD_DIM+d8;\n"
    " // A whole vstore8 on the trailing dim group would land on the next head's leading dims.\n"
    " if (q0 >= seq_len) return;\n"
    " STORE_FA_ROW(output,offset,out0,p3_dims);\n"
    " if (q0+1 >= seq_len) return;\n"
    " STORE_FA_ROW(output,offset+stride,out1,p3_dims);\n"
    " if (q0+2 >= seq_len) return;\n"
    " STORE_FA_ROW(output,offset+2*stride,out2,p3_dims);\n"
    " if (q0+3 >= seq_len) return;\n"
    " STORE_FA_ROW(output,offset+3*stride,out3,p3_dims);\n"
    "#endif\n"
    "}\n";
#endif
} // namespace MNN
