#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* attention_flash_decode_partial_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "#define GLOBAL_SIZE_3_DIMS "
    " __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
    "#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "
    " return; "
    " }\n"
    "#define GLOBAL_SIZE_2_DIMS "
    " __private const int global_size_dim0,__private const int global_size_dim1,\n"
    "#define DEAL_NON_UNIFORM_DIM2(input1, input2) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1) { "
    " return; "
    " }\n"
    "#define DEAL_OUTER_SEQLEN_NOT_ALIGN(length) "
    " if(4 * sl + 3 >= length) {"
    " temp_3 = (FLOAT4)0;"
    " }"
    " if(4 * sl + 2 >= length) {"
    " temp_2 = (FLOAT4)0;"
    " }"
    " if(4 * sl + 1 >= length) {"
    " temp_1 = (FLOAT4)0;"
    " }\n"
    "#define DEAL_INNER_HEADDIM_NOT_ALIGN(length) "
    " if(hd * 4 + 3 >= length) {"
    " temp_0.w = (FLOAT)0;"
    " temp_1.w = (FLOAT)0;"
    " temp_2.w = (FLOAT)0;"
    " temp_3.w = (FLOAT)0;"
    " }"
    " if(hd * 4 + 2 >= length) {"
    " temp_0.z = (FLOAT)0;"
    " temp_1.z = (FLOAT)0;"
    " temp_2.z = (FLOAT)0;"
    " temp_3.z = (FLOAT)0;"
    " }"
    " if(hd * 4 + 1 >= length) {"
    " temp_0.y = (FLOAT)0;"
    " temp_1.y = (FLOAT)0;"
    " temp_2.y = (FLOAT)0;"
    " temp_3.y = (FLOAT)0;"
    " }\n"
    "#ifdef VALUE_C4\n"
    "static inline FLOAT load_c4_value(__global const FLOAT* value,\n"
    " const int seq_storage,\n"
    " const int token,\n"
    " const int channel) {\n"
    " return value[((channel >> 2)*seq_storage+token)*4+(channel & 3)];\n"
    "}\n"
    "static inline FLOAT4 load_c4_value4(__global const FLOAT* value,\n"
    " const int seq_storage,\n"
    " const int token,\n"
    " const int channel,\n"
    " const int head_dim_offset,\n"
    " const int head_dim) {\n"
    " return (FLOAT4)(\n"
    " load_c4_value(value,seq_storage,token,channel),\n"
    " (head_dim_offset+1 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+1),\n"
    " (head_dim_offset+2 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+2),\n"
    " (head_dim_offset+3 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+3));\n"
    "}\n"
    "#endif\n"
    "#ifdef ATTENTION_C4\n"
    "static inline void store_attention_c4_4(__global FLOAT* output,const FLOAT4 value,const int seq_storage,\n"
    " const int token,const int channel,const int count) {\n"
    " if (((channel & 3) == 0) && count == 4) {\n"
    " const int offset=((channel >> 2)*seq_storage+token)*4;\n"
    " vstore4(value,0,output+offset);\n"
    " return;\n"
    " }\n"
    " int c=channel;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.x;\n"
    " if (count>1) {\n"
    " c=channel+1;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " c=channel+2;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.z;\n"
    " }\n"
    " if (count>3) {\n"
    " c=channel+3;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.w;\n"
    " }\n"
    "}\n"
    "static inline void store_attention_c4_8(__global FLOAT* output,const FLOAT8 value,const int seq_storage,\n"
    " const int token,const int channel,const int count) {\n"
    " const int low_count=min(count,4);\n"
    " store_attention_c4_4(output,value.lo,seq_storage,token,channel,low_count);\n"
    " if (count>4) {\n"
    " store_attention_c4_4(output,value.hi,seq_storage,token,channel+4,count-4);\n"
    " }\n"
    "}\n"
    "#endif\n"
    "// Store the first `count` (<=4) components of a FLOAT4 to contiguous addresses without vector subscript.\n"
    "static inline void store_scalar4(__global FLOAT* output,const int base,const FLOAT4 value,const int count) {\n"
    " output[base]=value.x;\n"
    " if (count>1) {\n"
    " output[base+1]=value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " output[base+2]=value.z;\n"
    " }\n"
    " if (count>3) {\n"
    " output[base+3]=value.w;\n"
    " }\n"
    "}\n"
    "// Store the first `count` (<=8) components of a FLOAT8 to contiguous addresses without vector subscript.\n"
    "static inline void store_scalar8(__global FLOAT* output,const int base,const FLOAT8 value,const int count) {\n"
    " output[base]=value.s0;\n"
    " if (count>1) {\n"
    " output[base+1]=value.s1;\n"
    " }\n"
    " if (count>2) {\n"
    " output[base+2]=value.s2;\n"
    " }\n"
    " if (count>3) {\n"
    " output[base+3]=value.s3;\n"
    " }\n"
    " if (count>4) {\n"
    " output[base+4]=value.s4;\n"
    " }\n"
    " if (count>5) {\n"
    " output[base+5]=value.s5;\n"
    " }\n"
    " if (count>6) {\n"
    " output[base+6]=value.s6;\n"
    " }\n"
    " if (count>7) {\n"
    " output[base+7]=value.s7;\n"
    " }\n"
    "}\n"
    "// Load the first `count` (1..4) components from contiguous addresses,zeroing the rest. Used on\n"
    "// the dim axis of the kv rearrange kernels,where head_dim is a runtime argument rather than a\n"
    "// macro,so the tail cannot be handled with #if the way the fused kernels do it.\n"
    "static inline FLOAT4 load_scalar4(__global const FLOAT* input,const int count) {\n"
    " FLOAT4 value=(FLOAT4)0;\n"
    " value.x=input[0];\n"
    " if (count>1) {\n"
    " value.y=input[1];\n"
    " }\n"
    " if (count>2) {\n"
    " value.z=input[2];\n"
    " }\n"
    " if (count>3) {\n"
    " value.w=input[3];\n"
    " }\n"
    " return value;\n"
    "}\n"
    "// The dim axis of the plain-buffer q/k/v inputs carries no padding and heads sit back to back,so a\n"
    "// vload4 on a partial tail group reads into the next head,and past the end of the buffer on the last\n"
    "// one. Only the tail group takes the scalar path,so the aligned groups keep their vector load. The\n"
    "// NC4HW4 value path already clamps this way inside load_c4_value4.\n"
    "static inline FLOAT4 load_dim4(__global const FLOAT* input,const int count) {\n"
    " return (count >= 4) ? vload4(0,input) : load_scalar4(input,count);\n"
    "}\n"
    "#ifndef NUMHEAD_GROUP_SIZE\n"
    "#define NUMHEAD_GROUP_SIZE 1\n"
    "#endif\n"
    "// \"Masked out\" sentinel. Must stay exactly representable in half (the score tile is\n"
    "// COMPUTE_FLOAT),so that the FA_NEG_TEST probe is an exact compare in both precisions.\n"
    "#define FA_NEG_INF (-60000.0f)\n"
    "#define FA_NEG_TEST (-50000.0f)\n"
    "// Flash-decoding (seqLen == 1). The three-stage decode path runs its P*V matmul on\n"
    "// ceil(headDim/8)*headNum work-items -- 256 for headDim 128/16 heads -- while\n"
    "// streaming the whole V cache,which leaves most of the GPU idle. These two kernels\n"
    "// split the kv axis across workgroups instead: each one softmaxes its own chunk and\n"
    "// emits an unnormalized (m,l,O),and the reduce kernel combines them.\n"
    "// Partials are fp32 (the host allocates a 4-byte-per-element scratch tensor).\n"
    "#ifndef FD_HEAD_DIM\n"
    "#define FD_HEAD_DIM 128\n"
    "#endif\n"
    "#ifndef FD_WG_SIZE\n"
    "#define FD_WG_SIZE 64\n"
    "#endif\n"
    "// kv entries per workgroup. Independent of FD_WG_SIZE: both phases walk their axis grid-stride,\n"
    "// so the group size is free to follow the wave rather than the tiling. It used to be pinned to\n"
    "// headDim/2 -- the value the PV phase needed -- which made the kv split a function of headDim.\n"
    "#ifndef FD_CHUNK\n"
    "#define FD_CHUNK 64\n"
    "#endif\n"
    "// PV works on dim quads,so the trailing quad is short when headDim is not 4-aligned.\n"
    "#define FD_DIM_QUADS (((FD_HEAD_DIM)+3) >> 2)\n"
    "// Store one finished dim quad of a decode row. The fused single-chunk path below completes a quad\n"
    "// at a time,so it cannot use the float4 store that the reduce kernel does; store_attention_c4_4\n"
    "// already handles a count below 4 and a channel that is not 4-aligned.\n"
    "static inline void store_decode_quad(__global FLOAT* output,const int channel,const float4 value,\n"
    " const int count) {\n"
    "#ifdef ATTENTION_C4\n"
    " store_attention_c4_4(output,CONVERT_FLOAT4(value),1,0,channel,count);\n"
    "#else\n"
    " if (count == 4) {\n"
    " vstore4(CONVERT_FLOAT4(value),0,output+channel);\n"
    " } else {\n"
    " output[channel]=(FLOAT)value.x;\n"
    " if (count>1) {\n"
    " output[channel+1]=(FLOAT)value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " output[channel+2]=(FLOAT)value.z;\n"
    " }\n"
    " }\n"
    "#endif\n"
    "}\n"
    "__kernel void flash_decode_partial(\n"
    " __global const FLOAT *query,// [1,1,headNum,headDim]\n"
    " __global const FLOAT *past_key,// [1,kvHeadNum,headDim,maxLen]\n"
    " __global const FLOAT *past_value,// [1,kvHeadNum,maxLen,headDim]\n"
    " __global float *partial_o,// [headNum,numChunk,headDim]\n"
    " __global float *partial_ml,// [headNum,numChunk,2]\n"
    " __private const float scale,\n"
    " __private const int kv_seq_len,\n"
    " __private const int max_len,\n"
    " __private const int head_num,\n"
    " __private const int num_chunk,\n"
    " __global FLOAT *output,// [1,1,headNum,headDim],fused path only\n"
    " __global const FLOAT *key,// [1,1,kvHeadNum,headDim],this step only\n"
    " __global const FLOAT *value,// same layout,see the C4 note below\n"
    " // Writable aliases keep the read-only cache pointers qualified const.\n"
    " __global FLOAT *past_key_out,\n"
    " __global FLOAT *past_value_out) {\n"
    " const int lid=get_local_id(0);\n"
    " const int chunk=get_group_id(0);\n"
    " const int hn=get_global_id(1);\n"
    " const int kv_hn=hn/NUMHEAD_GROUP_SIZE;\n"
    " const int k0=chunk*FD_CHUNK;\n"
    " __local float lsd[FD_CHUNK];\n"
    " __local FLOAT lqd[FD_HEAD_DIM];\n"
    " for (int d=lid; d<FD_HEAD_DIM; d += FD_WG_SIZE) {\n"
    " lqd[d]=query[hn*FD_HEAD_DIM+d];\n"
    " }\n"
    " // The last chunk appends the current KV row before reading it. The input is contiguous for the\n"
    " // single-token,single-batch decode shape,including NC4HW4 where the sequence stride is one.\n"
    " // Other chunks only need to synchronize local query loading.\n"
    " if (chunk == num_chunk-1) {\n"
    " const int past_len=kv_seq_len-1;\n"
    " const int kv_base=kv_hn*FD_HEAD_DIM;\n"
    " __global FLOAT* vrow=past_value_out+(kv_hn*max_len+past_len)*FD_HEAD_DIM;\n"
    " for (int d=lid; d<FD_HEAD_DIM; d += FD_WG_SIZE) {\n"
    " past_key_out[(kv_base+d)*max_len+past_len]=key[kv_base+d];\n"
    " vrow[d]=value[kv_base+d];\n"
    " }\n"
    " barrier(CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE);\n"
    " } else {\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " }\n"
    "#if (FD_CHUNK == 64) && defined(FD_QK_PAIR)\n"
    " // Adjacent KV entries are contiguous in K,so one lane can process a pair with vector loads.\n"
    " float2 qk2=(float2)FA_NEG_INF;\n"
    " for (int u=lid; u<FD_CHUNK/2; u += FD_WG_SIZE) {\n"
    " const int kg=k0+(u << 1);\n"
    " if (kg+2 <= kv_seq_len) {\n"
    " __global const FLOAT* kp=past_key+(kv_hn*FD_HEAD_DIM)*max_len+kg;\n"
    " float2 acc0=0.0f,acc1=0.0f;\n"
    " for (int d2=0; d2<FD_HEAD_DIM; d2 += 2) {\n"
    " const float2 q2=convert_float2(vload2(0,lqd+d2));\n"
    " acc0=mad((float2)q2.x,convert_float2(vload2(0,kp+(d2+0)*max_len)),acc0);\n"
    " acc1=mad((float2)q2.y,convert_float2(vload2(0,kp+(d2+1)*max_len)),acc1);\n"
    " }\n"
    " // The two chains split the dims by residue mod 2,each holding the whole 2-kv vector.\n"
    " qk2=(acc0+acc1)*scale;\n"
    " } else if (kg<kv_seq_len) {\n"
    " // Trailing pair: only one valid row,and the float2 load would read the next kv row\n"
    " // past kv_seq_len,so do it scalar. At most one lane per workgroup takes this path;\n"
    " // lanes whose pair is wholly past kv_seq_len must keep their FA_NEG_INF scores.\n"
    " __global const FLOAT* kr=past_key+(kv_hn*FD_HEAD_DIM)*max_len+kg;\n"
    " float acc=0.0f;\n"
    " for (int d=0; d<FD_HEAD_DIM; ++d) {\n"
    " acc=mad((float)lqd[d],(float)kr[d*max_len],acc);\n"
    " }\n"
    " qk2.x=acc*scale;\n"
    " }\n"
    " }\n"
    " // The 32 pair lanes cover all 64 slots of lsd; slots past kv_seq_len hold FA_NEG_INF scores,\n"
    " // which become 0 in the prob pass below.\n"
    " if (lid<FD_CHUNK/2) {\n"
    " vstore2(qk2,lid,lsd);\n"
    " }\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " // Every work-item reduces the whole chunk redundantly: all lanes read the same address on\n"
    " // each step,so it is a broadcast and needs no barrier,unlike a tree reduction.\n"
    " float m=FA_NEG_INF;\n"
    " float4 m4=(float4)FA_NEG_INF;\n"
    " for (int i=0; i<FD_CHUNK; i += 4) {\n"
    " m4=fmax(m4,vload4(0,lsd+i));\n"
    " }\n"
    " m=fmax(fmax(m4.x,m4.y),fmax(m4.z,m4.w));\n"
    " float2 p2=(float2)0.0f;\n"
    " p2.x=(qk2.x <= FA_NEG_TEST) ? 0.0f : native_exp(qk2.x-m);\n"
    " p2.y=(qk2.y <= FA_NEG_TEST) ? 0.0f : native_exp(qk2.y-m);\n"
    " if (lid<FD_CHUNK/2) {\n"
    " vstore2(p2,lid,lsd);\n"
    " }\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " // Same broadcast shape as the max; the summation order differs from a scalar loop,so l is\n"
    " // not bit-identical -- it is an fp32 accumulator that the reduce kernel divides by.\n"
    " float l=0.0f;\n"
    " float4 l4=(float4)0.0f;\n"
    " for (int i=0; i<FD_CHUNK; i += 4) {\n"
    " l4 += vload4(0,lsd+i);\n"
    " }\n"
    " l=(l4.x+l4.y)+(l4.z+l4.w);\n"
    "#else\n"
    " // K is [..,headDim,maxLen],so consecutive kv of one dim are contiguous and lanes working on\n"
    " // neighbouring kv coalesce.\n"
    " for (int kk=lid; kk<FD_CHUNK; kk += FD_WG_SIZE) {\n"
    " const int kg=k0+kk;\n"
    " float s=FA_NEG_INF;\n"
    " if (kg<kv_seq_len) {\n"
    " __global const FLOAT* kp=past_key+(kv_hn*FD_HEAD_DIM)*max_len+kg;\n"
    " float acc=0.0f;\n"
    " for (int d=0; d<FD_HEAD_DIM; ++d) {\n"
    " acc=mad((float)lqd[d],(float)kp[d*max_len],acc);\n"
    " }\n"
    " s=acc*scale;\n"
    " }\n"
    " lsd[kk]=s;\n"
    " }\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " // Every work-item reduces the chunk through broadcast local reads; vector loads shorten the\n"
    " // serial dependency chain without a tree-reduction barrier.\n"
    " float m=FA_NEG_INF;\n"
    "#if (FD_CHUNK % 4) == 0\n"
    " float4 m4=(float4)FA_NEG_INF;\n"
    " for (int i=0; i<FD_CHUNK; i += 4) {\n"
    " m4=fmax(m4,vload4(0,lsd+i));\n"
    " }\n"
    " m=fmax(fmax(m4.x,m4.y),fmax(m4.z,m4.w));\n"
    "#else\n"
    " for (int i=0; i<FD_CHUNK; ++i) {\n"
    " m=fmax(m,lsd[i]);\n"
    " }\n"
    "#endif\n"
    " // Everyone is done reading the scores before they are overwritten with probabilities. The\n"
    " // score is re-read from local rather than kept private,because a lane no longer owns exactly\n"
    " // one kv.\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " for (int kk=lid; kk<FD_CHUNK; kk += FD_WG_SIZE) {\n"
    " const float s=lsd[kk];\n"
    " lsd[kk]=(s <= FA_NEG_TEST) ? 0.0f : native_exp(s-m);\n"
    " }\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " // Same shape. The summation order differs from the scalar loop,so l is not bit-identical --\n"
    " // it is an fp32 accumulator that the reduce kernel divides by.\n"
    " float l=0.0f;\n"
    "#if (FD_CHUNK % 4) == 0\n"
    " float4 l4=(float4)0.0f;\n"
    " for (int i=0; i<FD_CHUNK; i += 4) {\n"
    " l4 += vload4(0,lsd+i);\n"
    " }\n"
    " l=(l4.x+l4.y)+(l4.z+l4.w);\n"
    "#else\n"
    " for (int i=0; i<FD_CHUNK; ++i) {\n"
    " l += lsd[i];\n"
    " }\n"
    "#endif\n"
    "#endif\n"
    " // Unnormalized O for this chunk,one dim quad per unit.\n"
    " const int kv_valid=min(FD_CHUNK,kv_seq_len-k0);\n"
    " const int base=(hn*num_chunk+chunk);\n"
    " // A single chunk already spans the whole kv axis,so (m,l) are global and this lane's acc4\n"
    " // is the finished O for its dim quad -- there is nothing for the reduce kernel to merge.\n"
    " // Dividing by l here instead saves reduce's round trip for partial_o/partial_ml through\n"
    " // global memory,which is a large share of the op at short kv. reduce is still launched --\n"
    " // onExecute enqueues a fixed kernel list,and under the record queue it is built once -- but\n"
    " // it early-returns.\n"
    " const bool fused=(1 == num_chunk);\n"
    " const float rl=(l>0.0f) ? (1.0f/l) : 0.0f;\n"
    "#if (FD_HEAD_DIM % 4) == 0\n"
    " for (int u=lid; u<FD_DIM_QUADS; u += FD_WG_SIZE) {\n"
    " const int d4=u << 2;\n"
    " __global const FLOAT* vp=past_value+(kv_hn*max_len)*FD_HEAD_DIM+d4;\n"
    " float4 acc4=0.0f;\n"
    " for (int i=0; i<kv_valid; ++i) {\n"
    " acc4=mad((float4)lsd[i],convert_float4(vload4(0,vp+(k0+i)*FD_HEAD_DIM)),acc4);\n"
    " }\n"
    " if (fused) {\n"
    " store_decode_quad(output,hn*FD_HEAD_DIM+d4,acc4*rl,4);\n"
    " } else {\n"
    " vstore4(acc4,0,partial_o+base*FD_HEAD_DIM+d4);\n"
    " }\n"
    " }\n"
    "#else\n"
    " // headDim not 4-aligned: the trailing quad is short,so fall back to scalar-safe dim pairs.\n"
    " for (int u=lid; u<FD_DIM_QUADS*2; u += FD_WG_SIZE) {\n"
    " const int d2=u << 1;\n"
    " __global const FLOAT* vp=past_value+(kv_hn*max_len)*FD_HEAD_DIM+d2;\n"
    " const int dims=min(2,FD_HEAD_DIM-d2);\n"
    " float2 acc2=0.0f;\n"
    " for (int i=0; i<kv_valid; ++i) {\n"
    " __global const FLOAT* vrow=vp+(k0+i)*FD_HEAD_DIM;\n"
    " float2 vv=0.0f;\n"
    " vv.x=(float)vrow[0];\n"
    " if (dims>1) {\n"
    " vv.y=(float)vrow[1];\n"
    " }\n"
    " acc2=mad((float2)lsd[i],vv,acc2);\n"
    " }\n"
    " if (fused) {\n"
    " store_decode_quad(output,hn*FD_HEAD_DIM+d2,(float4)(acc2.x,acc2.y,0.0f,0.0f),dims);\n"
    " } else {\n"
    " partial_o[base*FD_HEAD_DIM+d2]=acc2.x;\n"
    " if (dims>1) {\n"
    " partial_o[base*FD_HEAD_DIM+d2+1]=acc2.y;\n"
    " }\n"
    " }\n"
    " }\n"
    "#endif\n"
    " if (0 == lid && !fused) {\n"
    " partial_ml[base*2]=m;\n"
    " partial_ml[base*2+1]=l;\n"
    " }\n"
    "}\n";
#endif
} // namespace MNN
