#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* attention_flash_decode_reduce_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "#define GLOBAL_SIZE_3_DIMS "
    " __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
    "#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "
    " return; "
    " }\n"
    "#define GLOBAL_SIZE_2_DIMS "
    " __private const int global_size_dim0,__private const int global_size_dim1,\n"
    "#define DEAL_NON_UNIFORM_DIM2(input1, input2) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1) { "
    " return; "
    " }\n"
    "#define DEAL_OUTER_SEQLEN_NOT_ALIGN(length) "
    " if(4 * sl + 3 >= length) {"
    " temp_3 = (FLOAT4)0;"
    " }"
    " if(4 * sl + 2 >= length) {"
    " temp_2 = (FLOAT4)0;"
    " }"
    " if(4 * sl + 1 >= length) {"
    " temp_1 = (FLOAT4)0;"
    " }\n"
    "#define DEAL_INNER_HEADDIM_NOT_ALIGN(length) "
    " if(hd * 4 + 3 >= length) {"
    " temp_0.w = (FLOAT)0;"
    " temp_1.w = (FLOAT)0;"
    " temp_2.w = (FLOAT)0;"
    " temp_3.w = (FLOAT)0;"
    " }"
    " if(hd * 4 + 2 >= length) {"
    " temp_0.z = (FLOAT)0;"
    " temp_1.z = (FLOAT)0;"
    " temp_2.z = (FLOAT)0;"
    " temp_3.z = (FLOAT)0;"
    " }"
    " if(hd * 4 + 1 >= length) {"
    " temp_0.y = (FLOAT)0;"
    " temp_1.y = (FLOAT)0;"
    " temp_2.y = (FLOAT)0;"
    " temp_3.y = (FLOAT)0;"
    " }\n"
    "#ifdef VALUE_C4\n"
    "static inline FLOAT load_c4_value(__global const FLOAT* value,\n"
    " const int seq_storage,\n"
    " const int token,\n"
    " const int channel) {\n"
    " return value[((channel >> 2)*seq_storage+token)*4+(channel & 3)];\n"
    "}\n"
    "static inline FLOAT4 load_c4_value4(__global const FLOAT* value,\n"
    " const int seq_storage,\n"
    " const int token,\n"
    " const int channel,\n"
    " const int head_dim_offset,\n"
    " const int head_dim) {\n"
    " return (FLOAT4)(\n"
    " load_c4_value(value,seq_storage,token,channel),\n"
    " (head_dim_offset+1 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+1),\n"
    " (head_dim_offset+2 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+2),\n"
    " (head_dim_offset+3 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+3));\n"
    "}\n"
    "#endif\n"
    "#ifdef ATTENTION_C4\n"
    "static inline void store_attention_c4_4(__global FLOAT* output,const FLOAT4 value,const int seq_storage,\n"
    " const int token,const int channel,const int count) {\n"
    " if (((channel & 3) == 0) && count == 4) {\n"
    " const int offset=((channel >> 2)*seq_storage+token)*4;\n"
    " vstore4(value,0,output+offset);\n"
    " return;\n"
    " }\n"
    " int c=channel;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.x;\n"
    " if (count>1) {\n"
    " c=channel+1;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " c=channel+2;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.z;\n"
    " }\n"
    " if (count>3) {\n"
    " c=channel+3;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.w;\n"
    " }\n"
    "}\n"
    "static inline void store_attention_c4_8(__global FLOAT* output,const FLOAT8 value,const int seq_storage,\n"
    " const int token,const int channel,const int count) {\n"
    " const int low_count=min(count,4);\n"
    " store_attention_c4_4(output,value.lo,seq_storage,token,channel,low_count);\n"
    " if (count>4) {\n"
    " store_attention_c4_4(output,value.hi,seq_storage,token,channel+4,count-4);\n"
    " }\n"
    "}\n"
    "#endif\n"
    "// Store the first `count` (<=4) components of a FLOAT4 to contiguous addresses without vector subscript.\n"
    "static inline void store_scalar4(__global FLOAT* output,const int base,const FLOAT4 value,const int count) {\n"
    " output[base]=value.x;\n"
    " if (count>1) {\n"
    " output[base+1]=value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " output[base+2]=value.z;\n"
    " }\n"
    " if (count>3) {\n"
    " output[base+3]=value.w;\n"
    " }\n"
    "}\n"
    "// Store the first `count` (<=8) components of a FLOAT8 to contiguous addresses without vector subscript.\n"
    "static inline void store_scalar8(__global FLOAT* output,const int base,const FLOAT8 value,const int count) {\n"
    " output[base]=value.s0;\n"
    " if (count>1) {\n"
    " output[base+1]=value.s1;\n"
    " }\n"
    " if (count>2) {\n"
    " output[base+2]=value.s2;\n"
    " }\n"
    " if (count>3) {\n"
    " output[base+3]=value.s3;\n"
    " }\n"
    " if (count>4) {\n"
    " output[base+4]=value.s4;\n"
    " }\n"
    " if (count>5) {\n"
    " output[base+5]=value.s5;\n"
    " }\n"
    " if (count>6) {\n"
    " output[base+6]=value.s6;\n"
    " }\n"
    " if (count>7) {\n"
    " output[base+7]=value.s7;\n"
    " }\n"
    "}\n"
    "// Load the first `count` (1..4) components from contiguous addresses,zeroing the rest. Used on\n"
    "// the dim axis of the kv rearrange kernels,where head_dim is a runtime argument rather than a\n"
    "// macro,so the tail cannot be handled with #if the way the fused kernels do it.\n"
    "static inline FLOAT4 load_scalar4(__global const FLOAT* input,const int count) {\n"
    " FLOAT4 value=(FLOAT4)0;\n"
    " value.x=input[0];\n"
    " if (count>1) {\n"
    " value.y=input[1];\n"
    " }\n"
    " if (count>2) {\n"
    " value.z=input[2];\n"
    " }\n"
    " if (count>3) {\n"
    " value.w=input[3];\n"
    " }\n"
    " return value;\n"
    "}\n"
    "// The dim axis of the plain-buffer q/k/v inputs carries no padding and heads sit back to back,so a\n"
    "// vload4 on a partial tail group reads into the next head,and past the end of the buffer on the last\n"
    "// one. Only the tail group takes the scalar path,so the aligned groups keep their vector load. The\n"
    "// NC4HW4 value path already clamps this way inside load_c4_value4.\n"
    "static inline FLOAT4 load_dim4(__global const FLOAT* input,const int count) {\n"
    " return (count >= 4) ? vload4(0,input) : load_scalar4(input,count);\n"
    "}\n"
    "// \"Masked out\" sentinel. Must stay exactly representable in half (the score tile is\n"
    "// COMPUTE_FLOAT),so that the FA_NEG_TEST probe is an exact compare in both precisions.\n"
    "#define FA_NEG_INF (-60000.0f)\n"
    "#define FA_NEG_TEST (-50000.0f)\n"
    "#ifndef FD_HEAD_DIM\n"
    "#define FD_HEAD_DIM 128\n"
    "#endif\n"
    "#ifndef FD_WG_SIZE\n"
    "#define FD_WG_SIZE 64\n"
    "#endif\n"
    "// kv entries per workgroup. Independent of FD_WG_SIZE: both phases walk their axis grid-stride,\n"
    "// so the group size is free to follow the wave rather than the tiling. It used to be pinned to\n"
    "// headDim/2 -- the value the PV phase needed -- which made the kv split a function of headDim.\n"
    "#ifndef FD_CHUNK\n"
    "#define FD_CHUNK 64\n"
    "#endif\n"
    "// PV works on dim quads,so the trailing quad is short when headDim is not 4-aligned.\n"
    "#define FD_DIM_QUADS (((FD_HEAD_DIM)+3) >> 2)\n"
    "__kernel void flash_decode_reduce(\n"
    " __global const float *partial_o,// [headNum,numChunk,headDim]\n"
    " __global const float *partial_ml,// [headNum,numChunk,2]\n"
    " __global FLOAT *output,// [1,1,headNum,headDim]\n"
    " __private const int head_num,\n"
    " __private const int num_chunk) {\n"
    " if (1 == num_chunk) {\n"
    " // flash_decode_partial took the fused path and wrote the normalized row itself. This launch\n"
    " // cannot be skipped from the host -- see the comment there -- so make it a no-op.\n"
    " return;\n"
    " }\n"
    " const int d4=get_global_id(0) << 2;\n"
    " const int hn=get_global_id(1);\n"
    " if (d4 >= FD_HEAD_DIM || hn >= head_num) {\n"
    " return;\n"
    " }\n"
    " // The trailing dim group is partial unless headDim is a multiple of 4,and `d4<FD_HEAD_DIM`\n"
    " // alone does not catch it. A whole float4 there reads past partial_o,and on the output side\n"
    " // it would overwrite the leading dims of the next head.\n"
    " const int dcount=min(4,FD_HEAD_DIM-d4);\n"
    " float m=FA_NEG_INF;\n"
    " for (int c=0; c<num_chunk; ++c) {\n"
    " m=fmax(m,partial_ml[(hn*num_chunk+c)*2]);\n"
    " }\n"
    " float l=0.0f;\n"
    " float4 acc=0.0f;\n"
    " for (int c=0; c<num_chunk; ++c) {\n"
    " const int base=hn*num_chunk+c;\n"
    " const float mc=partial_ml[base*2];\n"
    " const float w=(mc <= FA_NEG_TEST) ? 0.0f : native_exp(mc-m);\n"
    " l += partial_ml[base*2+1]*w;\n"
    " const int off=base*FD_HEAD_DIM+d4;\n"
    "#if (FD_HEAD_DIM % 4) == 0\n"
    " acc=mad((float4)w,vload4(0,partial_o+off),acc);\n"
    "#else\n"
    " // Scalar loads,kept behind a compile-time branch so the aligned case has no run-time test\n"
    " // inside the chunk loop. This covers every group,not just the short one: dcount is 4 for\n"
    " // all but the last. The lanes past dcount stay zero and are never stored.\n"
    " float4 po=(float4)0.0f;\n"
    " po.x=partial_o[off];\n"
    " if (dcount>1) {\n"
    " po.y=partial_o[off+1];\n"
    " }\n"
    " if (dcount>2) {\n"
    " po.z=partial_o[off+2];\n"
    " }\n"
    " if (dcount>3) {\n"
    " po.w=partial_o[off+3];\n"
    " }\n"
    " acc=mad((float4)w,po,acc);\n"
    "#endif\n"
    " }\n"
    " acc *= (l>0.0f) ? (1.0f/l) : 0.0f;\n"
    "#ifdef ATTENTION_C4\n"
    " store_attention_c4_4(output,CONVERT_FLOAT4(acc),1,0,hn*FD_HEAD_DIM+d4,dcount);\n"
    "#else\n"
    " if (4 == dcount) {\n"
    " vstore4(CONVERT_FLOAT4(acc),0,output+hn*FD_HEAD_DIM+d4);\n"
    " } else {\n"
    " store_scalar4(output,hn*FD_HEAD_DIM+d4,CONVERT_FLOAT4(acc),dcount);\n"
    " }\n"
    "#endif\n"
    "}\n";
#endif
} // namespace MNN
