#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* attention_long_layout_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "#define GLOBAL_SIZE_3_DIMS "
    " __private const int global_size_dim0,__private const int global_size_dim1,__private const int global_size_dim2,\n"
    "#define DEAL_NON_UNIFORM_DIM3(input1, input2, input3) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1 || input3 >= global_size_dim2) { "
    " return; "
    " }\n"
    "#define GLOBAL_SIZE_2_DIMS "
    " __private const int global_size_dim0,__private const int global_size_dim1,\n"
    "#define DEAL_NON_UNIFORM_DIM2(input1, input2) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1) { "
    " return; "
    " }\n"
    "#define DEAL_OUTER_SEQLEN_NOT_ALIGN(length) "
    " if(4 * sl + 3 >= length) {"
    " temp_3 = (FLOAT4)0;"
    " }"
    " if(4 * sl + 2 >= length) {"
    " temp_2 = (FLOAT4)0;"
    " }"
    " if(4 * sl + 1 >= length) {"
    " temp_1 = (FLOAT4)0;"
    " }\n"
    "#define DEAL_INNER_HEADDIM_NOT_ALIGN(length) "
    " if(hd * 4 + 3 >= length) {"
    " temp_0.w = (FLOAT)0;"
    " temp_1.w = (FLOAT)0;"
    " temp_2.w = (FLOAT)0;"
    " temp_3.w = (FLOAT)0;"
    " }"
    " if(hd * 4 + 2 >= length) {"
    " temp_0.z = (FLOAT)0;"
    " temp_1.z = (FLOAT)0;"
    " temp_2.z = (FLOAT)0;"
    " temp_3.z = (FLOAT)0;"
    " }"
    " if(hd * 4 + 1 >= length) {"
    " temp_0.y = (FLOAT)0;"
    " temp_1.y = (FLOAT)0;"
    " temp_2.y = (FLOAT)0;"
    " temp_3.y = (FLOAT)0;"
    " }\n"
    "#ifdef VALUE_C4\n"
    "static inline FLOAT load_c4_value(__global const FLOAT* value,\n"
    " const int seq_storage,\n"
    " const int token,\n"
    " const int channel) {\n"
    " return value[((channel >> 2)*seq_storage+token)*4+(channel & 3)];\n"
    "}\n"
    "static inline FLOAT4 load_c4_value4(__global const FLOAT* value,\n"
    " const int seq_storage,\n"
    " const int token,\n"
    " const int channel,\n"
    " const int head_dim_offset,\n"
    " const int head_dim) {\n"
    " return (FLOAT4)(\n"
    " load_c4_value(value,seq_storage,token,channel),\n"
    " (head_dim_offset+1 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+1),\n"
    " (head_dim_offset+2 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+2),\n"
    " (head_dim_offset+3 >= head_dim) ? (FLOAT)0 : load_c4_value(value,seq_storage,token,channel+3));\n"
    "}\n"
    "#endif\n"
    "#ifdef ATTENTION_C4\n"
    "static inline void store_attention_c4_4(__global FLOAT* output,const FLOAT4 value,const int seq_storage,\n"
    " const int token,const int channel,const int count) {\n"
    " if (((channel & 3) == 0) && count == 4) {\n"
    " const int offset=((channel >> 2)*seq_storage+token)*4;\n"
    " vstore4(value,0,output+offset);\n"
    " return;\n"
    " }\n"
    " int c=channel;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.x;\n"
    " if (count>1) {\n"
    " c=channel+1;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " c=channel+2;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.z;\n"
    " }\n"
    " if (count>3) {\n"
    " c=channel+3;\n"
    " output[((c >> 2)*seq_storage+token)*4+(c & 3)]=value.w;\n"
    " }\n"
    "}\n"
    "static inline void store_attention_c4_8(__global FLOAT* output,const FLOAT8 value,const int seq_storage,\n"
    " const int token,const int channel,const int count) {\n"
    " const int low_count=min(count,4);\n"
    " store_attention_c4_4(output,value.lo,seq_storage,token,channel,low_count);\n"
    " if (count>4) {\n"
    " store_attention_c4_4(output,value.hi,seq_storage,token,channel+4,count-4);\n"
    " }\n"
    "}\n"
    "#endif\n"
    "// Store the first `count` (<=4) components of a FLOAT4 to contiguous addresses without vector subscript.\n"
    "static inline void store_scalar4(__global FLOAT* output,const int base,const FLOAT4 value,const int count) {\n"
    " output[base]=value.x;\n"
    " if (count>1) {\n"
    " output[base+1]=value.y;\n"
    " }\n"
    " if (count>2) {\n"
    " output[base+2]=value.z;\n"
    " }\n"
    " if (count>3) {\n"
    " output[base+3]=value.w;\n"
    " }\n"
    "}\n"
    "// Store the first `count` (<=8) components of a FLOAT8 to contiguous addresses without vector subscript.\n"
    "static inline void store_scalar8(__global FLOAT* output,const int base,const FLOAT8 value,const int count) {\n"
    " output[base]=value.s0;\n"
    " if (count>1) {\n"
    " output[base+1]=value.s1;\n"
    " }\n"
    " if (count>2) {\n"
    " output[base+2]=value.s2;\n"
    " }\n"
    " if (count>3) {\n"
    " output[base+3]=value.s3;\n"
    " }\n"
    " if (count>4) {\n"
    " output[base+4]=value.s4;\n"
    " }\n"
    " if (count>5) {\n"
    " output[base+5]=value.s5;\n"
    " }\n"
    " if (count>6) {\n"
    " output[base+6]=value.s6;\n"
    " }\n"
    " if (count>7) {\n"
    " output[base+7]=value.s7;\n"
    " }\n"
    "}\n"
    "// Load the first `count` (1..4) components from contiguous addresses,zeroing the rest. Used on\n"
    "// the dim axis of the kv rearrange kernels,where head_dim is a runtime argument rather than a\n"
    "// macro,so the tail cannot be handled with #if the way the fused kernels do it.\n"
    "static inline FLOAT4 load_scalar4(__global const FLOAT* input,const int count) {\n"
    " FLOAT4 value=(FLOAT4)0;\n"
    " value.x=input[0];\n"
    " if (count>1) {\n"
    " value.y=input[1];\n"
    " }\n"
    " if (count>2) {\n"
    " value.z=input[2];\n"
    " }\n"
    " if (count>3) {\n"
    " value.w=input[3];\n"
    " }\n"
    " return value;\n"
    "}\n"
    "// The dim axis of the plain-buffer q/k/v inputs carries no padding and heads sit back to back,so a\n"
    "// vload4 on a partial tail group reads into the next head,and past the end of the buffer on the last\n"
    "// one. Only the tail group takes the scalar path,so the aligned groups keep their vector load. The\n"
    "// NC4HW4 value path already clamps this way inside load_c4_value4.\n"
    "static inline FLOAT4 load_dim4(__global const FLOAT* input,const int count) {\n"
    " return (count >= 4) ? vload4(0,input) : load_scalar4(input,count);\n"
    "}\n"
    "__kernel void rearrange_qkv(GLOBAL_SIZE_3_DIMS\n"
    " __global const FLOAT *input_q,//[batch,seqLenQ/4,headNum,headDim,seqLenQ_4]\n"
    " __global const FLOAT *input_k,// [batch,seqLenKV/4,headNum/group,headDim,seqLenKV_4]\n"
    " __global const FLOAT *input_v,// [batch,seqLenKV/4,headNum/group,headDim,seqLenKV_4]\n"
    " __global FLOAT *output_q,// [batch*headNum,ROUND_UP(headDim,mTileHDK),ROUND_UP(seqLenQ,mTileQ)]\n"
    " __global FLOAT *output_k,// [batch*headNum/group,ROUND_UP(headDim,mTileHDK),ROUND_UP(seqLenKV,mTileKV)]\n"
    " __global FLOAT *output_v,// [batch*headNum/group,ROUND_UP(seqLenKV,mTileKV),ROUND_UP(headDim,mTileHDN)]\n"
    " #ifdef SAVE_KV\n"
    " __global FLOAT *past_k,// [batch,headNum/group,headDim,seqLenKV_4]\n"
    " __global FLOAT *past_v,// [batch,headNum/group,seqLenKV_4,headDim]\n"
    " #endif\n"
    " __private const int4 tile,// [mTileQ,mTileKV,mTileHDK,mTileHDN]\n"
    " __private const int4 shape,// [seqLenQ,seqLenKV,headNum,headDim]\n"
    " __private const int4 param,// [group,batch,max_len,past_len]\n"
    " __private const int maxLenKV\n"
    ") {\n"
    " const int sl=get_global_id(0); // seqLen/4 : max(seqLenPackQ/4,seqLenPackKV/4)\n"
    " const int hd=get_global_id(1); // headDim/4 : max(headDimPackQK/4,headDimPackV/4)\n"
    " const int z=get_global_id(2); // batch*headNum\n"
    " DEAL_NON_UNIFORM_DIM3(sl,hd,z);\n"
    " \n"
    " const int seqLenQ=shape.x;\n"
    " const int seqLenKV=shape.y;\n"
    " const int headNum=shape.z;\n"
    " const int headDim=shape.w;\n"
    " const int group=param.x;\n"
    " const int batch=param.y;\n"
    " const int b=z % batch;\n"
    " const int hn=z/batch;\n"
    " \n"
    " const int seqLenQ_4=(seqLenQ+3)/4;\n"
    " //const int in_offset_q=(((b*seqLenQ_4+sl)*headNum+hn)*headDim+4*hd)*4;\n"
    " const int in_offset_q=(((b*seqLenQ+sl*4)*headNum+hn)*headDim+4*hd);\n"
    " const int seqLenPackQ=((seqLenQ+tile.x-1)/tile.x)*tile.x;\n"
    " const int headDimPackQK=((headDim+tile.z-1)/tile.z)*tile.z;\n"
    " const int out_offset_q=(((b*headNum+hn)*headDimPackQK+hd*4)*seqLenPackQ+sl*4);\n"
    " \n"
    " if(sl*4<seqLenPackQ && hd*4<headDimPackQK) {\n"
    " if(sl*4 >= seqLenQ || hd*4 >= headDim) {\n"
    " vstore4((FLOAT4)0,0,output_q+out_offset_q);\n"
    " vstore4((FLOAT4)0,0,output_q+out_offset_q+seqLenPackQ);\n"
    " vstore4((FLOAT4)0,0,output_q+out_offset_q+2*seqLenPackQ);\n"
    " vstore4((FLOAT4)0,0,output_q+out_offset_q+3*seqLenPackQ);\n"
    " } else {\n"
    " const int dim_count_q=headDim-4*hd;\n"
    " FLOAT4 temp_0=load_dim4(input_q+in_offset_q,dim_count_q);\n"
    " FLOAT4 temp_1=(sl*4+1 >= seqLenQ) ? (FLOAT4)0 : load_dim4(input_q+in_offset_q+headNum*headDim,dim_count_q);\n"
    " FLOAT4 temp_2=(sl*4+2 >= seqLenQ) ? (FLOAT4)0 : load_dim4(input_q+in_offset_q+2*headNum*headDim,dim_count_q);\n"
    " FLOAT4 temp_3=(sl*4+3 >= seqLenQ) ? (FLOAT4)0 : load_dim4(input_q+in_offset_q+3*headNum*headDim,dim_count_q);\n"
    " #ifdef HEADDIM_LEAVE\n"
    " DEAL_INNER_HEADDIM_NOT_ALIGN(headDim)\n"
    " #endif\n"
    " #ifdef SEQLEN_LEAVE\n"
    " DEAL_OUTER_SEQLEN_NOT_ALIGN(seqLenQ)\n"
    " #endif\n"
    " vstore4((FLOAT4)(temp_0.s0,temp_1.s0,temp_2.s0,temp_3.s0),0,output_q+out_offset_q);\n"
    " vstore4((FLOAT4)(temp_0.s1,temp_1.s1,temp_2.s1,temp_3.s1),0,output_q+out_offset_q+seqLenPackQ);\n"
    " vstore4((FLOAT4)(temp_0.s2,temp_1.s2,temp_2.s2,temp_3.s2),0,output_q+out_offset_q+2*seqLenPackQ);\n"
    " vstore4((FLOAT4)(temp_0.s3,temp_1.s3,temp_2.s3,temp_3.s3),0,output_q+out_offset_q+3*seqLenPackQ);\n"
    " }\n"
    " }\n"
    " \n"
    " if(hn >= headNum/group) {\n"
    " return;\n"
    " }\n"
    " \n"
    " const int seqLenPackKV=((seqLenKV+tile.y-1)/tile.y)*tile.y;\n"
    " const int headDimPackV=((headDim+tile.w-1)/tile.w)*tile.w;\n"
    " const int seqLenKV_4=(seqLenKV+3)/4;\n"
    " const int in_offset_kv=(((b*seqLenKV+sl*4)*headNum/group+hn)*headDim+4*hd);\n"
    " const int past_offset_k=(((b*headNum/group+hn)*headDim+hd*4)*maxLenKV+sl*4);\n"
    " const int past_offset_v=(((b*headNum/group+hn)*maxLenKV+sl*4)*headDim+4*hd);\n"
    " if(sl*4<seqLenPackKV && hd*4<headDimPackQK) {\n"
    " const int out_offset_k=(((b*headNum/group+hn)*headDimPackQK+hd*4)*seqLenPackKV+sl*4);\n"
    " if(sl*4 >= seqLenKV || hd*4 >= headDim) {\n"
    " vstore4((FLOAT4)0,0,output_k+out_offset_k);\n"
    " vstore4((FLOAT4)0,0,output_k+out_offset_k+seqLenPackKV);\n"
    " vstore4((FLOAT4)0,0,output_k+out_offset_k+2*seqLenPackKV);\n"
    " vstore4((FLOAT4)0,0,output_k+out_offset_k+3*seqLenPackKV);\n"
    " } else {\n"
    " const int dim_count_k=headDim-4*hd;\n"
    " FLOAT4 temp_0=load_dim4(input_k+in_offset_kv,dim_count_k);\n"
    " FLOAT4 temp_1=(sl*4+1 >= seqLenKV) ? (FLOAT4)0 : "
    "load_dim4(input_k+in_offset_kv+headNum*headDim/group,dim_count_k);\n"
    " FLOAT4 temp_2=(sl*4+2 >= seqLenKV) ? (FLOAT4)0 : "
    "load_dim4(input_k+in_offset_kv+2*headNum*headDim/group,dim_count_k);\n"
    " FLOAT4 temp_3=(sl*4+3 >= seqLenKV) ? (FLOAT4)0 : "
    "load_dim4(input_k+in_offset_kv+3*headNum*headDim/group,dim_count_k);\n"
    " #ifdef HEADDIM_LEAVE\n"
    " DEAL_INNER_HEADDIM_NOT_ALIGN(headDim)\n"
    " #endif\n"
    " #ifdef SEQLEN_LEAVE\n"
    " DEAL_OUTER_SEQLEN_NOT_ALIGN(seqLenKV)\n"
    " #endif\n"
    " FLOAT4 key0=(FLOAT4)(temp_0.s0,temp_1.s0,temp_2.s0,temp_3.s0);\n"
    " FLOAT4 key1=(FLOAT4)(temp_0.s1,temp_1.s1,temp_2.s1,temp_3.s1);\n"
    " FLOAT4 key2=(FLOAT4)(temp_0.s2,temp_1.s2,temp_2.s2,temp_3.s2);\n"
    " FLOAT4 key3=(FLOAT4)(temp_0.s3,temp_1.s3,temp_2.s3,temp_3.s3);\n"
    " vstore4(key0,0,output_k+out_offset_k);\n"
    " vstore4(key1,0,output_k+out_offset_k+seqLenPackKV);\n"
    " vstore4(key2,0,output_k+out_offset_k+2*seqLenPackKV);\n"
    " vstore4(key3,0,output_k+out_offset_k+3*seqLenPackKV);\n"
    " \n"
    " // pastK. output_k above may write all four dim rows because headDimPackQK pads them,but\n"
    " // past_k is packed to headDim with the kv heads back to back: a tail group writing four rows\n"
    " // there lands on the next head's leading rows.\n"
    " #ifdef SAVE_KV\n"
    " vstore4(key0,0,past_k+past_offset_k);\n"
    " if(dim_count_k>1) {\n"
    " vstore4(key1,0,past_k+past_offset_k+maxLenKV);\n"
    " }\n"
    " if(dim_count_k>2) {\n"
    " vstore4(key2,0,past_k+past_offset_k+2*maxLenKV);\n"
    " }\n"
    " if(dim_count_k>3) {\n"
    " vstore4(key3,0,past_k+past_offset_k+3*maxLenKV);\n"
    " }\n"
    " #endif\n"
    " }\n"
    " \n"
    " }\n"
    " \n"
    " if(sl*4<seqLenPackKV && hd*4<headDimPackV) {\n"
    " const int out_offset_v=(((b*headNum/group+hn)*seqLenPackKV+sl*4)*headDimPackV+hd*4);\n"
    " if(sl*4 >= seqLenKV || hd*4 >= headDim) {\n"
    " vstore4((FLOAT4)0,0,output_v+out_offset_v);\n"
    " vstore4((FLOAT4)0,0,output_v+out_offset_v+headDimPackV);\n"
    " vstore4((FLOAT4)0,0,output_v+out_offset_v+2*headDimPackV);\n"
    " vstore4((FLOAT4)0,0,output_v+out_offset_v+3*headDimPackV);\n"
    " } else {\n"
    " const int dim_count_v=headDim-4*hd;\n"
    " #ifdef VALUE_C4\n"
    " const int value_seq_storage=batch*seqLenKV;\n"
    " const int value_channel=hn*headDim+4*hd;\n"
    " const int value_token=b*seqLenKV+sl*4;\n"
    " FLOAT4 temp_0=load_c4_value4(input_v,value_seq_storage,value_token,value_channel,4*hd,headDim);\n"
    " FLOAT4 temp_1=(sl*4+1 >= seqLenKV) ? (FLOAT4)0 :\n"
    " load_c4_value4(input_v,value_seq_storage,value_token+1,value_channel,4*hd,headDim);\n"
    " FLOAT4 temp_2=(sl*4+2 >= seqLenKV) ? (FLOAT4)0 :\n"
    " load_c4_value4(input_v,value_seq_storage,value_token+2,value_channel,4*hd,headDim);\n"
    " FLOAT4 temp_3=(sl*4+3 >= seqLenKV) ? (FLOAT4)0 :\n"
    " load_c4_value4(input_v,value_seq_storage,value_token+3,value_channel,4*hd,headDim);\n"
    " #else\n"
    " FLOAT4 temp_0=load_dim4(input_v+in_offset_kv,dim_count_v);\n"
    " FLOAT4 temp_1=(sl*4+1 >= seqLenKV) ? (FLOAT4)0 : "
    "load_dim4(input_v+in_offset_kv+headNum*headDim/group,dim_count_v);\n"
    " FLOAT4 temp_2=(sl*4+2 >= seqLenKV) ? (FLOAT4)0 : "
    "load_dim4(input_v+in_offset_kv+2*headNum*headDim/group,dim_count_v);\n"
    " FLOAT4 temp_3=(sl*4+3 >= seqLenKV) ? (FLOAT4)0 : "
    "load_dim4(input_v+in_offset_kv+3*headNum*headDim/group,dim_count_v);\n"
    " #endif\n"
    " #ifdef HEADDIM_LEAVE\n"
    " DEAL_INNER_HEADDIM_NOT_ALIGN(headDim)\n"
    " #endif\n"
    " #ifdef SEQLEN_LEAVE\n"
    " DEAL_OUTER_SEQLEN_NOT_ALIGN(seqLenKV)\n"
    " #endif\n"
    " vstore4(temp_0,0,output_v+out_offset_v);\n"
    " vstore4(temp_1,0,output_v+out_offset_v+headDimPackV);\n"
    " vstore4(temp_2,0,output_v+out_offset_v+2*headDimPackV);\n"
    " vstore4(temp_3,0,output_v+out_offset_v+3*headDimPackV);\n"
    " \n"
    " // pastV. output_v above may write four dims because headDimPackV pads them,but past_v is\n"
    " // packed to headDim with the tokens back to back: a tail group writing four dims there lands\n"
    " // on the next token's leading dims.\n"
    " #ifdef SAVE_KV\n"
    " if(dim_count_v >= 4) {\n"
    " vstore4(temp_0,0,past_v+past_offset_v);\n"
    " vstore4(temp_1,0,past_v+past_offset_v+headDim);\n"
    " vstore4(temp_2,0,past_v+past_offset_v+2*headDim);\n"
    " vstore4(temp_3,0,past_v+past_offset_v+3*headDim);\n"
    " } else {\n"
    " store_scalar4(past_v,past_offset_v,temp_0,dim_count_v);\n"
    " store_scalar4(past_v,past_offset_v+headDim,temp_1,dim_count_v);\n"
    " store_scalar4(past_v,past_offset_v+2*headDim,temp_2,dim_count_v);\n"
    " store_scalar4(past_v,past_offset_v+3*headDim,temp_3,dim_count_v);\n"
    " }\n"
    " #endif\n"
    " }\n"
    " \n"
    " }\n"
    "}\n"
    "#ifndef MASK_DTYPE\n"
    "#define MASK_DTYPE FLOAT\n"
    "#define MASK_DTYPE4 FLOAT4\n"
    "#endif\n"
    "__kernel void rearrange_mask(GLOBAL_SIZE_3_DIMS\n"
    " __global const MASK_DTYPE *input_mask,// [batch,1,seqLenQ,seqLenKV,4]\n"
    " __global MASK_DTYPE *output_mask,// [batch,ROUND_UP(seqLenQ,mTileQ),ROUND_UP(seqLenKV,mTileKV)]\n"
    " const int4 shape // [seqLenQ,seqLenKV,mTileQ,mTileKV]\n"
    ") {\n"
    " const int sl=get_global_id(0); // seqLen_4\n"
    " const int sl_kv=get_global_id(1); // seqLenKV_4\n"
    " const int b=get_global_id(2); // Batch\n"
    " DEAL_NON_UNIFORM_DIM3(sl,sl_kv,b);\n"
    " \n"
    " const int seq_len_pack=((shape.x+shape.z-1)/shape.z)*shape.z;\n"
    " const int seq_len_kv_pack=((shape.y+shape.w-1)/shape.w)*shape.w;\n"
    " int in_offset=((b*shape.x+sl*4)*shape.y+sl_kv*4);\n"
    " int out_offset=(b*seq_len_pack+sl*4)*seq_len_kv_pack+sl_kv*4;\n"
    " if(sl*4 >= shape.x || sl_kv*4 >= shape.y) {\n"
    " vstore4((MASK_DTYPE4)0,0,output_mask+out_offset);\n"
    " vstore4((MASK_DTYPE4)0,0,output_mask+out_offset+seq_len_kv_pack);\n"
    " vstore4((MASK_DTYPE4)0,0,output_mask+out_offset+seq_len_kv_pack*2);\n"
    " vstore4((MASK_DTYPE4)0,0,output_mask+out_offset+seq_len_kv_pack*3);\n"
    " } else {\n"
    " int y_down_align4=(shape.y/4*4);\n"
    " MASK_DTYPE4 temp_0,temp_1,temp_2,temp_3;\n"
    " \n"
    " if(sl_kv*4<y_down_align4) {\n"
    " temp_0=vload4(0,input_mask+in_offset);\n"
    " temp_1=(sl*4+1 >= shape.x) ? (MASK_DTYPE4)0 : vload4(0,input_mask+in_offset+shape.y);\n"
    " temp_2=(sl*4+2 >= shape.x) ? (MASK_DTYPE4)0 : vload4(0,input_mask+in_offset+shape.y*2);\n"
    " temp_3=(sl*4+3 >= shape.x) ? (MASK_DTYPE4)0 : vload4(0,input_mask+in_offset+shape.y*3);\n"
    " } else if(sl_kv*4+1 == shape.y){\n"
    " temp_0=(MASK_DTYPE4)(input_mask[in_offset],0,0,0);\n"
    " temp_1=(sl*4+1 >= shape.x) ? (MASK_DTYPE4)0 : "
    "(MASK_DTYPE4)(input_mask[in_offset+shape.y],0,0,0);//vload4(0,input_mask+in_offset+shape.y);\n"
    " temp_2=(sl*4+2 >= shape.x) ? (MASK_DTYPE4)0 : "
    "(MASK_DTYPE4)(input_mask[in_offset+shape.y*2],0,0,0);//vload4(0,input_mask+in_offset+shape.y*2);\n"
    " temp_3=(sl*4+3 >= shape.x) ? (MASK_DTYPE4)0 : "
    "(MASK_DTYPE4)(input_mask[in_offset+shape.y*3],0,0,0);//vload4(0,input_mask+in_offset+shape.y*3);\n"
    " } else if(sl_kv*4+2 == shape.y){\n"
    " temp_0=(MASK_DTYPE4)(input_mask[in_offset],input_mask[in_offset+1],0,0);\n"
    " temp_1=(sl*4+1 >= shape.x) ? (MASK_DTYPE4)0 : "
    "(FLOAT4)(input_mask[in_offset+shape.y],input_mask[in_offset+shape.y+1],0,0);//"
    "vload4(0,input_mask+in_offset+shape.y);\n"
    " temp_2=(sl*4+2 >= shape.x) ? (MASK_DTYPE4)0 : "
    "(MASK_DTYPE4)(input_mask[in_offset+shape.y*2],input_mask[in_offset+shape.y*2+1],0,0);//"
    "vload4(0,input_mask+in_offset+shape.y*2);\n"
    " temp_3=(sl*4+3 >= shape.x) ? (MASK_DTYPE4)0 : "
    "(MASK_DTYPE4)(input_mask[in_offset+shape.y*3],input_mask[in_offset+shape.y*3+1],0,0);//"
    "vload4(0,input_mask+in_offset+shape.y*3);\n"
    " } else if(sl_kv*4+3 == shape.y){\n"
    " temp_0=(MASK_DTYPE4)(input_mask[in_offset],input_mask[in_offset+1],input_mask[in_offset+2],0);\n"
    " temp_1=(sl*4+1 >= shape.x) ? (MASK_DTYPE4)0 : "
    "(MASK_DTYPE4)(input_mask[in_offset+shape.y],input_mask[in_offset+shape.y+1],input_mask[in_offset+shape.y+2],0);//"
    "vload4(0,input_mask+in_offset+shape.y);\n"
    " temp_2=(sl*4+2 >= shape.x) ? (MASK_DTYPE4)0 : "
    "(MASK_DTYPE4)(input_mask[in_offset+shape.y*2],input_mask[in_offset+shape.y*2+1],input_mask[in_offset+shape.y*2+2],"
    "0);//vload4(0,input_mask+in_offset+shape.y*2);\n"
    " temp_3=(sl*4+3 >= shape.x) ? (MASK_DTYPE4)0 : "
    "(MASK_DTYPE4)(input_mask[in_offset+shape.y*3],input_mask[in_offset+shape.y*3+1],input_mask[in_offset+shape.y*3+2],"
    "0);//vload4(0,input_mask+in_offset+shape.y*3);\n"
    " }\n"
    " vstore4(temp_0,0,output_mask+out_offset);\n"
    " vstore4(temp_1,0,output_mask+out_offset+seq_len_kv_pack);\n"
    " vstore4(temp_2,0,output_mask+out_offset+2*seq_len_kv_pack);\n"
    " vstore4(temp_3,0,output_mask+out_offset+3*seq_len_kv_pack);\n"
    " }\n"
    "}\n"
    "__kernel void qkv_transpose_output(GLOBAL_SIZE_3_DIMS\n"
    " __global const FLOAT *input,// [Batch*mNumHead,ROUND_UP(mHeadDim,mTileHDN),ROUND_UP(seqLen,mTileQ)]\n"
    " __global FLOAT *output,// [Batch,seqLen/4,mNumHead， mHeadDim,4] (or NC4HW4 when ATTENTION_C4)\n"
    " __private const int tile_q,\n"
    " __private const int tile_hdn,\n"
    " __private const int seq_len,\n"
    " __private const int head_num,\n"
    " __private const int head_dim,\n"
    " __private const int batch\n"
    ") {\n"
    " const int sl=get_global_id(0); // seqLen_4\n"
    " const int hd=get_global_id(1); // mHeadDim_4\n"
    " const int z=get_global_id(2); // Batch*mNumHead\n"
    " DEAL_NON_UNIFORM_DIM3(sl,hd,z);\n"
    " const int b=z/head_num;\n"
    " const int hn=z % head_num;\n"
    " const int seq_len_pack=((seq_len+tile_q-1)/tile_q)*tile_q;\n"
    " const int head_dim_pack=((head_dim+tile_hdn-1)/tile_hdn)*tile_hdn;\n"
    " const int offset_inp=((b*head_num+hn)*head_dim_pack+4*hd)*seq_len_pack+4*sl;\n"
    " // Q\n"
    " FLOAT4 temp_0=vload4(0,input+offset_inp);\n"
    " FLOAT4 temp_1=vload4(0,input+offset_inp+seq_len_pack);\n"
    " FLOAT4 temp_2=vload4(0,input+offset_inp+2*seq_len_pack);\n"
    " FLOAT4 temp_3=vload4(0,input+offset_inp+3*seq_len_pack);\n"
    "#ifdef ATTENTION_C4\n"
    " // output is NC4HW4: [(head_num*head_dim)/4,batch*seq_len,4].\n"
    " const int channel=hn*head_dim+4*hd;\n"
    " const int channel_count=min(4,head_dim-4*hd);\n"
    " const int seq_storage=seq_len*batch;\n"
    " int token=b*seq_len+sl*4;\n"
    " store_attention_c4_4(output,(FLOAT4)(temp_0.s0,temp_1.s0,temp_2.s0,temp_3.s0),seq_storage,token,\n"
    " channel,channel_count);\n"
    " if(4*sl+1 >= seq_len) return;\n"
    " store_attention_c4_4(output,(FLOAT4)(temp_0.s1,temp_1.s1,temp_2.s1,temp_3.s1),seq_storage,++token,\n"
    " channel,channel_count);\n"
    " if(4*sl+2 >= seq_len) return;\n"
    " store_attention_c4_4(output,(FLOAT4)(temp_0.s2,temp_1.s2,temp_2.s2,temp_3.s2),seq_storage,++token,\n"
    " channel,channel_count);\n"
    " if(4*sl+3 >= seq_len) return;\n"
    " store_attention_c4_4(output,(FLOAT4)(temp_0.s3,temp_1.s3,temp_2.s3,temp_3.s3),seq_storage,++token,\n"
    " channel,channel_count);\n"
    "#else\n"
    " const int offset_out=(((b*seq_len+sl*4)*head_num+hn)*head_dim+4*hd);\n"
    " // A head_dim that is not a multiple of 4 leaves the last dim group partial,and heads sit back\n"
    " // to back in the output: a full vstore4 there overwrites the next head's leading dims,and runs\n"
    " // off the buffer on the last head. The ATTENTION_C4 branch above already clamps with\n"
    " // channel_count; do the same here. Only the tail column takes the else,and the branch is\n"
    " // uniform across it,so the aligned case keeps its vector stores.\n"
    " const int dim_count=head_dim-4*hd;\n"
    " const FLOAT4 out_0=(FLOAT4)(temp_0.s0,temp_1.s0,temp_2.s0,temp_3.s0);\n"
    " const FLOAT4 out_1=(FLOAT4)(temp_0.s1,temp_1.s1,temp_2.s1,temp_3.s1);\n"
    " const FLOAT4 out_2=(FLOAT4)(temp_0.s2,temp_1.s2,temp_2.s2,temp_3.s2);\n"
    " const FLOAT4 out_3=(FLOAT4)(temp_0.s3,temp_1.s3,temp_2.s3,temp_3.s3);\n"
    " if(dim_count >= 4) {\n"
    " vstore4(out_0,0,output+offset_out);\n"
    " if(4*sl+1 >= seq_len) return;\n"
    " vstore4(out_1,0,output+offset_out+head_num*head_dim);\n"
    " if(4*sl+2 >= seq_len) return;\n"
    " vstore4(out_2,0,output+offset_out+2*head_num*head_dim);\n"
    " if(4*sl+3 >= seq_len) return;\n"
    " vstore4(out_3,0,output+offset_out+3*head_num*head_dim);\n"
    " } else {\n"
    " store_scalar4(output,offset_out,out_0,dim_count);\n"
    " if(4*sl+1 >= seq_len) return;\n"
    " store_scalar4(output,offset_out+head_num*head_dim,out_1,dim_count);\n"
    " if(4*sl+2 >= seq_len) return;\n"
    " store_scalar4(output,offset_out+2*head_num*head_dim,out_2,dim_count);\n"
    " if(4*sl+3 >= seq_len) return;\n"
    " store_scalar4(output,offset_out+3*head_num*head_dim,out_3,dim_count);\n"
    " }\n"
    "#endif\n"
    "}\n";
#endif
} // namespace MNN
