#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* buffer_convert_filter_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "#define GLOBAL_SIZE_2_DIMS __private const int global_size_dim0,__private const int global_size_dim1,\n"
    "#define DEAL_NON_UNIFORM_DIM2(input1, input2) "
    " if (input1 >= global_size_dim0 || input2 >= global_size_dim1) { "
    " return; "
    " }\n"
    "#ifdef MNN_SUPPORT_FP16\n"
    "#define MNN_LOAD_FLOAT(ptr,idx) vload_half((idx),(ptr))\n"
    "#else\n"
    "#define MNN_LOAD_FLOAT(ptr,idx) *((ptr)+(idx))\n"
    "#endif\n"
    "// convert kernel : from buffer(oihw) to image(ic,oc/4,h,w,oc4)\n"
    "__kernel void conv2d_filter_buffer_to_nc4hw4_buffer(GLOBAL_SIZE_2_DIMS\n"
    " __global const FLOAT *input_ptr,\n"
    " __private const int output_channel,\n"
    " __private const int2 kernel_shape,\n"
    " __private const int ic_h_w_size,\n"
    " __private const int height_width_size,\n"
    " __global FLOAT *output) {\n"
    " int image_width_idx=get_global_id(0); // ic\n"
    " int image_height_idx=get_global_id(1); // oc/4 h w\n"
    " DEAL_NON_UNIFORM_DIM2(image_width_idx,image_height_idx);\n"
    " const int input_channel_4_idx=image_width_idx;\n"
    " const int output_channel_4_idx=(image_height_idx/height_width_size)*4;\n"
    " const int height_width_idx=image_height_idx % height_width_size;\n"
    " const int buffer_height_idx=height_width_idx/kernel_shape.y;\n"
    " const int buffer_width_idx=height_width_idx % kernel_shape.y;\n"
    " const int buffer_offset=output_channel_4_idx*ic_h_w_size+input_channel_4_idx*height_width_size +\n"
    " buffer_height_idx*kernel_shape.y+buffer_width_idx;\n"
    " FLOAT4 output_values=0;\n"
    " if (output_channel_4_idx<output_channel) {\n"
    " const int remain_channel=output_channel-output_channel_4_idx;\n"
    " if (remain_channel >= 4) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset=mad24(1,ic_h_w_size,offset);\n"
    " output_values.y=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset += ic_h_w_size;\n"
    " output_values.z=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset += ic_h_w_size;\n"
    " output_values.w=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " } else if (remain_channel == 3) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset=mad24(1,ic_h_w_size,offset);\n"
    " output_values.y=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset += ic_h_w_size;\n"
    " output_values.z=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " } else if (remain_channel == 2) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset=mad24(1,ic_h_w_size,offset);\n"
    " output_values.y=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " } else if (remain_channel == 1) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " }\n"
    " }\n"
    " const int out_offset=(image_width_idx*height_width_size*((output_channel+3)/4)+image_height_idx)*4;\n"
    " vstore4(output_values,0,output+out_offset);\n"
    "}\n"
    "// convert kernel : from buffer(oihw) to image(oc/4 h w ,ic oc4)\n"
    "__kernel void conv2d_filter_buffer_to_nc4hw4_buffer_floatin(GLOBAL_SIZE_2_DIMS\n"
    " __global const float *input_ptr,\n"
    " __private const int output_channel,\n"
    " __private const int2 kernel_shape,\n"
    " __private const int ic_h_w_size,\n"
    " __private const int height_width_size,\n"
    " __global FLOAT *output) {\n"
    " int image_width_idx=get_global_id(0); // ic\n"
    " int image_height_idx=get_global_id(1); // oc/4 h w\n"
    " DEAL_NON_UNIFORM_DIM2(image_width_idx,image_height_idx);\n"
    " const int input_channel_4_idx=image_width_idx;\n"
    " const int output_channel_4_idx=(image_height_idx/height_width_size)*4;\n"
    " const int height_width_idx=image_height_idx % height_width_size;\n"
    " const int buffer_height_idx=height_width_idx/kernel_shape.y;\n"
    " const int buffer_width_idx=height_width_idx % kernel_shape.y;\n"
    " const int buffer_offset=output_channel_4_idx*ic_h_w_size+input_channel_4_idx*height_width_size +\n"
    " buffer_height_idx*kernel_shape.y+buffer_width_idx;\n"
    " FLOAT4 output_values=0;\n"
    " if (output_channel_4_idx<output_channel) {\n"
    " const int remain_channel=output_channel-output_channel_4_idx;\n"
    " if (remain_channel >= 4) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)(*(input_ptr+offset));\n"
    " offset=mad24(1,ic_h_w_size,offset);\n"
    " output_values.y=(FLOAT)(*(input_ptr+offset));\n"
    " offset += ic_h_w_size;\n"
    " output_values.z=(FLOAT)(*(input_ptr+offset));\n"
    " offset += ic_h_w_size;\n"
    " output_values.w=(FLOAT)(*(input_ptr+offset));\n"
    " } else if (remain_channel == 3) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)(*(input_ptr+offset));\n"
    " offset=mad24(1,ic_h_w_size,offset);\n"
    " output_values.y=(FLOAT)(*(input_ptr+offset));\n"
    " offset += ic_h_w_size;\n"
    " output_values.z=(FLOAT)(*(input_ptr+offset));\n"
    " } else if (remain_channel == 2) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)(*(input_ptr+offset));\n"
    " offset=mad24(1,ic_h_w_size,offset);\n"
    " output_values.y=(FLOAT)(*(input_ptr+offset));\n"
    " } else if (remain_channel == 1) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)(*(input_ptr+offset));\n"
    " }\n"
    " }\n"
    " const int out_offset=(image_width_idx*height_width_size*((output_channel+3)/4)+image_height_idx)*4;\n"
    " vstore4(output_values,0,output+out_offset);\n"
    "}\n"
    "// convert kernel from buffer(mihw) to image(ic/4,ic4 h w m)\n"
    "// but now dw only support m == 1\n"
    "__kernel void dw_filter_buffer_to_nc4hw4_buffer(GLOBAL_SIZE_2_DIMS\n"
    " __global const FLOAT *input_ptr,\n"
    " __private const int4 kernel_shape,//[1,Cout,fh,fw]\n"
    " __private const int height_width_size,\n"
    " __global FLOAT *output) {\n"
    " const int image_width_idx=get_global_id(0);//fh*fw\n"
    " const int image_height_idx=get_global_id(1);//UP_DIV(Cout,4)\n"
    " DEAL_NON_UNIFORM_DIM2(image_width_idx,image_height_idx);\n"
    " FLOAT4 output_values=0;\n"
    " if (kernel_shape.x == 1) {\n"
    " const int input_channel_4_idx=image_height_idx*4;\n"
    " const int buffer_height_idx=image_width_idx/kernel_shape.w;\n"
    " const int buffer_width_idx=image_width_idx % kernel_shape.w;\n"
    " const int buffer_offset =\n"
    " mad24(mad24(input_channel_4_idx,kernel_shape.z,buffer_height_idx),kernel_shape.w,buffer_width_idx);\n"
    " //input [1,Cout,fh,fw]\n"
    " //index:[0,input_channel_4_idx,buffer_height_idx,buffer_width_idx]\n"
    " const int remain_channel=kernel_shape.y-input_channel_4_idx;\n"
    " if (input_channel_4_idx<kernel_shape.y) {\n"
    " if (remain_channel >= 4) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset += height_width_size;\n"
    " output_values.y=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset += height_width_size;\n"
    " output_values.z=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset += height_width_size;\n"
    " output_values.w=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " } else if (remain_channel == 3) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset += height_width_size;\n"
    " output_values.y=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset += height_width_size;\n"
    " output_values.z=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " } else if (remain_channel == 2) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " offset += height_width_size;\n"
    " output_values.y=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " } else if (remain_channel == 1) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)MNN_LOAD_FLOAT(input_ptr,offset);\n"
    " }\n"
    " }\n"
    " }\n"
    " //output NC4HW4 [1,fw*fh,1,Cout/4]x oc4\n"
    " //index: [0,image_width_idx,0,image_height_idx]\n"
    " const int out_offset=(image_width_idx*((kernel_shape.y+3)/4)+image_height_idx)*4;\n"
    " vstore4(output_values,0,output+out_offset);\n"
    "}\n"
    "__kernel void dw_filter_buffer_to_nc4hw4_buffer_floatin(GLOBAL_SIZE_2_DIMS\n"
    " __global const float *input_ptr,\n"
    " __private const int4 kernel_shape,//[1,Cout,fh,fw]\n"
    " __private const int height_width_size,\n"
    " __global FLOAT *output) {\n"
    " const int image_width_idx=get_global_id(0);//fh*fw\n"
    " const int image_height_idx=get_global_id(1);//UP_DIV(Cout,4)\n"
    " DEAL_NON_UNIFORM_DIM2(image_width_idx,image_height_idx);\n"
    " FLOAT4 output_values=0;\n"
    " if (kernel_shape.x == 1) {\n"
    " const int input_channel_4_idx=image_height_idx*4;\n"
    " const int buffer_height_idx=image_width_idx/kernel_shape.w;\n"
    " const int buffer_width_idx=image_width_idx % kernel_shape.w;\n"
    " const int buffer_offset =\n"
    " mad24(mad24(input_channel_4_idx,kernel_shape.z,buffer_height_idx),kernel_shape.w,buffer_width_idx);\n"
    " //input [1,Cout,fh,fw]\n"
    " //index:[0,input_channel_4_idx,buffer_height_idx,buffer_width_idx]\n"
    " const int remain_channel=kernel_shape.y-input_channel_4_idx;\n"
    " if (input_channel_4_idx<kernel_shape.y) {\n"
    " if (remain_channel >= 4) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)(*(input_ptr+offset));\n"
    " offset += height_width_size;\n"
    " output_values.y=(FLOAT)(*(input_ptr+offset));\n"
    " offset += height_width_size;\n"
    " output_values.z=(FLOAT)(*(input_ptr+offset));\n"
    " offset += height_width_size;\n"
    " output_values.w=(FLOAT)(*(input_ptr+offset));\n"
    " } else if (remain_channel == 3) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)(*(input_ptr+offset));\n"
    " offset += height_width_size;\n"
    " output_values.y=(FLOAT)(*(input_ptr+offset));\n"
    " offset += height_width_size;\n"
    " output_values.z=(FLOAT)(*(input_ptr+offset));\n"
    " } else if (remain_channel == 2) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)(*(input_ptr+offset));\n"
    " offset += height_width_size;\n"
    " output_values.y=(FLOAT)(*(input_ptr+offset));\n"
    " } else if (remain_channel == 1) {\n"
    " int offset=buffer_offset;\n"
    " output_values.x=(FLOAT)(*(input_ptr+offset));\n"
    " }\n"
    " }\n"
    " }\n"
    " //output NC4HW4 [1,fw*fh,1,Cout/4]x oc4\n"
    " //index: [0,image_width_idx,0,image_height_idx]\n"
    " const int out_offset=(image_width_idx*((kernel_shape.y+3)/4)+image_height_idx)*4;\n"
    " vstore4(output_values,0,output+out_offset);\n"
    "}\n";
#endif
} // namespace MNN
