#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* fused_proj_gemv_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "// Decode-time GEMV for a whole FusedLinear group: 2-4 conv1x1 projections that\n"
    "// share one input activation,computed in a single dispatch.\n"
    "//\n"
    "// Two flavours,both int4 weights (QUANT_BIT 4),no channel leaves:\n"
    "// FUSE_SILU_MUL: NUM_CONV == 2,gate/up. One workgroup owns the same output\n"
    "// tile of both convs,so the MUL_SILU epilogue happens in\n"
    "// registers and neither projection is ever written to DRAM.\n"
    "// otherwise: NUM_CONV in 2..4 (q/k/v[/w]) writing their own outputs. The\n"
    "// workgroup's tile index selects the member,so the group is\n"
    "// one dispatch instead of one per member.\n"
    "//\n"
    "// Mirrors gemv_conv_c8_buf (gemv_conv1x1_buf.cl): 8 output channels per\n"
    "// workgroup,K split across WGS work-items,tree reduce in local memory. The\n"
    "// per-member scale/bias/coef stay separate because the dequant scale buffer is\n"
    "// quant-block-major,so members cannot share one buffer.\n"
    "__constant sampler_t SAMPLER=CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;\n"
    "#define GLOBAL_SIZE_DIM_2 __private int global_size_dim0,__private int global_size_dim1,\n"
    "#define UCHAR4_TO_CHAR8(b, scale, offset) "
    " wei.s0 = CONVERT_FLOAT((b.s0 >> 4)); "
    " wei.s1 = CONVERT_FLOAT((b.s0 & 15)); "
    " wei.s2 = CONVERT_FLOAT((b.s1 >> 4)); "
    " wei.s3 = CONVERT_FLOAT((b.s1 & 15)); "
    " wei.s4 = CONVERT_FLOAT((b.s2 >> 4)); "
    " wei.s5 = CONVERT_FLOAT((b.s2 & 15)); "
    " wei.s6 = CONVERT_FLOAT((b.s3 >> 4)); "
    " wei.s7 = CONVERT_FLOAT((b.s3 & 15)); "
    " wei=wei*scale+offset;\n"
    "#ifdef USE_IMAGE\n"
    "#define FP_WEIGHT_ARG(name) __read_only image2d_t name\n"
    "#define FP_LOAD_WEIGHT(w,j,tile) as_uchar16(read_imagei(w,SAMPLER,(int2)((j),(tile))))\n"
    "#else\n"
    "#define FP_WEIGHT_ARG(name) __global const uchar* name\n"
    "#define FP_LOAD_WEIGHT(w,j,tile) vload16((j),w+(tile)*srcChannelC4*16)\n"
    "#endif\n"
    "// Dequant scale/offset of the 8 output channels at `oc8` for the quant block\n"
    "// holding input channel k4. Layout is block-major: (block*dstC4*4)+oc.\n"
    "#ifdef ASYMMETRIC\n"
    "#define FP_LOAD_SCALE(so, dstC4, cf, oc8, k4, scale, offset) "
    " { "
    " COMPUTE_FLOAT16 scaleOffset = CONVERT_COMPUTE_FLOAT16( "
    " convert_float16(vload16(0, so + (oc8) * 2 + ((k4) / blockDim) * (dstC4) * 8)) / (cf)); "
    " scale = scaleOffset.s02468ace; "
    " offset = scaleOffset.s13579bdf; "
    " }\n"
    "#else\n"
    "#define FP_LOAD_SCALE(so, dstC4, cf, oc8, k4, scale, offset) "
    " { "
    " scale = "
    " CONVERT_COMPUTE_FLOAT8(convert_float8(vload8(0, so + (oc8) + ((k4) / blockDim) * (dstC4) * 4)) / (cf)); "
    " offset = (COMPUTE_FLOAT8)(-8) * scale; "
    " }\n"
    "#endif\n"
    "// This work-item's slice of the dot products for output tile `tile` of one member.\n"
    "#define FP_ACCUM(w, so, dstC4, cf, tile, acc) "
    " { "
    " const int oc8_ = (tile) << 3; "
    " for (int j = lid; j < loop; j += WGS) { "
    " const int k4 = j << 2; "
    " COMPUTE_FLOAT8 scale, offset; "
    " FP_LOAD_SCALE(so, dstC4, cf, oc8_, k4, scale, offset) "
    " COMPUTE_FLOAT8 wei; "
    " COMPUTE_FLOAT4 in = CONVERT_COMPUTE_FLOAT4(vload4(0, input + k4)); "
    " uchar16 wq = FP_LOAD_WEIGHT(w, j, tile); "
    " UCHAR4_TO_CHAR8(wq.s0123, scale, offset) "
    " acc = mad((COMPUTE_FLOAT8)in.s0, wei, acc); "
    " UCHAR4_TO_CHAR8(wq.s4567, scale, offset) "
    " acc = mad((COMPUTE_FLOAT8)in.s1, wei, acc); "
    " UCHAR4_TO_CHAR8(wq.s89ab, scale, offset) "
    " acc = mad((COMPUTE_FLOAT8)in.s2, wei, acc); "
    " UCHAR4_TO_CHAR8(wq.scdef, scale, offset) "
    " acc = mad((COMPUTE_FLOAT8)in.s3, wei, acc); "
    " } "
    " }\n"
    "// Tree reduce of the workgroup's partial sums. Every work-item leaves with the\n"
    "// total in `res`,and the trailing barrier lets the scratch be reused.\n"
    "#define FP_REDUCE(acc, res) "
    " { "
    " sum0[lid] = acc; "
    " barrier(CLK_LOCAL_MEM_FENCE); "
    " for (int i = WGS / 2; i > 0; i /= 2) { "
    " if (lid < i) { "
    " sum0[lid] = sum0[lid] + sum0[lid + i]; "
    " } "
    " barrier(CLK_LOCAL_MEM_FENCE); "
    " } "
    " res = sum0[0]; "
    " barrier(CLK_LOCAL_MEM_FENCE); "
    " }\n"
    "#if WGS >= 8\n"
    "__kernel void fused_proj_gemv_buf(GLOBAL_SIZE_DIM_2 __global const FLOAT* input,FP_WEIGHT_ARG(weight0),\n"
    " FP_WEIGHT_ARG(weight1),\n"
    "#if NUM_CONV>2\n"
    " FP_WEIGHT_ARG(weight2),\n"
    "#endif\n"
    "#if NUM_CONV>3\n"
    " FP_WEIGHT_ARG(weight3),\n"
    "#endif\n"
    " __global const FLOAT* scaleOffset0,__global const FLOAT* scaleOffset1,\n"
    "#if NUM_CONV>2\n"
    " __global const FLOAT* scaleOffset2,\n"
    "#endif\n"
    "#if NUM_CONV>3\n"
    " __global const FLOAT* scaleOffset3,\n"
    "#endif\n"
    " __global const FLOAT* bias0,__global const FLOAT* bias1,\n"
    "#if NUM_CONV>2\n"
    " __global const FLOAT* bias2,\n"
    "#endif\n"
    "#if NUM_CONV>3\n"
    " __global const FLOAT* bias3,\n"
    "#endif\n"
    " __global FLOAT* output0,\n"
    "#ifndef FUSE_SILU_MUL\n"
    " __global FLOAT* output1,\n"
    "#if NUM_CONV>2\n"
    " __global FLOAT* output2,\n"
    "#endif\n"
    "#if NUM_CONV>3\n"
    " __global FLOAT* output3,\n"
    "#endif\n"
    "#endif\n"
    " __private const int srcChannelC4,__private const int blockDim,\n"
    " __private const int4 dstChannelC4,__private const int4 ocTiles,\n"
    " __private const float4 coef) {\n"
    " const int lid=get_local_id(0);\n"
    " const int gid=get_global_id(1);\n"
    " const int loop=srcChannelC4;\n"
    " __local COMPUTE_FLOAT8 sum0[WGS];\n"
    "#ifdef FUSE_SILU_MUL\n"
    " // gate=convs[0](x),up=convs[1](x),out=up*silu(gate) — the two\n"
    " // members share this tile,so both stay in registers.\n"
    " COMPUTE_FLOAT8 accGate=0,accUp=0;\n"
    " FP_ACCUM(weight0,scaleOffset0,dstChannelC4.x,coef.x,gid,accGate)\n"
    " FP_ACCUM(weight1,scaleOffset1,dstChannelC4.y,coef.y,gid,accUp)\n"
    " COMPUTE_FLOAT8 resGate,resUp;\n"
    " FP_REDUCE(accGate,resGate)\n"
    " FP_REDUCE(accUp,resUp)\n"
    " if (lid == 0) {\n"
    " const int oc8=gid << 3;\n"
    " float8 gate=convert_float8(resGate+CONVERT_COMPUTE_FLOAT8(vload8(0,bias0+oc8)));\n"
    " float8 up=convert_float8(resUp+CONVERT_COMPUTE_FLOAT8(vload8(0,bias1+oc8)));\n"
    " // Same expression as BinaryBufExecution's MUL_SILU,so the fused and the\n"
    " // unfused graph agree bit for bit.\n"
    " float8 out=up*(gate*native_recip((float8)1+native_exp(-gate)));\n"
    " vstore8(CONVERT_FLOAT8(out),0,output0+oc8);\n"
    " }\n"
    "#else\n"
    " // One member per tile: peel the member index off the flat tile id. It is\n"
    " // workgroup-uniform,so the branches below never diverge.\n"
    " int tile=gid;\n"
    " int ci=0;\n"
    " if (tile >= ocTiles.x) {\n"
    " tile -= ocTiles.x;\n"
    " ci=1;\n"
    "#if NUM_CONV>2\n"
    " if (tile >= ocTiles.y) {\n"
    " tile -= ocTiles.y;\n"
    " ci=2;\n"
    "#if NUM_CONV>3\n"
    " if (tile >= ocTiles.z) {\n"
    " tile -= ocTiles.z;\n"
    " ci=3;\n"
    " }\n"
    "#endif\n"
    " }\n"
    "#endif\n"
    " }\n"
    " COMPUTE_FLOAT8 acc=0,res;\n"
    " if (ci == 0) {\n"
    " FP_ACCUM(weight0,scaleOffset0,dstChannelC4.x,coef.x,tile,acc)\n"
    " } else if (ci == 1) {\n"
    " FP_ACCUM(weight1,scaleOffset1,dstChannelC4.y,coef.y,tile,acc)\n"
    " }\n"
    "#if NUM_CONV>2\n"
    " else if (ci == 2) {\n"
    " FP_ACCUM(weight2,scaleOffset2,dstChannelC4.z,coef.z,tile,acc)\n"
    " }\n"
    "#endif\n"
    "#if NUM_CONV>3\n"
    " else {\n"
    " FP_ACCUM(weight3,scaleOffset3,dstChannelC4.w,coef.w,tile,acc)\n"
    " }\n"
    "#endif\n"
    " FP_REDUCE(acc,res)\n"
    " if (lid == 0) {\n"
    " const int oc8=tile << 3;\n"
    " if (ci == 0) {\n"
    " vstore8(CONVERT_FLOAT8(res+CONVERT_COMPUTE_FLOAT8(vload8(0,bias0+oc8))),0,output0+oc8);\n"
    " } else if (ci == 1) {\n"
    " vstore8(CONVERT_FLOAT8(res+CONVERT_COMPUTE_FLOAT8(vload8(0,bias1+oc8))),0,output1+oc8);\n"
    " }\n"
    "#if NUM_CONV>2\n"
    " else if (ci == 2) {\n"
    " vstore8(CONVERT_FLOAT8(res+CONVERT_COMPUTE_FLOAT8(vload8(0,bias2+oc8))),0,output2+oc8);\n"
    " }\n"
    "#endif\n"
    "#if NUM_CONV>3\n"
    " else {\n"
    " vstore8(CONVERT_FLOAT8(res+CONVERT_COMPUTE_FLOAT8(vload8(0,bias3+oc8))),0,output3+oc8);\n"
    " }\n"
    "#endif\n"
    " }\n"
    "#endif\n"
    "}\n"
    "#endif\n";
#endif
} // namespace MNN
