#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* gated_rms_norm_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "// OpType_GatedRMSNorm: out=(RMSNorm(x)*gamma+beta)*silu(z).\n"
    "//\n"
    "// Layout note (the op absorbs the C4 repacks the exported graph used to carry):\n"
    "// x is [outside,inside] -> FLOAT4 index (c/4)*outside+h,lane c%4\n"
    "// z/out are [batch,heads*inside] -> flat channel f=head*inside+c,\n"
    "// FLOAT4 index (f/4)*batch+b,lane f%4\n"
    "// with outside=batch*heads and h=b*heads+head.\n"
    "//\n"
    "// When inside % 4 == 0 the x lane and the z/out lane coincide,so the whole row\n"
    "// is vector work (gated_rms_norm_c4_buf). Otherwise the two sides disagree on\n"
    "// the lane and the addressing has to go element-wise (gated_rms_norm_buf).\n"
    "#define SILU(g) ((g)/(1.0f+exp(-(g))))\n"
    "// Zero the padding lanes of the last channel unit so they cannot enter the sum.\n"
    "#define MASK_C4_TAIL(value, index, channel_unit, remain) "
    " do { "
    " if ((remain) != 0 && (index) == (channel_unit) - 1) { "
    " if ((remain) < 4) "
    " (value).w = 0.0f; "
    " if ((remain) < 3) "
    " (value).z = 0.0f; "
    " if ((remain) < 2) "
    " (value).y = 0.0f; "
    " } "
    " } while (0)\n"
    "// Sum of squares of row `row` of x,reduced across the workgroup.\n"
    "#define REDUCE_SQUARE_SUM(sum_local, lid, x, row, outside, channelUnit, channelRemain, acc) "
    " do { "
    " float4 in_sum = (float4)0; "
    " for (int index = (lid); index < (channelUnit); index += LOCAL_SIZE) { "
    " float4 in = convert_float4((x)[index * (outside) + (row)]); "
    " MASK_C4_TAIL(in, index, channelUnit, channelRemain); "
    " in_sum += in * in; "
    " } "
    " (sum_local)[lid] = in_sum; "
    " barrier(CLK_LOCAL_MEM_FENCE); "
    " for (int i = LOCAL_SIZE / 2; i > 0; i /= 2) { "
    " if ((lid) < i) { "
    " (sum_local)[lid] = (sum_local)[lid] + (sum_local)[(lid) + i]; "
    " } "
    " barrier(CLK_LOCAL_MEM_FENCE); "
    " } "
    " (acc) = (sum_local)[0].x + (sum_local)[0].y + (sum_local)[0].z + (sum_local)[0].w; "
    " } while (0)\n"
    "// inside % 4 == 0: x,z and out share the lane,so everything stays vectorised.\n"
    "__kernel void gated_rms_norm_c4_buf(__private int global_dim0,__private int global_dim1,__global const FLOAT4* "
    "x,\n"
    " __global const FLOAT4* z,__global FLOAT4* output,\n"
    "#ifdef GAMMA_BETA\n"
    " __global const FLOAT4* gamma,__global const FLOAT4* beta,\n"
    "#endif\n"
    " __private const int inside,__private const int heads,__private const int batch,\n"
    " __private const float epsilon) {\n"
    " int2 pos=(int2)(get_global_id(0),get_global_id(1));\n"
    " float4 local sum_mnn[LOCAL_SIZE];\n"
    " if (pos.x >= global_dim0 || pos.y >= global_dim1) {\n"
    " return;\n"
    " }\n"
    " const int lid=get_local_id(0);\n"
    " const int outside=global_dim1;\n"
    " const int channelUnit=inside >> 2;\n"
    " float square_sum_all;\n"
    " REDUCE_SQUARE_SUM(sum_mnn,lid,x,pos.y,outside,channelUnit,0,square_sum_all);\n"
    " const float4 scale=(float4)1.0f/(float4)sqrt((float4)(square_sum_all/inside)+(float4)epsilon);\n"
    " const int b=pos.y/heads;\n"
    " const int head=pos.y-b*heads;\n"
    " // f=head*inside+c,and inside % 4 == 0,so the unit offset is exact.\n"
    " const int unitBase=(head*inside) >> 2;\n"
    " for (int index=lid; index<channelUnit; index += LOCAL_SIZE) {\n"
    " float4 in=convert_float4(x[index*outside+pos.y]);\n"
    "#ifdef GAMMA_BETA\n"
    " float4 out=in*scale*convert_float4(gamma[index])+convert_float4(beta[index]);\n"
    "#else\n"
    " float4 out=in*scale;\n"
    "#endif\n"
    " const int zIdx=(unitBase+index)*batch+b;\n"
    " float4 g=convert_float4(z[zIdx]);\n"
    " output[zIdx]=CONVERT_FLOAT4(out*SILU(g));\n"
    " }\n"
    "}\n"
    "// inside % 4 != 0: x carries per-row channel padding that z/out do not,so the\n"
    "// epilogue addresses both sides element-wise. Correctness path only.\n"
    "__kernel void gated_rms_norm_buf(__private int global_dim0,__private int global_dim1,__global const FLOAT* x,\n"
    " __global const FLOAT* z,__global FLOAT* output,\n"
    "#ifdef GAMMA_BETA\n"
    " __global const FLOAT* gamma,__global const FLOAT* beta,\n"
    "#endif\n"
    " __private const int inside,__private const int heads,__private const int batch,\n"
    " __private const float epsilon) {\n"
    " int2 pos=(int2)(get_global_id(0),get_global_id(1));\n"
    " float local sum_mnn[LOCAL_SIZE];\n"
    " if (pos.x >= global_dim0 || pos.y >= global_dim1) {\n"
    " return;\n"
    " }\n"
    " const int lid=get_local_id(0);\n"
    " const int outside=global_dim1;\n"
    " // x element index: unit c/4 of row pos.y,lane c%4. Scalar throughout,so\n"
    " // the padding lanes of the last unit are never touched.\n"
    " float acc=0.0f;\n"
    " for (int c=lid; c<inside; c += LOCAL_SIZE) {\n"
    " float in=(float)x[((c >> 2)*outside+pos.y)*4+(c & 3)];\n"
    " acc += in*in;\n"
    " }\n"
    " sum_mnn[lid]=acc;\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " for (int i=LOCAL_SIZE/2; i>0; i /= 2) {\n"
    " if (lid<i) {\n"
    " sum_mnn[lid]=sum_mnn[lid]+sum_mnn[lid+i];\n"
    " }\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " }\n"
    " const float scale=1.0f/sqrt(sum_mnn[0]/inside+epsilon);\n"
    " const int b=pos.y/heads;\n"
    " const int head=pos.y-b*heads;\n"
    " for (int c=lid; c<inside; c += LOCAL_SIZE) {\n"
    " const int xIdx=((c >> 2)*outside+pos.y)*4+(c & 3);\n"
    " float in=(float)x[xIdx];\n"
    "#ifdef GAMMA_BETA\n"
    " float out=in*scale*(float)gamma[c]+(float)beta[c];\n"
    "#else\n"
    " float out=in*scale;\n"
    "#endif\n"
    " const int f=head*inside+c;\n"
    " const int zIdx=((f >> 2)*batch+b)*4+(f & 3);\n"
    " float g=(float)z[zIdx];\n"
    " output[zIdx]=(FLOAT)(out*SILU(g));\n"
    " }\n"
    "}\n";
#endif
} // namespace MNN
