#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* gemm_conv1x1_int4_b8_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "#define GLOBAL_SIZE_DIM2 "
    " __private int global_size_dim0,__private int global_size_dim1,\n"
    "#define UNIFORM_BOUNDRY_CHECK(index0, index1) "
    " if(index0 >= global_size_dim0 || index1 >= global_size_dim1) { "
    " return; "
    " }\n"
    "__constant sampler_t SAMPLER=CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;\n"
    "#ifdef USE_IMAGE1D_INPUT\n"
    "#ifdef MNN_SUPPORT_FP16\n"
    "#define RI_F(i,coord) read_imageh(i,coord)\n"
    "#else\n"
    "#define RI_F(i,coord) read_imagef(i,coord)\n"
    "#endif\n"
    "#define LOAD_INPUT4(offset) CONVERT_COMPUTE_FLOAT4(RI_F(input,(offset) >> 2))\n"
    "#define LOAD_INPUT16(offset) "
    "(COMPUTE_FLOAT16)(LOAD_INPUT4(offset),LOAD_INPUT4((offset)+4),LOAD_INPUT4((offset)+8),LOAD_INPUT4((offset)+12))\n"
    "#else\n"
    "#define LOAD_INPUT4(offset) CONVERT_COMPUTE_FLOAT4(vload4(0,input+(offset)))\n"
    "#define LOAD_INPUT16(offset) CONVERT_COMPUTE_FLOAT16(vload16(0,input+(offset)))\n"
    "#endif\n"
    "#define UCHAR4_TO_FLOAT8(b, scale, offset) "
    " wei.s0 = CONVERT_FLOAT((b.s0 >> 4)); "
    " wei.s1 = CONVERT_FLOAT((b.s0 & 15)); "
    " wei.s2 = CONVERT_FLOAT((b.s1 >> 4)); "
    " wei.s3 = CONVERT_FLOAT((b.s1 & 15)); "
    " wei.s4 = CONVERT_FLOAT((b.s2 >> 4)); "
    " wei.s5 = CONVERT_FLOAT((b.s2 & 15)); "
    " wei.s6 = CONVERT_FLOAT((b.s3 >> 4)); "
    " wei.s7 = CONVERT_FLOAT((b.s3 & 15)); "
    " wei=wei*scale+offset;\n"
    "__kernel void gemm_b8_c8_int4_buf(GLOBAL_SIZE_DIM2\n"
    "#ifdef USE_IMAGE1D_INPUT\n"
    " __read_only image1d_buffer_t input,\n"
    "#else\n"
    " __global const FLOAT* input,\n"
    "#endif\n"
    "#ifdef USE_IMAGE\n"
    " __read_only image2d_t weight,\n"
    "#else\n"
    " __global const uchar *weight,\n"
    "#endif\n"
    " __global const FLOAT *dequantScaleOffset,\n"
    " __global const FLOAT *bias,\n"
    " __global FLOAT* output,\n"
    " __private const int bhw,\n"
    " __private const int dstChannelAlign,\n"
    " __private const int srcChannelAlign,\n"
    " __private const int blockNum,\n"
    " __private const int blockDim,\n"
    " __private const float coef) {\n"
    " const int x=get_global_id(0); //b/8\n"
    " const int y=get_global_id(1); //c/8\n"
    " UNIFORM_BOUNDRY_CHECK(x,y);\n"
    " \n"
    " const int out_b_idx=x << 3; // 8 batches per work-item\n"
    " const int out_c_idx=y << 1; // 8 channels (2*float4)\n"
    " COMPUTE_FLOAT8 out0=CONVERT_COMPUTE_FLOAT8(vload8(0,bias+(out_c_idx << 2)));\n"
    " COMPUTE_FLOAT8 out1=out0;\n"
    " COMPUTE_FLOAT8 out2=out0;\n"
    " COMPUTE_FLOAT8 out3=out0;\n"
    " COMPUTE_FLOAT8 out4=out0;\n"
    " COMPUTE_FLOAT8 out5=out0;\n"
    " COMPUTE_FLOAT8 out6=out0;\n"
    " COMPUTE_FLOAT8 out7=out0;\n"
    " \n"
    " const int bhw4=bhw << 2;\n"
    " const int input_offset=out_b_idx*4;\n"
    " int out_offset=out_c_idx*bhw4+out_b_idx*4;\n"
    "#ifndef USE_IMAGE\n"
    " const int weight_offset=y*srcChannelAlign*4;\n"
    "#endif\n"
    " const int loop=(blockDim+4-1)/4;\n"
    "#if INPUT_CHANNEL_LEAVES_NUM != 0\n"
    " const int loop_end=max(loop-1,0);\n"
    "#else\n"
    " const int loop_end=loop;\n"
    "#endif\n"
    "#if INPUT_BATCH_LEAVES_NUM != 0\n"
    " if(out_b_idx+7 >= bhw){\n"
    " // Tail path: handle remaining 1-7 batches\n"
    " for (int i=0; i<blockNum; i++){\n"
    " #ifdef ASYMMETRIC\n"
    " COMPUTE_FLOAT8 scale,offset;\n"
    " {\n"
    " COMPUTE_FLOAT16 scaleOffset=CONVERT_COMPUTE_FLOAT16(convert_float16(vload16(0,dequantScaleOffset+(out_c_idx << "
    "3)+i*dstChannelAlign*2))/coef);\n"
    " scale=scaleOffset.s02468ace;\n"
    " offset=scaleOffset.s13579bdf;\n"
    " }\n"
    " #else\n"
    " COMPUTE_FLOAT8 scale=CONVERT_COMPUTE_FLOAT8(convert_float8(vload8(0,dequantScaleOffset+(out_c_idx << "
    "2)+i*dstChannelAlign))/coef);\n"
    " COMPUTE_FLOAT8 offset=(COMPUTE_FLOAT8)(-8)*scale;\n"
    " #endif\n"
    " for (int j=0; j<loop_end; j++) {\n"
    " int k=i*loop+j;\n"
    " COMPUTE_FLOAT8 wei;\n"
    " #ifdef USE_IMAGE\n"
    " uchar16 charWeightsInt40=as_uchar16(read_imagei(weight,SAMPLER,(int2)(k,y)));\n"
    " #else\n"
    " uchar16 charWeightsInt40=vload16(k,weight+weight_offset);\n"
    " #endif\n"
    " \n"
    "#if INPUT_BATCH_LEAVES_NUM >= 4\n"
    " // First 4 batches are always valid\n"
    " COMPUTE_FLOAT16 inA=LOAD_INPUT16(input_offset+k*bhw4);\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s0123,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s0,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s4,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.s8,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.sc,wei,out3);\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s4567,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s1,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s5,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.s9,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.sd,wei,out3);\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s89ab,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s2,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s6,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.sa,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.se,wei,out3);\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.scdef,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s3,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s7,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.sb,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.sf,wei,out3);\n"
    " }\n"
    " // Remaining batches (4..6)\n"
    " {\n"
    " COMPUTE_FLOAT16 inB=LOAD_INPUT16(input_offset+16+k*bhw4);\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s0123,scale,offset);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s0,wei,out4);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 6\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s4,wei,out5);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 7\n"
    " out6=mad((COMPUTE_FLOAT8)inB.s8,wei,out6);\n"
    " #endif\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s4567,scale,offset);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s1,wei,out4);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 6\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s5,wei,out5);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 7\n"
    " out6=mad((COMPUTE_FLOAT8)inB.s9,wei,out6);\n"
    " #endif\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s89ab,scale,offset);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s2,wei,out4);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 6\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s6,wei,out5);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 7\n"
    " out6=mad((COMPUTE_FLOAT8)inB.sa,wei,out6);\n"
    " #endif\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.scdef,scale,offset);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s3,wei,out4);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 6\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s7,wei,out5);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 7\n"
    " out6=mad((COMPUTE_FLOAT8)inB.sb,wei,out6);\n"
    " #endif\n"
    " }\n"
    " }\n"
    "#else\n"
    " // INPUT_BATCH_LEAVES_NUM<4: only 1-3 valid batches\n"
    " COMPUTE_FLOAT4 in0=LOAD_INPUT4(input_offset+k*bhw4);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 2\n"
    " COMPUTE_FLOAT4 in1=LOAD_INPUT4(input_offset+k*bhw4+4);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 3\n"
    " COMPUTE_FLOAT4 in2=LOAD_INPUT4(input_offset+k*bhw4+8);\n"
    " #endif\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s0123,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)in0.s0,wei,out0);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 2\n"
    " out1=mad((COMPUTE_FLOAT8)in1.s0,wei,out1);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 3\n"
    " out2=mad((COMPUTE_FLOAT8)in2.s0,wei,out2);\n"
    " #endif\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s4567,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)in0.s1,wei,out0);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 2\n"
    " out1=mad((COMPUTE_FLOAT8)in1.s1,wei,out1);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 3\n"
    " out2=mad((COMPUTE_FLOAT8)in2.s1,wei,out2);\n"
    " #endif\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s89ab,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)in0.s2,wei,out0);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 2\n"
    " out1=mad((COMPUTE_FLOAT8)in1.s2,wei,out1);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 3\n"
    " out2=mad((COMPUTE_FLOAT8)in2.s2,wei,out2);\n"
    " #endif\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.scdef,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)in0.s3,wei,out0);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 2\n"
    " out1=mad((COMPUTE_FLOAT8)in1.s3,wei,out1);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 3\n"
    " out2=mad((COMPUTE_FLOAT8)in2.s3,wei,out2);\n"
    " #endif\n"
    " }\n"
    "#endif\n"
    " }\n"
    " #if INPUT_CHANNEL_LEAVES_NUM != 0\n"
    " {\n"
    " int k=i*loop+loop_end;\n"
    " COMPUTE_FLOAT8 wei;\n"
    " #ifdef USE_IMAGE\n"
    " uchar16 charWeightsInt40=as_uchar16(read_imagei(weight,SAMPLER,(int2)(k,y)));\n"
    " #else\n"
    " uchar16 charWeightsInt40=vload16(k,weight+weight_offset);\n"
    " #endif\n"
    "#if INPUT_BATCH_LEAVES_NUM >= 4\n"
    " COMPUTE_FLOAT16 inA=LOAD_INPUT16(input_offset+k*bhw4);\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s0123,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s0,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s4,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.s8,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.sc,wei,out3);\n"
    " }\n"
    " #if INPUT_CHANNEL_LEAVES_NUM >= 2\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s4567,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s1,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s5,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.s9,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.sd,wei,out3);\n"
    " }\n"
    " #endif\n"
    " #if INPUT_CHANNEL_LEAVES_NUM >= 3\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s89ab,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s2,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s6,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.sa,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.se,wei,out3);\n"
    " }\n"
    " #endif\n"
    " {\n"
    " COMPUTE_FLOAT16 inB=LOAD_INPUT16(input_offset+16+k*bhw4);\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s0123,scale,offset);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s0,wei,out4);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 6\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s4,wei,out5);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 7\n"
    " out6=mad((COMPUTE_FLOAT8)inB.s8,wei,out6);\n"
    " #endif\n"
    " }\n"
    " #if INPUT_CHANNEL_LEAVES_NUM >= 2\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s4567,scale,offset);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s1,wei,out4);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 6\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s5,wei,out5);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 7\n"
    " out6=mad((COMPUTE_FLOAT8)inB.s9,wei,out6);\n"
    " #endif\n"
    " }\n"
    " #endif\n"
    " #if INPUT_CHANNEL_LEAVES_NUM >= 3\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s89ab,scale,offset);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s2,wei,out4);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 6\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s6,wei,out5);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 7\n"
    " out6=mad((COMPUTE_FLOAT8)inB.sa,wei,out6);\n"
    " #endif\n"
    " }\n"
    " #endif\n"
    " }\n"
    "#else\n"
    " COMPUTE_FLOAT4 in0=LOAD_INPUT4(input_offset+k*bhw4);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 2\n"
    " COMPUTE_FLOAT4 in1=LOAD_INPUT4(input_offset+k*bhw4+4);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 3\n"
    " COMPUTE_FLOAT4 in2=LOAD_INPUT4(input_offset+k*bhw4+8);\n"
    " #endif\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s0123,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)in0.s0,wei,out0);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 2\n"
    " out1=mad((COMPUTE_FLOAT8)in1.s0,wei,out1);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 3\n"
    " out2=mad((COMPUTE_FLOAT8)in2.s0,wei,out2);\n"
    " #endif\n"
    " }\n"
    " #if INPUT_CHANNEL_LEAVES_NUM >= 2\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s4567,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)in0.s1,wei,out0);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 2\n"
    " out1=mad((COMPUTE_FLOAT8)in1.s1,wei,out1);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 3\n"
    " out2=mad((COMPUTE_FLOAT8)in2.s1,wei,out2);\n"
    " #endif\n"
    " }\n"
    " #endif\n"
    " #if INPUT_CHANNEL_LEAVES_NUM >= 3\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s89ab,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)in0.s2,wei,out0);\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 2\n"
    " out1=mad((COMPUTE_FLOAT8)in1.s2,wei,out1);\n"
    " #endif\n"
    " #if INPUT_BATCH_LEAVES_NUM >= 3\n"
    " out2=mad((COMPUTE_FLOAT8)in2.s2,wei,out2);\n"
    " #endif\n"
    " }\n"
    " #endif\n"
    "#endif\n"
    " }\n"
    " #endif\n"
    " }\n"
    " } else {\n"
    "#endif\n"
    " for (int i=0; i<blockNum; i++){\n"
    " #ifdef ASYMMETRIC\n"
    " COMPUTE_FLOAT8 scale,offset;\n"
    " {\n"
    " COMPUTE_FLOAT16 scaleOffset=CONVERT_COMPUTE_FLOAT16(convert_float16(vload16(0,dequantScaleOffset+(out_c_idx << "
    "3)+i*dstChannelAlign*2))/coef);\n"
    " scale=scaleOffset.s02468ace;\n"
    " offset=scaleOffset.s13579bdf;\n"
    " }\n"
    " #else\n"
    " COMPUTE_FLOAT8 scale=CONVERT_COMPUTE_FLOAT8(convert_float8(vload8(0,dequantScaleOffset+(out_c_idx << "
    "2)+i*dstChannelAlign))/coef);\n"
    " COMPUTE_FLOAT8 offset=(COMPUTE_FLOAT8)(-8)*scale;\n"
    " #endif\n"
    " for (int j=0; j<loop_end; j++) {\n"
    " int k=i*loop+j;\n"
    " COMPUTE_FLOAT8 wei;\n"
    " \n"
    " #ifdef USE_IMAGE\n"
    " uchar16 charWeightsInt40=as_uchar16(read_imagei(weight,SAMPLER,(int2)(k,y)));\n"
    " #else\n"
    " uchar16 charWeightsInt40=vload16(k,weight+weight_offset);\n"
    " #endif\n"
    " \n"
    " COMPUTE_FLOAT16 inA=LOAD_INPUT16(input_offset+k*bhw4);\n"
    " COMPUTE_FLOAT16 inB=LOAD_INPUT16(input_offset+16+k*bhw4);\n"
    " \n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s0123,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s0,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s4,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.s8,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.sc,wei,out3);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s0,wei,out4);\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s4,wei,out5);\n"
    " out6=mad((COMPUTE_FLOAT8)inB.s8,wei,out6);\n"
    " out7=mad((COMPUTE_FLOAT8)inB.sc,wei,out7);\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s4567,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s1,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s5,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.s9,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.sd,wei,out3);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s1,wei,out4);\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s5,wei,out5);\n"
    " out6=mad((COMPUTE_FLOAT8)inB.s9,wei,out6);\n"
    " out7=mad((COMPUTE_FLOAT8)inB.sd,wei,out7);\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s89ab,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s2,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s6,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.sa,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.se,wei,out3);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s2,wei,out4);\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s6,wei,out5);\n"
    " out6=mad((COMPUTE_FLOAT8)inB.sa,wei,out6);\n"
    " out7=mad((COMPUTE_FLOAT8)inB.se,wei,out7);\n"
    " }\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.scdef,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s3,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s7,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.sb,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.sf,wei,out3);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s3,wei,out4);\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s7,wei,out5);\n"
    " out6=mad((COMPUTE_FLOAT8)inB.sb,wei,out6);\n"
    " out7=mad((COMPUTE_FLOAT8)inB.sf,wei,out7);\n"
    " }\n"
    " }\n"
    " #if INPUT_CHANNEL_LEAVES_NUM != 0\n"
    " {\n"
    " int k=i*loop+loop_end;\n"
    " COMPUTE_FLOAT8 wei;\n"
    " #ifdef USE_IMAGE\n"
    " uchar16 charWeightsInt40=as_uchar16(read_imagei(weight,SAMPLER,(int2)(k,y)));\n"
    " #else\n"
    " uchar16 charWeightsInt40=vload16(k,weight+weight_offset);\n"
    " #endif\n"
    " COMPUTE_FLOAT16 inA=LOAD_INPUT16(input_offset+k*bhw4);\n"
    " COMPUTE_FLOAT16 inB=LOAD_INPUT16(input_offset+16+k*bhw4);\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s0123,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s0,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s4,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.s8,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.sc,wei,out3);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s0,wei,out4);\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s4,wei,out5);\n"
    " out6=mad((COMPUTE_FLOAT8)inB.s8,wei,out6);\n"
    " out7=mad((COMPUTE_FLOAT8)inB.sc,wei,out7);\n"
    " }\n"
    " #if INPUT_CHANNEL_LEAVES_NUM >= 2\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s4567,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s1,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s5,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.s9,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.sd,wei,out3);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s1,wei,out4);\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s5,wei,out5);\n"
    " out6=mad((COMPUTE_FLOAT8)inB.s9,wei,out6);\n"
    " out7=mad((COMPUTE_FLOAT8)inB.sd,wei,out7);\n"
    " }\n"
    " #endif\n"
    " #if INPUT_CHANNEL_LEAVES_NUM >= 3\n"
    " {\n"
    " UCHAR4_TO_FLOAT8(charWeightsInt40.s89ab,scale,offset);\n"
    " out0=mad((COMPUTE_FLOAT8)inA.s2,wei,out0);\n"
    " out1=mad((COMPUTE_FLOAT8)inA.s6,wei,out1);\n"
    " out2=mad((COMPUTE_FLOAT8)inA.sa,wei,out2);\n"
    " out3=mad((COMPUTE_FLOAT8)inA.se,wei,out3);\n"
    " out4=mad((COMPUTE_FLOAT8)inB.s2,wei,out4);\n"
    " out5=mad((COMPUTE_FLOAT8)inB.s6,wei,out5);\n"
    " out6=mad((COMPUTE_FLOAT8)inB.sa,wei,out6);\n"
    " out7=mad((COMPUTE_FLOAT8)inB.se,wei,out7);\n"
    " }\n"
    " #endif\n"
    " }\n"
    " #endif\n"
    " }\n"
    "#if INPUT_BATCH_LEAVES_NUM != 0\n"
    " }\n"
    "#endif\n"
    "#ifdef RELU\n"
    " out0=fmax(out0,(COMPUTE_FLOAT8)0);\n"
    " out1=fmax(out1,(COMPUTE_FLOAT8)0);\n"
    " out2=fmax(out2,(COMPUTE_FLOAT8)0);\n"
    " out3=fmax(out3,(COMPUTE_FLOAT8)0);\n"
    " out4=fmax(out4,(COMPUTE_FLOAT8)0);\n"
    " out5=fmax(out5,(COMPUTE_FLOAT8)0);\n"
    " out6=fmax(out6,(COMPUTE_FLOAT8)0);\n"
    " out7=fmax(out7,(COMPUTE_FLOAT8)0);\n"
    "#endif\n"
    "#ifdef RELU6\n"
    " out0=clamp(out0,(COMPUTE_FLOAT8)0,(COMPUTE_FLOAT8)6);\n"
    " out1=clamp(out1,(COMPUTE_FLOAT8)0,(COMPUTE_FLOAT8)6);\n"
    " out2=clamp(out2,(COMPUTE_FLOAT8)0,(COMPUTE_FLOAT8)6);\n"
    " out3=clamp(out3,(COMPUTE_FLOAT8)0,(COMPUTE_FLOAT8)6);\n"
    " out4=clamp(out4,(COMPUTE_FLOAT8)0,(COMPUTE_FLOAT8)6);\n"
    " out5=clamp(out5,(COMPUTE_FLOAT8)0,(COMPUTE_FLOAT8)6);\n"
    " out6=clamp(out6,(COMPUTE_FLOAT8)0,(COMPUTE_FLOAT8)6);\n"
    " out7=clamp(out7,(COMPUTE_FLOAT8)0,(COMPUTE_FLOAT8)6);\n"
    "#endif\n"
    "#if INPUT_BATCH_LEAVES_NUM != 0\n"
    " if(out_b_idx+7 >= bhw){\n"
    "#if INPUT_BATCH_LEAVES_NUM >= 4\n"
    " // First 4 batches are always valid\n"
    " vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out0.s0123,out1.s0123,out2.s0123,out3.s0123)),0,output+out_offset);\n"
    " if((out_c_idx << 2)+4<dstChannelAlign){\n"
    " vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out0.s4567,out1.s4567,out2.s4567,out3.s4567)),0,output+out_offset+"
    "bhw4);\n"
    " }\n"
    " // Write remaining valid batches (4..6)\n"
    " #if INPUT_BATCH_LEAVES_NUM == 4\n"
    " // No remaining batches\n"
    " #elif INPUT_BATCH_LEAVES_NUM == 5\n"
    " {\n"
    " int off2=out_offset+16;\n"
    " vstore4(CONVERT_FLOAT4(out4.s0123),0,output+off2);\n"
    " if((out_c_idx << 2)+4<dstChannelAlign){\n"
    " vstore4(CONVERT_FLOAT4(out4.s4567),0,output+off2+bhw4);\n"
    " }\n"
    " }\n"
    " #elif INPUT_BATCH_LEAVES_NUM == 6\n"
    " {\n"
    " int off2=out_offset+16;\n"
    " vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out4.s0123,out5.s0123)),0,output+off2);\n"
    " if((out_c_idx << 2)+4<dstChannelAlign){\n"
    " vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out4.s4567,out5.s4567)),0,output+off2+bhw4);\n"
    " }\n"
    " }\n"
    " #elif INPUT_BATCH_LEAVES_NUM == 7\n"
    " {\n"
    " int off2=out_offset+16;\n"
    " vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out4.s0123,out5.s0123)),0,output+off2);\n"
    " vstore4(CONVERT_FLOAT4(out6.s0123),0,output+off2+8);\n"
    " if((out_c_idx << 2)+4<dstChannelAlign){\n"
    " vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out4.s4567,out5.s4567)),0,output+off2+bhw4);\n"
    " vstore4(CONVERT_FLOAT4(out6.s4567),0,output+off2+bhw4+8);\n"
    " }\n"
    " }\n"
    " #endif\n"
    "#elif INPUT_BATCH_LEAVES_NUM == 3\n"
    " vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out0.s0123,out1.s0123)),0,output+out_offset);\n"
    " vstore4(CONVERT_FLOAT4(out2.s0123),0,output+out_offset+8);\n"
    " if((out_c_idx << 2)+4<dstChannelAlign){\n"
    " vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out0.s4567,out1.s4567)),0,output+out_offset+bhw4);\n"
    " vstore4(CONVERT_FLOAT4(out2.s4567),0,output+out_offset+bhw4+8);\n"
    " }\n"
    "#elif INPUT_BATCH_LEAVES_NUM == 2\n"
    " vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out0.s0123,out1.s0123)),0,output+out_offset);\n"
    " if((out_c_idx << 2)+4<dstChannelAlign){\n"
    " vstore8(CONVERT_FLOAT8((COMPUTE_FLOAT8)(out0.s4567,out1.s4567)),0,output+out_offset+bhw4);\n"
    " }\n"
    "#elif INPUT_BATCH_LEAVES_NUM == 1\n"
    " vstore4(CONVERT_FLOAT4(out0.s0123),0,output+out_offset);\n"
    " if((out_c_idx << 2)+4<dstChannelAlign){\n"
    " vstore4(CONVERT_FLOAT4(out0.s4567),0,output+out_offset+bhw4);\n"
    " }\n"
    "#endif\n"
    " } else {\n"
    "#endif\n"
    " // Write all 8 batches\n"
    " vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out0.s0123,out1.s0123,out2.s0123,out3.s0123)),0,output+out_offset);\n"
    " vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out4.s0123,out5.s0123,out6.s0123,out7.s0123)),0,output+out_offset+16);"
    "\n"
    " if((out_c_idx << 2)+4<dstChannelAlign){\n"
    " vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out0.s4567,out1.s4567,out2.s4567,out3.s4567)),0,output+out_offset+"
    "bhw4);\n"
    " vstore16(CONVERT_FLOAT16((COMPUTE_FLOAT16)(out4.s4567,out5.s4567,out6.s4567,out7.s4567)),0,output+out_offset+"
    "bhw4+16);\n"
    " }\n"
    "#if INPUT_BATCH_LEAVES_NUM != 0\n"
    " }\n"
    "#endif\n"
    "}\n";
#endif
} // namespace MNN
