#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* gemm_conv1x1_layout_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "#define GLOBAL_SIZE_DIM2 "
    " __private int global_size_dim0,__private int global_size_dim1,\n"
    "#define UNIFORM_BOUNDRY_CHECK(index0, index1) "
    " if(index0 >= global_size_dim0 || index1 >= global_size_dim1) { "
    " return; "
    " }\n"
    "__kernel void gemm_c4nhw4_to_nhwc(GLOBAL_SIZE_DIM2\n"
    "__global const FLOAT* input,\n"
    "__global FLOAT* output,\n"
    "__private const int bhw,\n"
    "__private const int channel,\n"
    "__private const int channelAlign\n"
    "){\n"
    " const int x=get_global_id(0); //b/4\n"
    " const int y=get_global_id(1); //c/4\n"
    " UNIFORM_BOUNDRY_CHECK(x,y);\n"
    " const int out_b_idx=x << 2;\n"
    " const int out_c_idx=y << 2;\n"
    " const int bhw4=bhw << 2;\n"
    " const int input_offset=y*bhw4+out_b_idx*4;\n"
    " FLOAT4 in0,in1,in2,in3;\n"
    " if(out_c_idx+3<channel && out_b_idx+3<bhw){\n"
    " in0=vload4(0,input+input_offset);\n"
    " in1=vload4(0,input+input_offset+4);\n"
    " in2=vload4(0,input+input_offset+8);\n"
    " in3=vload4(0,input+input_offset+12);\n"
    " } else{\n"
    " if(out_c_idx+3<channel){\n"
    " in0=vload4(0,input+input_offset);\n"
    " in1=out_b_idx+1<bhw ? vload4(0,input+input_offset+4) : 0;\n"
    " in2=out_b_idx+2<bhw ? vload4(0,input+input_offset+8) : 0;\n"
    " in3=out_b_idx+3<bhw ? vload4(0,input+input_offset+12) : 0;\n"
    " } else if(out_c_idx+1 == channel){\n"
    " in0=(FLOAT4)(input[input_offset],0,0,0);\n"
    " in1=out_b_idx+1<bhw ? (FLOAT4)(input[input_offset+4],0,0,0) : 0;\n"
    " in2=out_b_idx+2<bhw ? (FLOAT4)(input[input_offset+8],0,0,0) : 0;\n"
    " in3=out_b_idx+3<bhw ? (FLOAT4)(input[input_offset+12],0,0,0) : 0;\n"
    " } else if(out_c_idx+2 == channel){\n"
    " in0=(FLOAT4)(input[input_offset],input[input_offset+1],0,0);\n"
    " in1=out_b_idx+1<bhw ? (FLOAT4)(input[input_offset+4],input[input_offset+5],0,0) : 0;\n"
    " in2=out_b_idx+2<bhw ? (FLOAT4)(input[input_offset+8],input[input_offset+9],0,0) : 0;\n"
    " in3=out_b_idx+3<bhw ? (FLOAT4)(input[input_offset+12],input[input_offset+13],0,0) : 0;\n"
    " } else if(out_c_idx+3 == channel){\n"
    " in0=(FLOAT4)(input[input_offset],input[input_offset+1],input[input_offset+2],0);\n"
    " in1=out_b_idx+1<bhw ? (FLOAT4)(input[input_offset+4],input[input_offset+5],input[input_offset+6],0) : 0;\n"
    " in2=out_b_idx+2<bhw ? (FLOAT4)(input[input_offset+8],input[input_offset+9],input[input_offset+10],0) : 0;\n"
    " in3=out_b_idx+3<bhw ? (FLOAT4)(input[input_offset+12],input[input_offset+13],input[input_offset+14],0) : 0;\n"
    " }\n"
    " }\n"
    " int out_offset=out_b_idx*channelAlign+out_c_idx;\n"
    " vstore4(in0,0,output+out_offset);\n"
    " vstore4(in1,0,output+out_offset+channelAlign);\n"
    " vstore4(in2,0,output+out_offset+channelAlign+channelAlign);\n"
    " vstore4(in3,0,output+out_offset+channelAlign+channelAlign+channelAlign);\n"
    "}\n"
    "__kernel void gemm_nhwc_to_c4nhw4(GLOBAL_SIZE_DIM2\n"
    "__global const FLOAT* input,\n"
    "__global FLOAT* output,\n"
    "__private const int bhw,\n"
    "__private const int channelAlign\n"
    "){\n"
    " const int x=get_global_id(0); //b/4\n"
    " const int y=get_global_id(1); //c/4\n"
    " UNIFORM_BOUNDRY_CHECK(x,y);\n"
    " const int out_b_idx=x << 2;\n"
    " const int out_c_idx=y << 2;\n"
    " const int bhw4=bhw << 2;\n"
    " const int input_offset=out_b_idx*channelAlign+out_c_idx;\n"
    " FLOAT4 in0=vload4(0,input+input_offset);\n"
    " FLOAT4 in1=vload4(0,input+input_offset+channelAlign);\n"
    " FLOAT4 in2=vload4(0,input+input_offset+channelAlign+channelAlign);\n"
    " FLOAT4 in3=vload4(0,input+input_offset+channelAlign+channelAlign+channelAlign);\n"
    " int out_offset=y*bhw4+out_b_idx*4;\n"
    " vstore4(in0,0,output+out_offset);\n"
    " if(out_b_idx+1 >= bhw) return;\n"
    " vstore4(in1,0,output+out_offset+4);\n"
    " if(out_b_idx+2 >= bhw) return;\n"
    " vstore4(in2,0,output+out_offset+8);\n"
    " if(out_b_idx+3 >= bhw) return;\n"
    " vstore4(in3,0,output+out_offset+12);\n"
    "}\n";
#endif
} // namespace MNN
