#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* gemm_conv1x1_inverse_quant_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "#define GLOBAL_SIZE_DIM2 "
    " __private int global_size_dim0,__private int global_size_dim1,\n"
    "#define UNIFORM_BOUNDRY_CHECK(index0, index1) "
    " if(index0 >= global_size_dim0 || index1 >= global_size_dim1) { "
    " return; "
    " }\n"
    "#define UCHAR4_TO_CHAR8(a, c) "
    " a.s0=(c.s0 >> 4); a.s1=(c.s0 & 15); a.s2=(c.s1 >> 4); a.s3=(c.s1 & 15); a.s4=(c.s2 >> 4); a.s5=(c.s2 & 15); "
    "a.s6=(c.s3 >> 4); a.s7=(c.s3 & 15);\n"
    "// 2bit unpack: 2 packed bytes (b0,b1) → 8 chars,unsigned [0,3].\n"
    "// Origin offset is folded into the dequant `offset` (or asym bias) by the caller.\n"
    "#define UCHAR2_TO_CHAR8_W2(a, b0, b1) "
    " a.s0 = (char)((b0 >> 6) & 3); "
    " a.s1 = (char)((b0 >> 4) & 3); "
    " a.s2 = (char)((b0 >> 2) & 3); "
    " a.s3 = (char)((b0 >> 0) & 3); "
    " a.s4 = (char)((b1 >> 6) & 3); "
    " a.s5 = (char)((b1 >> 4) & 3); "
    " a.s6 = (char)((b1 >> 2) & 3); "
    " a.s7=(char)((b1 >> 0) & 3);\n"
    "// 3bit unpack: 2 low bytes+1 high byte → 8 chars,unsigned [0,7].\n"
    "// Origin offset is folded into the dequant `offset` (or asym bias) by the caller.\n"
    "#define UCHAR3_TO_CHAR8_W3(a, b0, b1, h) "
    " a.s0 = (char)(((b0 >> 6) & 3) | (((h >> 7) & 1) << 2)); "
    " a.s1 = (char)(((b0 >> 4) & 3) | (((h >> 6) & 1) << 2)); "
    " a.s2 = (char)(((b0 >> 2) & 3) | (((h >> 5) & 1) << 2)); "
    " a.s3 = (char)(((b0 >> 0) & 3) | (((h >> 4) & 1) << 2)); "
    " a.s4 = (char)(((b1 >> 6) & 3) | (((h >> 3) & 1) << 2)); "
    " a.s5 = (char)(((b1 >> 4) & 3) | (((h >> 2) & 1) << 2)); "
    " a.s6 = (char)(((b1 >> 2) & 3) | (((h >> 1) & 1) << 2)); "
    " a.s7=(char)(((b1 >> 0) & 3) | (((h >> 0) & 1) << 2));\n"
    "__constant sampler_t SAMPLER=CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;\n"
    "__kernel void inverse_quant_weight(GLOBAL_SIZE_DIM2\n"
    " #ifdef USE_IMAGE\n"
    " __read_only image2d_t weight,\n"
    " #else\n"
    " #if QUANT_BIT == 8\n"
    " __global const char *weight,\n"
    " #else\n"
    " __global const uchar *weight,\n"
    " #endif\n"
    " #endif\n"
    " __global const FLOAT *dequantScaleOffset,\n"
    " __global FLOAT* output,\n"
    " __private const int inputChannel,\n"
    " __private const int inputChannel4Align,\n"
    " __private const int outputChannelAlign,\n"
    " __private const int outputChannel4Align,\n"
    " __private const int blockDim,\n"
    " __private const float coef){\n"
    " const int x=get_global_id(0); //ic\n"
    " const int y=get_global_id(1); //oc\n"
    " UNIFORM_BOUNDRY_CHECK(x,y);\n"
    " \n"
    "#if QUANT_BIT == 2 || QUANT_BIT == 3 || QUANT_BIT == 4\n"
    " const int ic=x << 2;\n"
    " const int oc=y << 3;\n"
    " const int output_offset=ic*outputChannelAlign+oc;\n"
    " #ifdef ASYMMETRIC\n"
    " COMPUTE_FLOAT8 scale,offset;\n"
    " {\n"
    " COMPUTE_FLOAT16 "
    "ScaleOffset=CONVERT_COMPUTE_FLOAT16(convert_float16(vload16(0,dequantScaleOffset+((ic/"
    "blockDim)*outputChannel4Align+oc)*2))/coef);\n"
    " scale=ScaleOffset.s02468ace;\n"
    " offset=ScaleOffset.s13579bdf;\n"
    " }\n"
    " #else\n"
    " COMPUTE_FLOAT8 "
    "scale=CONVERT_COMPUTE_FLOAT8(convert_float8(vload8(0,dequantScaleOffset+(ic/blockDim)*outputChannel4Align+oc))/"
    "coef);\n"
    " #if QUANT_BIT == 2\n"
    " COMPUTE_FLOAT8 offset=(COMPUTE_FLOAT8)(-2)*scale;\n"
    " #elif QUANT_BIT == 3\n"
    " COMPUTE_FLOAT8 offset=(COMPUTE_FLOAT8)(-4)*scale;\n"
    " #else\n"
    " COMPUTE_FLOAT8 offset=(COMPUTE_FLOAT8)(-8)*scale;\n"
    " #endif\n"
    " #endif\n"
    " COMPUTE_FLOAT8 weights0,weights1,weights2,weights3;\n"
    " {\n"
    "#if QUANT_BIT == 4\n"
    " #ifdef USE_IMAGE\n"
    " uchar16 charWeightsInt40=as_uchar16(read_imagei(weight,SAMPLER,(int2)(x,y)));\n"
    " #else\n"
    " uchar16 charWeightsInt40=vload16(x,weight+y*inputChannel4Align*4);\n"
    " #endif\n"
    " char8 charWeights0;\n"
    " UCHAR4_TO_CHAR8(charWeights0,charWeightsInt40.s0123);\n"
    " weights0=CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    " UCHAR4_TO_CHAR8(charWeights0,charWeightsInt40.s4567);\n"
    " weights1=ic+1 >= inputChannel ? 0 : CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    " UCHAR4_TO_CHAR8(charWeights0,charWeightsInt40.s89ab);\n"
    " weights2=ic+2 >= inputChannel ? 0 : CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    " UCHAR4_TO_CHAR8(charWeights0,charWeightsInt40.scdef);\n"
    " weights3=ic+3 >= inputChannel ? 0 : CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    "#elif QUANT_BIT == 2\n"
    " // 2bit storage: 8 bytes per (4IC × 8OC) tile,weight_offset row stride=inputChannel4Align*2\n"
    " uchar8 charWeightsInt20=vload8(x,weight+y*inputChannel4Align*2);\n"
    " char8 charWeights0;\n"
    " UCHAR2_TO_CHAR8_W2(charWeights0,charWeightsInt20.s0,charWeightsInt20.s1);\n"
    " weights0=CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    " UCHAR2_TO_CHAR8_W2(charWeights0,charWeightsInt20.s2,charWeightsInt20.s3);\n"
    " weights1=ic+1 >= inputChannel ? 0 : CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    " UCHAR2_TO_CHAR8_W2(charWeights0,charWeightsInt20.s4,charWeightsInt20.s5);\n"
    " weights2=ic+2 >= inputChannel ? 0 : CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    " UCHAR2_TO_CHAR8_W2(charWeights0,charWeightsInt20.s6,charWeightsInt20.s7);\n"
    " weights3=ic+3 >= inputChannel ? 0 : CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    "#elif QUANT_BIT == 3\n"
    " // 3bit storage: 12 bytes per (4IC × 8OC) tile,row stride=inputChannel4Align*3\n"
    " const int base=y*inputChannel4Align*3+x*12;\n"
    " uchar8 charWeightsInt30Lo=vload8(0,weight+base);\n"
    " uchar4 charWeightsInt30Hi=vload4(0,weight+base+8);\n"
    " char8 charWeights0;\n"
    " UCHAR3_TO_CHAR8_W3(charWeights0,charWeightsInt30Lo.s0,charWeightsInt30Lo.s1,charWeightsInt30Hi.s0);\n"
    " weights0=CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    " UCHAR3_TO_CHAR8_W3(charWeights0,charWeightsInt30Lo.s2,charWeightsInt30Lo.s3,charWeightsInt30Hi.s1);\n"
    " weights1=ic+1 >= inputChannel ? 0 : CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    " UCHAR3_TO_CHAR8_W3(charWeights0,charWeightsInt30Lo.s4,charWeightsInt30Lo.s5,charWeightsInt30Hi.s2);\n"
    " weights2=ic+2 >= inputChannel ? 0 : CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    " UCHAR3_TO_CHAR8_W3(charWeights0,charWeightsInt30Lo.s6,charWeightsInt30Lo.s7,charWeightsInt30Hi.s3);\n"
    " weights3=ic+3 >= inputChannel ? 0 : CONVERT_COMPUTE_FLOAT8(charWeights0)*scale+offset;\n"
    "#endif\n"
    " }\n"
    " vstore8(CONVERT_FLOAT8(weights0),0,output+output_offset);\n"
    " vstore8(CONVERT_FLOAT8(weights1),0,output+output_offset+outputChannelAlign);\n"
    " vstore8(CONVERT_FLOAT8(weights2),0,output+output_offset+2*outputChannelAlign);\n"
    " vstore8(CONVERT_FLOAT8(weights3),0,output+output_offset+3*outputChannelAlign);\n"
    "#elif QUANT_BIT == 8\n"
    " const int ic=x << 1;\n"
    " const int oc=y << 3;\n"
    " const int output_offset=ic*outputChannelAlign+oc;\n"
    " \n"
    " #ifdef ASYMMETRIC\n"
    " COMPUTE_FLOAT8 scale,offset;\n"
    " {\n"
    " COMPUTE_FLOAT16 "
    "ScaleOffset=CONVERT_COMPUTE_FLOAT16(convert_float16(vload16(0,dequantScaleOffset+((ic/"
    "blockDim)*outputChannel4Align+oc)*2))/coef);\n"
    " scale=ScaleOffset.s02468ace;\n"
    " offset=ScaleOffset.s13579bdf;\n"
    " }\n"
    " #else\n"
    " COMPUTE_FLOAT8 "
    "scale=CONVERT_COMPUTE_FLOAT8(convert_float8(vload8(0,dequantScaleOffset+(ic/blockDim)*outputChannel4Align+oc))/"
    "coef);\n"
    " #endif\n"
    " COMPUTE_FLOAT8 weights0,weights1;\n"
    " {\n"
    " #ifdef USE_IMAGE\n"
    " COMPUTE_FLOAT16 wei=CONVERT_COMPUTE_FLOAT16(as_char16(read_imagei(weight,SAMPLER,(int2)(x,y))));\n"
    " #else\n"
    " COMPUTE_FLOAT16 wei=CONVERT_COMPUTE_FLOAT16(vload16(x,weight+y*inputChannel4Align*8));\n"
    " #endif\n"
    " #ifdef ASYMMETRIC\n"
    " weights0=wei.s01234567*scale+offset;\n"
    " weights1=ic+1 >= inputChannel ? 0 : wei.s89abcdef*scale+offset;\n"
    " #else\n"
    " weights0=wei.s01234567*scale;\n"
    " weights1=ic+1 >= inputChannel ? 0 : wei.s89abcdef*scale;\n"
    " #endif\n"
    " }\n"
    " vstore8(CONVERT_FLOAT8(weights0),0,output+output_offset);\n"
    " vstore8(CONVERT_FLOAT8(weights1),0,output+output_offset+outputChannelAlign);\n"
    " #endif\n"
    "}\n";
#endif
} // namespace MNN
