#include "opencl_source_map.hpp"
namespace MNN {
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* layernorm_buf =
    "#ifdef MNN_SUPPORT_FP16\n"
    "#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
    "#endif\n"
    "#define MASK_C4_TAIL(value, index, channel_unit, remain) "
    " do { "
    " if ((remain) != 0 && (index) == (channel_unit)-1) { "
    " if ((remain) < 4) (value).w = 0.0f; "
    " if ((remain) < 3) (value).z = 0.0f; "
    " if ((remain) < 2) (value).y = 0.0f; "
    " } "
    " } while (0)\n"
    "__kernel void layernorm_c4_buf(__private int global_dim0,__private int global_dim1,\n"
    " __global const FLOAT4*input,\n"
    " __global FLOAT4*output,\n"
    " __private const int inside,\n"
    "#ifdef GAMMA_BETA\n"
    " __global const FLOAT4 *gamma,\n"
    " __global const FLOAT4 *beta,\n"
    "#endif\n"
    " __private float epsilon){\n"
    " int2 pos=(int2)(get_global_id(0),get_global_id(1));\n"
    "#if LOCAL_SIZE>1\n"
    " float4 local sum_mnn[LOCAL_SIZE];\n"
    " #ifndef RMSNORM\n"
    " float4 local sum_mean_mnn[LOCAL_SIZE];\n"
    " #endif\n"
    " if (pos.x<global_dim0 && pos.y<global_dim1) {\n"
    " const int lid=get_local_id(0);\n"
    " const int batch=global_dim1;\n"
    " const int channelUnit=(inside+3)/4;\n"
    " const int channelRemain=inside & 3;\n"
    " float4 in_sum=0;\n"
    " int index=lid;\n"
    " #ifdef RMSNORM\n"
    " float4 mean=(float4)0;\n"
    " #else\n"
    " for(; index<channelUnit; index+=LOCAL_SIZE){\n"
    " int idx=index*batch+pos.y;\n"
    " float4 in=convert_float4(input[idx]);\n"
    " MASK_C4_TAIL(in,index,channelUnit,channelRemain);\n"
    " in_sum += in;\n"
    " }\n"
    " sum_mean_mnn[lid]=in_sum;\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
    " if (lid<i)\n"
    " sum_mean_mnn[lid]=sum_mean_mnn[lid]+sum_mean_mnn[lid+i];\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " }\n"
    " float sum_all=sum_mean_mnn[0].x+sum_mean_mnn[0].y+sum_mean_mnn[0].z+sum_mean_mnn[0].w;\n"
    " float4 mean=(float4)(sum_all/inside);\n"
    " #endif\n"
    " in_sum=0;\n"
    " index=lid;\n"
    " for(; index<channelUnit; index+=LOCAL_SIZE){\n"
    " int idx=index*batch+pos.y;\n"
    " float4 in=convert_float4(input[idx]);\n"
    " float4 diff=in-mean;\n"
    " MASK_C4_TAIL(diff,index,channelUnit,channelRemain);\n"
    " in_sum += diff*diff;\n"
    " }\n"
    " sum_mnn[lid]=in_sum;\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
    " if (lid<i)\n"
    " sum_mnn[lid]=sum_mnn[lid]+sum_mnn[lid+i];\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " }\n"
    " float square_sum_all=sum_mnn[0].x+sum_mnn[0].y+sum_mnn[0].z+sum_mnn[0].w;\n"
    " float4 square_sum=(float4)(square_sum_all/inside);\n"
    " float4 value=(float4)1.0f/(float4)sqrt(square_sum+(float4)epsilon);\n"
    " index=lid;\n"
    " for(; index<channelUnit; index+=LOCAL_SIZE){\n"
    " int idx=index*batch+pos.y;\n"
    " float4 in=convert_float4(input[idx]);\n"
    " #ifdef GAMMA_BETA\n"
    " float4 out=(in-mean)*value*convert_float4(gamma[index])+convert_float4(beta[index]);\n"
    " #else\n"
    " float4 out=(in-mean)*value;\n"
    " #endif\n"
    " MASK_C4_TAIL(out,index,channelUnit,channelRemain);\n"
    " output[idx]=CONVERT_FLOAT4(out);\n"
    " }\n"
    " }\n"
    "#else\n"
    " if (pos.x<global_dim0 && pos.y<global_dim1) {\n"
    " const int batch=global_dim1;\n"
    " const int channelUnit=(inside+3)/4;\n"
    " const int channelRemain=inside & 3;\n"
    " float4 in_sum=0;\n"
    " #ifdef RMSNORM\n"
    " float4 mean=(float4)0;\n"
    " #else\n"
    " for(int index=0; index<channelUnit; index++){\n"
    " int idx=index*batch+pos.y;\n"
    " float4 in=convert_float4(input[idx]);\n"
    " MASK_C4_TAIL(in,index,channelUnit,channelRemain);\n"
    " in_sum += in;\n"
    " }\n"
    " float sum_all=in_sum.x+in_sum.y+in_sum.z+in_sum.w;\n"
    " float4 mean=(float4)(sum_all/inside);\n"
    " #endif\n"
    " in_sum=0;\n"
    " for(int index=0; index<channelUnit; index++){\n"
    " int idx=index*batch+pos.y;\n"
    " float4 in=convert_float4(input[idx]);\n"
    " float4 diff=in-mean;\n"
    " MASK_C4_TAIL(diff,index,channelUnit,channelRemain);\n"
    " in_sum += diff*diff;\n"
    " }\n"
    " float square_sum_all=in_sum.x+in_sum.y+in_sum.z+in_sum.w;\n"
    " float4 square_sum=(float4)(square_sum_all/inside);\n"
    " float4 value=(float4)1.0f/(float4)sqrt(square_sum+(float4)epsilon);\n"
    " int idx=pos.x*batch+pos.y;\n"
    " float4 in=convert_float4(input[idx]);\n"
    " #ifdef GAMMA_BETA\n"
    " float4 out=(in-mean)*value*convert_float4(gamma[pos.x])+convert_float4(beta[pos.x]);\n"
    " #else\n"
    " float4 out=(in-mean)*value;\n"
    " #endif\n"
    " MASK_C4_TAIL(out,pos.x,channelUnit,channelRemain);\n"
    " output[idx]=CONVERT_FLOAT4(out);\n"
    " }\n"
    "#endif\n"
    "}\n"
    "__kernel void binary_add_c4_buf(__private int global_dim0,\n"
    " __global const FLOAT* input0,\n"
    " __global const FLOAT* input1,\n"
    " __global FLOAT* output,\n"
    " __private const int size) {\n"
    " const int pos_x=get_global_id(0);\n"
    " if (pos_x >= global_dim0) return;\n"
    " int offset=pos_x << 2;\n"
    "#ifdef PACK_LEAVE\n"
    " if (offset+3 >= size) {\n"
    " int remain=size-offset;\n"
    " for (int i=0; i<remain; ++i) {\n"
    " output[offset+i]=input0[offset+i]+input1[offset+i];\n"
    " }\n"
    " return;\n"
    " }\n"
    "#endif\n"
    " float4 in0=convert_float4(vload4(0,input0+offset));\n"
    " float4 in1=convert_float4(vload4(0,input1+offset));\n"
    " float4 out=in0+in1;\n"
    " vstore4(CONVERT_FLOAT4(out),0,output+offset);\n"
    "}\n"
    "// Binary RMSNorm in one dispatch: out0=in0+in1 (the residual the block\n"
    "// carries forward),out1=RMSNorm(out0). The split binary_add_c4_buf +\n"
    "// layernorm_c4_buf pair costs a second launch and reads the summed hidden state\n"
    "// back from DRAM; here each workgroup owns one row,so the sum it reads back is\n"
    "// the sum it wrote itself. RMSNorm only: a mean-based LayerNorm needs its own\n"
    "// reduction pass over the row before the variance one,which the split path has.\n"
    "__kernel void binary_add_rms_norm_c4_buf(__private int global_dim0,__private int global_dim1,\n"
    " __global const FLOAT4* input0,__global const FLOAT4* input1,\n"
    " __global FLOAT4* output0,__global FLOAT4* output1,__private const int inside,\n"
    "#ifdef GAMMA_BETA\n"
    " __global const FLOAT4* gamma,__global const FLOAT4* beta,\n"
    "#endif\n"
    " __private float epsilon) {\n"
    " int2 pos=(int2)(get_global_id(0),get_global_id(1));\n"
    "// LOCAL_SIZE is not defined in every build-option set this program is compiled\n"
    "// with (binary_add_c4_buf is built with none at all),so guard the workgroup\n"
    "// reduce on it exactly like layernorm_c4_buf does — otherwise the local array\n"
    "// declaration fails to compile and takes the whole program down with it.\n"
    "#if LOCAL_SIZE>1\n"
    " float4 local sum_mnn[LOCAL_SIZE];\n"
    " if (pos.x<global_dim0 && pos.y<global_dim1) {\n"
    " const int lid=get_local_id(0);\n"
    " const int batch=global_dim1;\n"
    " const int channelUnit=(inside+3)/4;\n"
    " const int channelRemain=inside & 3;\n"
    " float4 in_sum=0;\n"
    " for (int index=lid; index<channelUnit; index += LOCAL_SIZE) {\n"
    " int idx=index*batch+pos.y;\n"
    " float4 sum=convert_float4(input0[idx])+convert_float4(input1[idx]);\n"
    " // Write the unmasked residual; tail padding is unused downstream.\n"
    " output0[idx]=CONVERT_FLOAT4(sum);\n"
    " // Mask tail lanes before accumulating into the RMS reduction so that\n"
    " // padding does not pollute square_sum_all.\n"
    " MASK_C4_TAIL(sum,index,channelUnit,channelRemain);\n"
    " in_sum += sum*sum;\n"
    " }\n"
    " sum_mnn[lid]=in_sum;\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " for (int i=LOCAL_SIZE/2; i>0; i /= 2) {\n"
    " if (lid<i)\n"
    " sum_mnn[lid]=sum_mnn[lid]+sum_mnn[lid+i];\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " }\n"
    " float square_sum_all=sum_mnn[0].x+sum_mnn[0].y+sum_mnn[0].z+sum_mnn[0].w;\n"
    " float4 value=(float4)1.0f/(float4)sqrt((float4)max(0.0f,square_sum_all/inside)+(float4)epsilon);\n"
    " for (int index=lid; index<channelUnit; index += LOCAL_SIZE) {\n"
    " // Re-reads what this same work-item stored above: same stride,so no\n"
    " // other work-item's store is involved.\n"
    " int idx=index*batch+pos.y;\n"
    " float4 in=convert_float4(output0[idx]);\n"
    "#ifdef GAMMA_BETA\n"
    " float4 out=in*value*convert_float4(gamma[index])+convert_float4(beta[index]);\n"
    "#else\n"
    " float4 out=in*value;\n"
    "#endif\n"
    " MASK_C4_TAIL(out,index,channelUnit,channelRemain);\n"
    " output1[idx]=CONVERT_FLOAT4(out);\n"
    " }\n"
    " }\n"
    "#else\n"
    " if (pos.x<global_dim0 && pos.y<global_dim1) {\n"
    " const int batch=global_dim1;\n"
    " const int channelUnit=(inside+3)/4;\n"
    " const int channelRemain=inside & 3;\n"
    " float4 in_sum=0;\n"
    " for (int index=0; index<channelUnit; index++) {\n"
    " int idx=index*batch+pos.y;\n"
    " float4 sum=convert_float4(input0[idx])+convert_float4(input1[idx]);\n"
    " output0[idx]=CONVERT_FLOAT4(sum);\n"
    " MASK_C4_TAIL(sum,index,channelUnit,channelRemain);\n"
    " in_sum += sum*sum;\n"
    " }\n"
    " float square_sum_all=in_sum.x+in_sum.y+in_sum.z+in_sum.w;\n"
    " float4 value=(float4)1.0f/(float4)sqrt((float4)max(0.0f,square_sum_all/inside)+(float4)epsilon);\n"
    " for (int index=0; index<channelUnit; index++) {\n"
    " int idx=index*batch+pos.y;\n"
    " float4 in=convert_float4(output0[idx]);\n"
    "#ifdef GAMMA_BETA\n"
    " float4 out=in*value*convert_float4(gamma[index])+convert_float4(beta[index]);\n"
    "#else\n"
    " float4 out=in*value;\n"
    "#endif\n"
    " MASK_C4_TAIL(out,index,channelUnit,channelRemain);\n"
    " output1[idx]=CONVERT_FLOAT4(out);\n"
    " }\n"
    " }\n"
    "#endif\n"
    "}\n"
    "__kernel void layernorm_buf(__private int global_dim0,__private int global_dim1,\n"
    " __global const FLOAT*input,\n"
    " __global FLOAT*output,\n"
    " __private const int inside,\n"
    "#ifdef GAMMA_BETA\n"
    " __global const FLOAT *gamma,\n"
    " __global const FLOAT *beta,\n"
    "#endif\n"
    " __private float epsilon){\n"
    " int2 pos=(int2)(get_global_id(0),get_global_id(1));\n"
    "#if LOCAL_SIZE>1\n"
    " float local sum_mnn[LOCAL_SIZE];\n"
    " #ifndef RMSNORM\n"
    " float local sum_mean_mnn[LOCAL_SIZE];\n"
    " #endif\n"
    " if (pos.x<global_dim0 && pos.y<global_dim1) {\n"
    " const int lid=get_local_id(0);\n"
    " const int offset=pos.y*inside;\n"
    " const int inside_v4=(inside+3) >> 2;\n"
    " #ifdef PACK_LEAVE\n"
    " const int loop=inside_v4-1;\n"
    " const int inside_remain=inside-((inside_v4-1) << 2);\n"
    " #else\n"
    " const int loop=inside_v4;\n"
    " #endif\n"
    " \n"
    " float4 in_sum=0;\n"
    " int index=lid;\n"
    " #ifdef RMSNORM\n"
    " float4 mean=(float4)0;\n"
    " #else\n"
    " for(; index<loop; index+=LOCAL_SIZE){\n"
    " float4 in=convert_float4(vload4(index,input+offset));\n"
    " in_sum += in;\n"
    " }\n"
    " sum_mean_mnn[lid]=in_sum.x+in_sum.y+in_sum.z+ in_sum.w;\n"
    " \n"
    " #ifdef PACK_LEAVE\n"
    " if(index == inside_v4-1) {\n"
    " for(int i=0; i<inside_remain; ++i){\n"
    " float in=input[offset+index*4+i];\n"
    " sum_mean_mnn[lid]=sum_mean_mnn[lid]+in;\n"
    " }\n"
    " }\n"
    " #endif\n"
    " \n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
    " if (lid<i)\n"
    " sum_mean_mnn[lid]=sum_mean_mnn[lid]+sum_mean_mnn[lid+i];\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " }\n"
    " \n"
    " float4 mean=sum_mean_mnn[0]/(float4)inside;\n"
    " #endif\n"
    " in_sum=0;\n"
    " index=lid;\n"
    " for(; index<loop; index+=LOCAL_SIZE){\n"
    " float4 in=convert_float4(vload4(index,input+offset));\n"
    " in_sum += (in-mean)*(in-mean);\n"
    " }\n"
    " sum_mnn[lid]=in_sum.x+in_sum.y+in_sum.z+in_sum.w;\n"
    " #ifdef PACK_LEAVE\n"
    " if(index == inside_v4-1) {\n"
    " for(int i=0; i<inside_remain; ++i) {\n"
    " float in=input[offset+index*4+i];\n"
    " in=(in-mean.x)*(in-mean.x);\n"
    " sum_mnn[lid]=sum_mnn[lid]+in;\n"
    " }\n"
    " }\n"
    " #endif\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
    " if (lid<i)\n"
    " sum_mnn[lid]=sum_mnn[lid]+sum_mnn[lid+i];\n"
    " barrier(CLK_LOCAL_MEM_FENCE);\n"
    " }\n"
    " float4 square_sum=sum_mnn[0]/(float4)inside;\n"
    " float4 value=(float4)1.0f/(float4)sqrt(square_sum+(float4)epsilon);\n"
    " index=lid;\n"
    " for(; index<loop; index+=LOCAL_SIZE){\n"
    " float4 in=convert_float4(vload4(index,input+offset));\n"
    " #ifdef GAMMA_BETA\n"
    " float4 out=(in-mean)*value*convert_float4(vload4(index,gamma))+convert_float4(vload4(index,beta));\n"
    " #else\n"
    " float4 out=(in-mean)*value;\n"
    " #endif\n"
    " vstore4(CONVERT_FLOAT4(out),index,output+offset);\n"
    " }\n"
    " #ifdef PACK_LEAVE\n"
    " if(index == inside_v4-1) {\n"
    " for(int i=0; i<inside_remain; ++i){\n"
    " float in=input[offset+index*4+i];\n"
    " #ifdef GAMMA_BETA\n"
    " float out=(in-mean.x)*value.x*(float)gamma[index*4+i]+(float)beta[index*4+i];\n"
    " #else\n"
    " float out=(in-mean.x)*value.x;\n"
    " #endif\n"
    " output[offset+index*4+i]=out;\n"
    " }\n"
    " }\n"
    " #endif\n"
    " }\n"
    "#else\n"
    " if (pos.x<global_dim0 && pos.y<global_dim1) {\n"
    " const int offset=pos.y*inside;\n"
    " float in_sum=0;\n"
    " #ifdef RMSNORM\n"
    " float mean=0;\n"
    " #else\n"
    " for(int index=0; index<inside; index++){\n"
    " in_sum += (float)input[offset+index];\n"
    " }\n"
    " float mean=in_sum/inside;\n"
    " #endif\n"
    " in_sum=0;\n"
    " for(int index=0; index<inside; index++){\n"
    " float in=(float)input[offset+index];\n"
    " in_sum += (in-mean)*(in-mean);\n"
    " }\n"
    " float square_sum=in_sum/inside;\n"
    " float value=1.0f/sqrt(square_sum+epsilon);\n"
    " for(int i=0; i<inside; ++i){\n"
    " float in=input[offset+i];\n"
    " #ifdef GAMMA_BETA\n"
    " float out=(in-mean)*value*(float)gamma[i]+(float)beta[i];\n"
    " #else\n"
    " float out=(in-mean)*value;\n"
    " #endif\n"
    " output[offset+i]=out;\n"
    " }\n"
    " }\n"
    "#endif\n"
    "}\n";
#endif
} // namespace MNN
