#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* linear_attention_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"// Kernel 1: Depthwise Conv1D+SiLU\n"
"// Each work-item processes one (batch*channel,seq_pos) element.\n"
"// Input: qkv [B,D,L],conv_state [B,D,conv_state_size],conv_weight [D,1,K]\n"
"// Output: conv_out [B,D,L]\n"
"// conv_state is read but NOT updated here (updated by separate kernel).\n"
"__kernel void linear_attn_conv_silu(\n"
" __private const int global_dim0,\n"
" __global const FLOAT* qkv,\n"
" __global const FLOAT* conv_state,\n"
" __global const FLOAT* conv_weight,\n"
" __global FLOAT* conv_out,\n"
" __private const int batch,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int kernel_size,\n"
" __private const int conv_state_size)\n"
"{\n"
" const int gid=get_global_id(0);\n"
" if (gid >= global_dim0) return;\n"
" const int L=seq_len;\n"
" const int D=conv_dim;\n"
" const int K=kernel_size;\n"
" const int css=conv_state_size;\n"
" // Decompose: gid -> (batch_chan,seq_pos)\n"
" const int l=gid % L;\n"
" const int bd=gid/L;\n"
" const int b=bd/D;\n"
" const int d=bd % D;\n"
" // Compute valid convolution for position l\n"
" // Padded input=[conv_state[b,d,:],qkv[b,d,:]]\n"
" // padded[pos]: if pos<css -> conv_state[b*D*css+d*css+pos]\n"
" // else -> qkv[b*D*L+d*L+(pos-css)]\n"
" float sum=0.0f;\n"
" for (int k=0; k<K; ++k) {\n"
" int pos=l+k;\n"
" float input_val;\n"
" if (pos<css) {\n"
" input_val=(float)conv_state[b*D*css+d*css+pos];\n"
" } else {\n"
" input_val=(float)qkv[b*D*L+d*L+(pos-css)];\n"
" }\n"
" sum += input_val*(float)conv_weight[d*K+k];\n"
" }\n"
" // SiLU activation: x*sigmoid(x)\n"
" float sigmoid_val=1.0f/(1.0f+exp(-sum));\n"
" conv_out[b*D*L+d*L+l]=(FLOAT)(sum*sigmoid_val);\n"
"}\n"
"// Kernel 2: Update conv state with last (K-1) elements of padded input\n"
"// new_state[i]=padded[L+i],where padded=cat(old_state[css],qkv[L])\n"
"// Must execute AFTER linear_attn_conv_silu (which reads conv_state).\n"
"__kernel void linear_attn_conv_state_update(\n"
" __private const int global_dim0,\n"
" __global const FLOAT* qkv,\n"
" __global FLOAT* conv_state,\n"
" __private const int batch,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int conv_state_size)\n"
"{\n"
" const int gid=get_global_id(0);\n"
" if (gid >= global_dim0) return;\n"
" const int L=seq_len;\n"
" const int D=conv_dim;\n"
" const int css=conv_state_size;\n"
" const int i=gid % css;\n"
" const int bd=gid/css;\n"
" const int b=bd/D;\n"
" const int d=bd % D;\n"
" // new_state[i]=padded[L+i]\n"
" // padded=cat(old_state[css],qkv[L])\n"
" // position (L+i) in padded: if (L+i)<css -> old_state,else -> qkv[(L+i)-css]\n"
" int pos=L+i;\n"
" FLOAT val;\n"
" if (pos<css) {\n"
" val=conv_state[b*D*css+d*css+pos];\n"
" } else {\n"
" val=qkv[b*D*L+d*L+(pos-css)];\n"
" }\n"
" // Safe: we write to index i,read from index (L+i) where L >= 1,so (L+i)>i always\n"
" conv_state[b*D*css+d*css+i]=val;\n"
"}\n"
"// Kernel 3: Gated Delta Rule (Steps 2-5 fused)\n"
"// Each work-item processes one (batch,head) pair across all timesteps.\n"
"// Uses float32 exclusively for numerical stability of the recurrence.\n"
"__kernel void linear_attn_gated_delta_rule(\n"
" __global const FLOAT* conv_out,\n"
" __global const FLOAT* gate,\n"
" __global const FLOAT* beta_in,\n"
" __global FLOAT* recurrent_state,\n"
" __global FLOAT* attn_out,\n"
" __private const int batch,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int num_k_heads,\n"
" __private const int num_v_heads,\n"
" __private const int d_k,\n"
" __private const int d_v,\n"
" __private const int key_dim,\n"
" __private const int val_dim,\n"
" __private const int gqa_factor,\n"
" __private const float q_scale)\n"
"{\n"
" const int dv4=(d_v+3)/4;\n"
" const int total=dv4*num_v_heads*batch;\n"
" const int gid=get_global_id(1);\n"
" if (gid >= total) return;\n"
" const int x=(gid % dv4) << 2;\n"
" const int bh=gid/dv4;\n"
" const int h=bh % num_v_heads;\n"
" const int b=bh/num_v_heads;\n"
" const int k_head=h/gqa_factor; // GQA: corresponding K-head\n"
" __local float4 __sum[LOCAL_SIZE];\n"
" __local float4 rec_local[K_SIZE];\n"
" __local float key_local[K_SIZE];\n"
" const int lid=get_local_id(0);\n"
" // State pointer: recurrent_state layout [B,H,d_k,d_v]\n"
" const int state_offset=(b*num_v_heads+h)*K_SIZE*d_v+x;\n"
" #ifdef DECODE_PHASE\n"
" const int conv_base=b*conv_dim;\n"
" float g_t=(float)(gate[b*num_v_heads+h]);\n"
" float4 beta_t=(float4)(beta_in[b*num_v_heads+h]);\n"
" float4 decay_val=(float4)(exp(g_t));\n"
" const int out_offset=b*num_v_heads*d_v+h*d_v;\n"
" float4 s=(float4)(0);\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" float4 rec=convert_float4(vload4(0,recurrent_state+state_offset+i*d_v))* decay_val;\n"
" float key=(float)(conv_out[conv_base+key_dim+k_head*K_SIZE+i]);\n"
" s += rec*(float4)(key);\n"
" rec_local[i]=rec;\n"
" key_local[i]=key;\n"
" }\n"
" __sum[lid]=s;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" s=__sum[0];\n"
" float4 v_data=convert_float4(vload4(0,conv_out+conv_base+2*key_dim+h*d_v+x));\n"
" float4 delta=beta_t*(v_data-s);\n"
" s=(float4)(0);\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" float4 recurrent_state_data=rec_local[i]+(float4)(key_local[i])*delta;\n"
" s += recurrent_state_data*(float4)(conv_out[conv_base+(k_head*K_SIZE+i)])*(float4)(q_scale);\n"
" vstore4(CONVERT_FLOAT4(recurrent_state_data),0,recurrent_state+state_offset+i*d_v);\n"
" }\n"
" __sum[lid]=s;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" s=__sum[0];\n"
" if(lid == 0){\n"
" vstore4(CONVERT_FLOAT4(s),0,attn_out+out_offset+x);\n"
" }\n"
" #else\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" rec_local[i]=convert_float4(vload4(0,recurrent_state+state_offset+i*d_v));\n"
" }\n"
" for (int t=0; t<seq_len; ++t) {\n"
" const int conv_base=b*seq_len*conv_dim;\n"
" float g_t=(float)(gate[b*seq_len*num_v_heads+t*num_v_heads+h]);\n"
" float4 beta_t=(float4)(beta_in[b*seq_len*num_v_heads+t*num_v_heads+h]);\n"
" float4 decay_val=(float4)(exp(g_t));\n"
" const int out_offset=(b*seq_len+t)*num_v_heads*d_v+h*d_v;\n"
" float4 s=(float4)(0);\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" float4 rec=rec_local[i]*decay_val;\n"
" float key=(float)(conv_out[conv_base+(key_dim+k_head*K_SIZE+i)*seq_len+t]);\n"
" s += rec*(float4)(key);\n"
" key_local[i]=key;\n"
" }\n"
" __sum[lid]=s;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" s=__sum[0];\n"
" float4 v_data;\n"
" v_data.x=(float)(conv_out[conv_base+(2*key_dim+h*d_v+x)*seq_len+t]);\n"
" v_data.y=(float)(conv_out[conv_base+(2*key_dim+h*d_v+x+1)*seq_len+t]);\n"
" v_data.z=(float)(conv_out[conv_base+(2*key_dim+h*d_v+x+2)*seq_len+t]);\n"
" v_data.w=(float)(conv_out[conv_base+(2*key_dim+h*d_v+x+3)*seq_len+t]);\n"
" float4 delta=beta_t*(v_data-s);\n"
" s=(float4)(0);\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" float4 recurrent_state_data=rec_local[i]*decay_val+(float4)(key_local[i])*delta;\n"
" s += recurrent_state_data*(float4)(conv_out[conv_base+(k_head*K_SIZE+i)*seq_len+t])*(float4)(q_scale);\n"
" rec_local[i]=recurrent_state_data;\n"
" }\n"
" __sum[lid]=s;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" s=__sum[0];\n"
" if(lid == 0){\n"
" vstore4(CONVERT_FLOAT4(s),0,attn_out+out_offset+x);\n"
" }\n"
" }\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" vstore4(CONVERT_FLOAT4(rec_local[i]),0,recurrent_state+state_offset+i*d_v);\n"
" }\n"
" #endif\n"
"}\n"
"__kernel void l2_norm(__global const FLOAT* input,\n"
" __global FLOAT* output,\n"
" __private const int conv_dim,\n"
" __private const int head_k_dim,\n"
" __private const int gqa_factor,\n"
" __private const int key_dim,\n"
" __private const int seq_len)\n"
"{\n"
" #ifdef USE_VEC\n"
" const int hl=get_global_id(1);\n"
" const int bk=get_global_id(2);\n"
" const int seq_len4=(seq_len+3)/4;\n"
" const int h=hl/seq_len4;\n"
" const int sq=hl % seq_len4;\n"
" const int b=bk/2;\n"
" const int k=bk % 2;\n"
" const int lid=get_local_id(0);\n"
" const int k_head=h/gqa_factor; // GQA: corresponding K-head\n"
" const int input_offset=(b*conv_dim+k*key_dim+k_head*head_k_dim)*seq_len+(sq << 2);\n"
" __local float4 __sum[K_SIZE];\n"
" float4 sum=0.0f;\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float4 in=convert_float4(vload4(0,input+input_offset+i*seq_len));\n"
" sum += in*in;\n"
" }\n"
" __sum[lid]=sum;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=K_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" sum=__sum[0];\n"
" int remain=seq_len-(sq << 2);\n"
" float4 invNorm=(float4)1.0f/sqrt(sum+(float4)1e-6f);\n"
" if(remain == 1){\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float4 out=convert_float4(vload4(0,input+input_offset+i*seq_len))*invNorm;\n"
" output[input_offset+i*seq_len]=(FLOAT)out.s0;\n"
" }\n"
" }else if(remain == 2){\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float4 out=convert_float4(vload4(0,input+input_offset+i*seq_len))*invNorm;\n"
" vstore2(CONVERT_FLOAT2(out.s01),0,output+input_offset+i*seq_len);\n"
" }\n"
" }else if(remain == 3){\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float4 out=convert_float4(vload4(0,input+input_offset+i*seq_len))*invNorm;\n"
" vstore3(CONVERT_FLOAT3(out.s012),0,output+input_offset+i*seq_len);\n"
" }\n"
" }else{\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float4 out=convert_float4(vload4(0,input+input_offset+i*seq_len))*invNorm;\n"
" vstore4(CONVERT_FLOAT4(out),0,output+input_offset+i*seq_len);\n"
" }\n"
" }\n"
" #else\n"
" const int h=get_global_id(1);\n"
" const int bk=get_global_id(2);\n"
" const int b=bk/2;\n"
" const int k=bk % 2;\n"
" const int lid=get_local_id(0);\n"
" const int k_head=h/gqa_factor; // GQA: corresponding K-head\n"
" const int input_offset=b*conv_dim+k*key_dim+k_head*head_k_dim;\n"
" __local float __sum[K_SIZE];\n"
" float sum=0.0f;\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float in=(float)(input[input_offset+i]);\n"
" sum += in*in;\n"
" }\n"
" __sum[lid]=sum;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=K_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" sum=__sum[0];\n"
" float invNorm=1.0f/sqrt(sum+1e-6f);\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float out=(float)(input[input_offset+i])*invNorm;\n"
" output[input_offset+i]=(FLOAT)out;\n"
" }\n"
" #endif\n"
"}\n"
"#ifdef CHUNK_PREFILL\n"
"// ======================== Chunked Prefill Kernels ========================\n"
"// Implements torch_chunk_gated_delta_rule from modeling_qwen3_5.py\n"
"// Decomposes sequential recurrence into chunk-parallel operations.\n"
"// CHUNK_SIZE must be defined at compile time (e.g. -DCHUNK_SIZE=64).\n"
"// Kernel C1: Cumulative sum of gate values within each chunk\n"
"// GWS: {num_v_heads,num_chunks,batch}\n"
"__kernel void chunk_g_cumsum(\n"
" __global const FLOAT* gate,// [B,L,H]\n"
" __global float* g_cumsum,// [B,H,num_chunks,CHUNK_SIZE] (float32 for precision)\n"
" __private const int num_v_heads,\n"
" __private const int seq_len,\n"
" __private const int num_chunks)\n"
"{\n"
" const int h=get_global_id(0);\n"
" const int c=get_global_id(1);\n"
" const int b=get_global_id(2);\n"
" if (h >= num_v_heads || c >= num_chunks) return;\n"
" const int H=num_v_heads;\n"
" const int L=seq_len;\n"
" const int C=CHUNK_SIZE;\n"
" float cumsum=0.0f;\n"
" int out_base=((b*H+h)*num_chunks+c)*C;\n"
" for (int p=0; p<C; ++p) {\n"
" int l=c*C+p;\n"
" float g_val=(l<L) ? (float)gate[b*L*H+l*H+h] : 0.0f;\n"
" cumsum += g_val;\n"
" g_cumsum[out_base+p]=cumsum;\n"
" }\n"
"}\n"
"// Kernel C2: Build Neumann-corrected intra-chunk attention matrix\n"
"// attn=I+neumann_correction(-(k_beta @ k^T)*decay_mask)\n"
"// GWS: {CHUNK_SIZE,num_v_heads*num_chunks,batch},LWS: {CHUNK_SIZE,1,1}\n"
"__kernel void chunk_build_neumann_attn_step0(\n"
" __global const FLOAT* conv_out,// [B,D,L]\n"
" __global const FLOAT* beta_in,// [B,L,H]\n"
" __global const float* g_cumsum,// [B,H,num_chunks,C] (float32)\n"
" __global float* attn_matrix,// [B,H,num_chunks,C,C] (float32)\n"
" __private const int batch,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int num_v_heads,\n"
" __private const int head_k_dim,\n"
" __private const int key_dim,\n"
" __private const int gqa_factor,\n"
" __private const int num_chunks)\n"
"{\n"
" const int rc=get_global_id(0);\n"
" const int hc=get_global_id(1);\n"
" const int b=get_global_id(2);\n"
" if (hc >= num_v_heads*num_chunks || b >= batch || rc >= CHUNK_SIZE*CHUNK_SIZE) return;\n"
" const int col=rc % CHUNK_SIZE;\n"
" const int row=rc/CHUNK_SIZE;\n"
" const int h=hc/num_chunks;\n"
" const int c=hc % num_chunks;\n"
" const int C=CHUNK_SIZE;\n"
" const int dk=head_k_dim;\n"
" const int D=conv_dim;\n"
" const int L=seq_len;\n"
" const int H=num_v_heads;\n"
" const int k_head=h/gqa_factor;\n"
" const int g_base=((b*H+h)*num_chunks+c)*C;\n"
" const int attn_out_base=((b*H+h)*num_chunks+c)*C*C;\n"
" const int conv_base=b*D*L;\n"
" \n"
" // Phase 1: Compute strictly-lower-triangular attn\n"
" // attn[i,j]=-(k[i]*beta[i]) dot k[j]*exp(g[i]-g[j])\n"
" float val=0.0f;\n"
" if (col<row) {\n"
" const int l_i=c*C+row;\n"
" const int l_j=c*C+col;\n"
" if (l_i<L && l_j<L) {\n"
" const float g_i=(float)g_cumsum[g_base+row];\n"
" const float beta_i=(float)beta_in[b*L*H+l_i*H+h];\n"
" const float g_j=(float)g_cumsum[g_base+col];\n"
" const float decay=exp(g_i-g_j);\n"
" float dot=0.0f;\n"
" for (int d=0; d<dk; ++d) {\n"
" float k_i_d=(float)conv_out[conv_base+(key_dim+k_head*dk+d)*L+l_i];\n"
" float k_j_d=(float)conv_out[conv_base+(key_dim+k_head*dk+d)*L+l_j];\n"
" dot += k_i_d*k_j_d;\n"
" }\n"
" val=-(beta_i*dot)*decay;\n"
" }\n"
" }\n"
" attn_matrix[attn_out_base+row*C+col]=val;\n"
"}\n"
"__kernel void chunk_build_neumann_attn_step1(\n"
" __global float* attn_matrix,// [B,H,num_chunks,C,C] (float32)\n"
" __private const int batch,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int num_v_heads,\n"
" __private const int head_k_dim,\n"
" __private const int key_dim,\n"
" __private const int gqa_factor,\n"
" __private const int num_chunks)\n"
"{\n"
" const int col=get_global_id(0);\n"
" const int hc=get_global_id(1);\n"
" const int b=get_global_id(2);\n"
" if (hc >= num_v_heads*num_chunks || b >= batch || col >= CHUNK_SIZE) return;\n"
" const int lid=get_local_id(0);\n"
" const int h=hc/num_chunks;\n"
" const int c=hc % num_chunks;\n"
" const int C=CHUNK_SIZE;\n"
" const int dk=head_k_dim;\n"
" const int D=conv_dim;\n"
" const int L=seq_len;\n"
" const int H=num_v_heads;\n"
" const int k_head=h/gqa_factor;\n"
" const int attn_out_base=((b*H+h)*num_chunks+c)*C*C;\n"
" \n"
" // Phase 2: Neumann series correction (row by row)\n"
" for (int r=1; r<C; ++r) {\n"
" float orig=attn_matrix[attn_out_base+r*C+lid];\n"
" float correction=0.0f;\n"
" if (lid<r) {\n"
" for (int k=0; k<r; ++k) {\n"
" correction += attn_matrix[attn_out_base+r*C+k]*attn_matrix[attn_out_base+k*C+lid];\n"
" }\n"
" }\n"
" if (lid<r) {\n"
" attn_matrix[attn_out_base+r*C+lid]=orig+correction;\n"
" }\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" // Phase 3: Add identity and write to global (float32)\n"
" attn_matrix[attn_out_base+lid*C+lid]=attn_matrix[attn_out_base+lid*C+lid]+1.0f;\n"
"}\n"
"// Kernel C3: v_corrected=attn_matrix @ (V*beta)\n"
"// GWS: {UP_DIV(dv,4),CHUNK_SIZE*num_chunks,B*H}\n"
"__kernel void chunk_correct_v(\n"
" __global const float* attn_matrix,// [B,H,num_chunks,C,C] (float32)\n"
" __global const FLOAT* conv_out,// [B,D,L]\n"
" __global const FLOAT* beta_in,// [B,L,H]\n"
" __global const float* g_cumsum,// [B,H,num_chunks,C] (float32)\n"
" __global float* v_corrected,// [B,H,num_chunks,C,dv] (float32)\n"
" __global float* k_cumdecay,// [B,H,num_chunks,C,dk] (float32)\n"
" __private const int global_dim0,\n"
" __private const int global_dim1,\n"
" __private const int global_dim2,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int num_v_heads,\n"
" __private const int head_k_dim,\n"
" __private const int head_v_dim,\n"
" __private const int key_dim,\n"
" __private const int num_chunks)\n"
"{\n"
" const int x=get_global_id(0);\n"
" const int y=get_global_id(1);\n"
" const int z=get_global_id(2);\n"
" if (x >= global_dim0 || y >= global_dim1 || z >= global_dim2) return;\n"
" const int j=x << 2;\n"
" const int c=y/CHUNK_SIZE;\n"
" const int row=y % CHUNK_SIZE;\n"
" const int b=z/num_v_heads;\n"
" const int h=z % num_v_heads;\n"
" const int C=CHUNK_SIZE;\n"
" const int dk=head_k_dim;\n"
" const int dv=head_v_dim;\n"
" const int D=conv_dim;\n"
" const int L=seq_len;\n"
" const int H=num_v_heads;\n"
" const int attn_base=((b*H+h)*num_chunks+c)*C*C+row*C;\n"
" const int g_base=((b*H+h)*num_chunks+c)*C;\n"
" const int conv_base=b*D*L;\n"
" float4 result0=(float4)(0.0f);\n"
" float4 result1=(float4)(0.0f);\n"
" int l_p=c*C;\n"
" for (int p=0; p<C && l_p<L; ++p,++l_p) {\n"
" float a=attn_matrix[attn_base+p];\n"
" float beta_p=(float)beta_in[b*L*H+l_p*H+h];\n"
" float ab=a*beta_p;\n"
" float g_p=g_cumsum[g_base+p];\n"
" float coeff=ab*exp(g_p);\n"
" float4 v_p;\n"
" v_p.x=(float)conv_out[conv_base+(2*key_dim+h*dv+j)*L+l_p];\n"
" v_p.y=(float)conv_out[conv_base+(2*key_dim+h*dv+j+1)*L+l_p];\n"
" v_p.z=(float)conv_out[conv_base+(2*key_dim+h*dv+j+2)*L+l_p];\n"
" v_p.w=(float)conv_out[conv_base+(2*key_dim+h*dv+j+3)*L+l_p];\n"
" result0 += ab*v_p;\n"
" float4 k_p;\n"
" k_p.x=(float)conv_out[conv_base+(key_dim+h*dk+j)*L+l_p];\n"
" k_p.y=(float)conv_out[conv_base+(key_dim+h*dk+j+1)*L+l_p];\n"
" k_p.z=(float)conv_out[conv_base+(key_dim+h*dk+j+2)*L+l_p];\n"
" k_p.w=(float)conv_out[conv_base+(key_dim+h*dk+j+3)*L+l_p];\n"
" result1 += coeff*k_p;\n"
" }\n"
" int out_idx=((b*H+h)*num_chunks+c)*C*dv+row*dv+j;\n"
" vstore4((float4)(result0),0,v_corrected+out_idx);\n"
" vstore4((float4)(result1),0,k_cumdecay+out_idx);\n"
"}\n"
"// Kernel C5: Intra-chunk QK attention with decay (lower triangular including diagonal)\n"
"// qk[i,j]=(q[i] dot k[j])*q_scale*exp(g[i]-g[j]) for j <= i\n"
"// GWS: {CHUNK_SIZE,CHUNK_SIZE*num_chunks,B*H}\n"
"__kernel void chunk_qk_attn(\n"
" __global const FLOAT* conv_out,// [B,D,L]\n"
" __global const float* g_cumsum,// [B,H,num_chunks,C] (float32)\n"
" __global float* qk_attn_out,// [B,H,num_chunks,C,C] (float32,reuses attn_matrix buf)\n"
" __private const int global_dim0,\n"
" __private const int global_dim1,\n"
" __private const int global_dim2,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int num_v_heads,\n"
" __private const int head_k_dim,\n"
" __private const int key_dim,\n"
" __private const int gqa_factor,\n"
" __private const int num_chunks,\n"
" __private const float q_scale)\n"
"{\n"
" const int col=get_global_id(0);\n"
" const int y=get_global_id(1);\n"
" const int z=get_global_id(2);\n"
" if (col >= global_dim0 || y >= global_dim1 || z >= global_dim2) return;\n"
" const int c=y/CHUNK_SIZE;\n"
" const int row=y % CHUNK_SIZE;\n"
" const int b=z/num_v_heads;\n"
" const int h=z % num_v_heads;\n"
" const int C=CHUNK_SIZE;\n"
" const int dk=head_k_dim;\n"
" const int D=conv_dim;\n"
" const int L=seq_len;\n"
" const int H=num_v_heads;\n"
" const int k_head=h/gqa_factor;\n"
" float val=0.0f;\n"
" if (col <= row) {\n"
" const int l_row=c*C+row;\n"
" const int l_col=c*C+col;\n"
" if (l_row<L && l_col<L) {\n"
" const int g_base=((b*H+h)*num_chunks+c)*C;\n"
" const float decay=exp(g_cumsum[g_base+row]-g_cumsum[g_base+col]);\n"
" const int conv_base=b*D*L;\n"
" float dot=0.0f;\n"
" for (int d=0; d<dk; ++d) {\n"
" float q_d=(float)conv_out[conv_base+(k_head*dk+d)*L+l_row];\n"
" float k_d=(float)conv_out[conv_base+(key_dim+k_head*dk+d)*L+l_col];\n"
" dot += q_d*k_d;\n"
" }\n"
" val=dot*q_scale*decay;\n"
" }\n"
" }\n"
" int out_idx=((b*H+h)*num_chunks+c)*C*C+row*C+col;\n"
" qk_attn_out[out_idx]=val;\n"
"}\n"
"// Kernel C6: v_new=v_corrected-k_cumdecay @ state (per chunk)\n"
"// GWS: {UP_DIV(dv,4),CHUNK_SIZE,B*H}\n"
"__kernel void chunk_compute_vnew(\n"
" __global const float* v_corrected,// [B,H,num_chunks,C,dv] (float32)\n"
" __global const float* k_cumdecay,// [B,H,num_chunks,C,dk] (float32)\n"
" __global const FLOAT* recurrent_state,// [B,H,dk,dv]\n"
" __global float* v_new,// [B,H,C,dv] (float32)\n"
" __private const int global_dim0,\n"
" __private const int global_dim1,\n"
" __private const int global_dim2,\n"
" __private const int head_k_dim,\n"
" __private const int head_v_dim,\n"
" __private const int num_v_heads,\n"
" __private const int num_chunks,\n"
" __private const int chunk_idx)\n"
"{\n"
" const int x=get_global_id(0);\n"
" const int p=get_global_id(1);\n"
" const int z=get_global_id(2);\n"
" if (x >= global_dim0 || p >= global_dim1 || z >= global_dim2) return;\n"
" const int j=x << 2;\n"
" const int b=z/num_v_heads;\n"
" const int h=z % num_v_heads;\n"
" const int C=CHUNK_SIZE;\n"
" const int dk=head_k_dim;\n"
" const int dv=head_v_dim;\n"
" const int H=num_v_heads;\n"
" const int c=chunk_idx;\n"
" const int kc_base=((b*H+h)*num_chunks+c)*C*dk+p*dk;\n"
" const int state_base=(b*H+h)*dk*dv;\n"
" float4 v_prime=(float4)(0.0f);\n"
" for (int d=0; d<dk; ++d) {\n"
" float kc_d=k_cumdecay[kc_base+d];\n"
" float4 s=convert_float4(vload4(0,recurrent_state+state_base+d*dv+j));\n"
" v_prime += kc_d*s;\n"
" }\n"
" int vc_idx=((b*H+h)*num_chunks+c)*C*dv+p*dv+j;\n"
" float4 vc=vload4(0,v_corrected+vc_idx);\n"
" float4 vn=vc-v_prime;\n"
" int vn_idx=(b*H+h)*C*dv+p*dv+j;\n"
" vstore4((float4)(vn),0,v_new+vn_idx);\n"
"}\n"
"// Kernel C7: Compute output and update recurrent state (per chunk)\n"
"// GWS: {dk*UP_DIV(dv,4),H,batch}\n"
"__kernel void chunk_output_state_update(\n"
" __global const FLOAT* conv_out,// [B,D,L]\n"
" __global const float* qk_attn_matrix,// [B,H,num_chunks,C,C] (float32)\n"
" __global const float* v_new,// [B,H,C,dv] (float32)\n"
" __global const float* g_cumsum,// [B,H,num_chunks,C] (float32)\n"
" __global FLOAT* recurrent_state,// [B,H,dk,dv]\n"
" __global FLOAT* attn_out,// [B,L,H*dv]\n"
" __private const int global_dim0,\n"
" __private const int global_dim1,\n"
" __private const int global_dim2,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int num_v_heads,\n"
" __private const int head_k_dim,\n"
" __private const int head_v_dim,\n"
" __private const int key_dim,\n"
" __private const int gqa_factor,\n"
" __private const int num_chunks,\n"
" __private const int chunk_idx,\n"
" __private const float q_scale)\n"
"{\n"
" const int x=get_global_id(0);\n"
" const int h=get_global_id(1);\n"
" const int b=get_global_id(2);\n"
" if (x >= global_dim0 || h >= global_dim1 || b >= global_dim2) return;\n"
" \n"
" const int dk=head_k_dim;\n"
" const int dv=head_v_dim;\n"
" const int dv4=(dv+3)/4;\n"
" const int j=(x % dv4) << 2;\n"
" const int d=x/dv4;\n"
" const int C=CHUNK_SIZE;\n"
" const int D=conv_dim;\n"
" const int L=seq_len;\n"
" const int H=num_v_heads;\n"
" const int c=chunk_idx;\n"
" const int k_head=h/gqa_factor;\n"
" const int state_base=(b*H+h)*dk*dv;\n"
" const int g_base=((b*H+h)*num_chunks+c)*C;\n"
" const int qk_base=((b*H+h)*num_chunks+c)*C*C;\n"
" const int vn_base=(b*H+h)*C*dv;\n"
" const int conv_base=b*D*L;\n"
" int last_p=min(C,L-c*C);\n"
" if (last_p <= 0) return;\n"
" // Phase 2: Update recurrent state\n"
" // state[d,j]=state[d,j]*exp(g_last)+sum_p k[p,d]*exp(g_last-g[p])*v_new[p,j]\n"
" float g_last=g_cumsum[g_base+last_p-1];\n"
" float decay_state=exp(g_last);\n"
" float4 s=convert_float4(vload4(0,recurrent_state+state_base+d*dv+j))*(float4)(decay_state);\n"
" for (int p=0; p<last_p; ++p) {\n"
" int l_p=c*C+p;\n"
" float g_p=g_cumsum[g_base+p];\n"
" float k_d=(float)conv_out[conv_base+(key_dim+k_head*dk+d)*L+l_p]*exp(g_last-g_p);\n"
" float4 vn=vload4(0,v_new+vn_base+p*dv+j);\n"
" s += k_d*vn;\n"
" }\n"
" vstore4(CONVERT_FLOAT4(s),0,recurrent_state+state_base+d*dv+j);\n"
"}\n"
"__kernel void chunk_output(\n"
" __global const FLOAT* conv_out,// [B,D,L]\n"
" __global const float* qk_attn_matrix,// [B,H,num_chunks,C,C] (float32)\n"
" __global const float* v_new,// [B,H,C,dv] (float32)\n"
" __global const float* g_cumsum,// [B,H,num_chunks,C] (float32)\n"
" __global const FLOAT* recurrent_state,// [B,H,dk,dv]\n"
" __global FLOAT* attn_out,// [B,L,H*dv]\n"
" __private const int global_dim0,\n"
" __private const int global_dim1,\n"
" __private const int global_dim2,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int num_v_heads,\n"
" __private const int dk,\n"
" __private const int dv,\n"
" __private const int key_dim,\n"
" __private const int gqa_factor,\n"
" __private const int num_chunks,\n"
" __private const int chunk_idx,\n"
" __private const float q_scale)\n"
"{\n"
" const int x=get_global_id(0);\n"
" const int h=get_global_id(1);\n"
" const int b=get_global_id(2);\n"
" if (x >= global_dim0 || h >= global_dim1 || b >= global_dim2) return;\n"
" \n"
" const int dv4=(dv+3)/4;\n"
" const int j=(x % dv4) << 2;\n"
" const int p=x/dv4;\n"
" const int C=CHUNK_SIZE;\n"
" const int D=conv_dim;\n"
" const int L=seq_len;\n"
" const int H=num_v_heads;\n"
" const int c=chunk_idx;\n"
" const int k_head=h/gqa_factor;\n"
" const int state_base=(b*H+h)*dk*dv;\n"
" const int g_base=((b*H+h)*num_chunks+c)*C;\n"
" const int qk_base=((b*H+h)*num_chunks+c)*C*C;\n"
" const int vn_base=(b*H+h)*C*dv;\n"
" const int conv_base=b*D*L;\n"
" int last_p=min(C,L-c*C);\n"
" if (last_p <= 0 || p >= last_p) return;\n"
" // Phase 1: Compute output for each position p\n"
" int l_p=c*C+p;\n"
" float g_p=g_cumsum[g_base+p];\n"
" float decay_q=exp(g_p)*q_scale;\n"
" // Cross-chunk: q*scale*exp(g) @ state\n"
" float4 inter=(float4)(0.0f);\n"
" for (int d=0; d<dk; d++) {\n"
" float q_d=(float)conv_out[conv_base+(k_head*dk+d)*L+l_p]*decay_q;\n"
" float4 s=convert_float4(vload4(0,recurrent_state+state_base+d*dv+j));\n"
" inter += q_d*s;\n"
" }\n"
" \n"
" // Intra-chunk: qk_attn @ v_new\n"
" float4 intra=(float4)(0.0f);\n"
" for (int r=0; r <= p; ++r) {\n"
" float qk=qk_attn_matrix[qk_base+p*C+r];\n"
" float4 vn=vload4(0,v_new+vn_base+r*dv+j);\n"
" intra += qk*vn;\n"
" }\n"
" const int out_offset=(b*L+l_p)*H*dv+h*dv+j;\n"
" vstore4(CONVERT_FLOAT4(inter+intra),0,attn_out+out_offset);\n"
"}\n"
"#endif // CHUNK_PREFILL\n"
;
#endif
}
