#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* linear_attention_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"// Kernel 1: Depthwise Conv1D+SiLU\n"
"// Each work-item processes one (batch*channel,seq_pos) element.\n"
"// Input: qkv [B,D,L],conv_state [B,D,conv_state_size],conv_weight [D,1,K]\n"
"// Output: conv_out [B,D,L]\n"
"// conv_state is read but NOT updated here (updated by separate kernel).\n"
"__kernel void linear_attn_conv_silu(\n"
" __private const int global_dim0,\n"
" __global const FLOAT* qkv,\n"
" __global const FLOAT* conv_state,\n"
" __global const FLOAT* conv_weight,\n"
" __global FLOAT* conv_out,\n"
" __private const int batch,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int kernel_size,\n"
" __private const int conv_state_size)\n"
"{\n"
" const int gid=get_global_id(0);\n"
" if (gid >= global_dim0) return;\n"
" const int L=seq_len;\n"
" const int D=conv_dim;\n"
" const int K=kernel_size;\n"
" const int css=conv_state_size;\n"
" // Decompose: gid -> (batch_chan,seq_pos)\n"
" const int l=gid % L;\n"
" const int bd=gid/L;\n"
" const int b=bd/D;\n"
" const int d=bd % D;\n"
" // Compute valid convolution for position l\n"
" // Padded input=[conv_state[b,d,:],qkv[b,d,:]]\n"
" // padded[pos]: if pos<css -> conv_state[b*D*css+d*css+pos]\n"
" // else -> qkv[b*D*L+d*L+(pos-css)]\n"
" float sum=0.0f;\n"
" for (int k=0; k<K; ++k) {\n"
" int pos=l+k;\n"
" float input_val;\n"
" if (pos<css) {\n"
" input_val=(float)conv_state[b*D*css+d*css+pos];\n"
" } else {\n"
" input_val=(float)qkv[b*D*L+d*L+(pos-css)];\n"
" }\n"
" sum += input_val*(float)conv_weight[d*K+k];\n"
" }\n"
" // SiLU activation: x*sigmoid(x)\n"
" float sigmoid_val=1.0f/(1.0f+exp(-sum));\n"
" conv_out[b*D*L+d*L+l]=(FLOAT)(sum*sigmoid_val);\n"
"}\n"
"// Kernel 2: Update conv state with last (K-1) elements of padded input\n"
"// new_state[i]=padded[L+i],where padded=cat(old_state[css],qkv[L])\n"
"// Must execute AFTER linear_attn_conv_silu (which reads conv_state).\n"
"__kernel void linear_attn_conv_state_update(\n"
" __private const int global_dim0,\n"
" __global const FLOAT* qkv,\n"
" __global FLOAT* conv_state,\n"
" __private const int batch,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int conv_state_size)\n"
"{\n"
" const int gid=get_global_id(0);\n"
" if (gid >= global_dim0) return;\n"
" const int L=seq_len;\n"
" const int D=conv_dim;\n"
" const int css=conv_state_size;\n"
" const int i=gid % css;\n"
" const int bd=gid/css;\n"
" const int b=bd/D;\n"
" const int d=bd % D;\n"
" // new_state[i]=padded[L+i]\n"
" // padded=cat(old_state[css],qkv[L])\n"
" // position (L+i) in padded: if (L+i)<css -> old_state,else -> qkv[(L+i)-css]\n"
" int pos=L+i;\n"
" FLOAT val;\n"
" if (pos<css) {\n"
" val=conv_state[b*D*css+d*css+pos];\n"
" } else {\n"
" val=qkv[b*D*L+d*L+(pos-css)];\n"
" }\n"
" // Safe: we write to index i,read from index (L+i) where L >= 1,so (L+i)>i always\n"
" conv_state[b*D*css+d*css+i]=val;\n"
"}\n"
"// Kernel 3: Gated Delta Rule (Steps 2-5 fused)\n"
"// Each work-item processes one (batch,head) pair across all timesteps.\n"
"// Uses float32 exclusively for numerical stability of the recurrence.\n"
"__kernel void linear_attn_gated_delta_rule(\n"
" __global const FLOAT* conv_out,\n"
" __global const FLOAT* gate,\n"
" __global const FLOAT* beta_in,\n"
" __global FLOAT* recurrent_state,\n"
" __global FLOAT* attn_out,\n"
" __private const int batch,\n"
" __private const int conv_dim,\n"
" __private const int seq_len,\n"
" __private const int num_k_heads,\n"
" __private const int num_v_heads,\n"
" __private const int d_k,\n"
" __private const int d_v,\n"
" __private const int key_dim,\n"
" __private const int val_dim,\n"
" __private const int gqa_factor,\n"
" __private const float q_scale)\n"
"{\n"
" const int dv4=(d_v+3)/4;\n"
" const int total=dv4*num_v_heads*batch;\n"
" const int gid=get_global_id(1);\n"
" if (gid >= total) return;\n"
" const int x=(gid % dv4) << 2;\n"
" const int bh=gid/dv4;\n"
" const int h=bh % num_v_heads;\n"
" const int b=bh/num_v_heads;\n"
" const int k_head=h/gqa_factor; // GQA: corresponding K-head\n"
" __local float4 __sum[LOCAL_SIZE];\n"
" __local float4 rec_local[K_SIZE];\n"
" __local float key_local[K_SIZE];\n"
" const int lid=get_local_id(0);\n"
" // State pointer: recurrent_state layout [B,H,d_k,d_v]\n"
" const int state_offset=(b*num_v_heads+h)*K_SIZE*d_v+x;\n"
" #ifdef DECODE_PHASE\n"
" const int conv_base=b*conv_dim;\n"
" float g_t=(float)(gate[b*num_v_heads+h]);\n"
" float4 beta_t=(float4)(beta_in[b*num_v_heads+h]);\n"
" float4 decay_val=(float4)(exp(g_t));\n"
" const int out_offset=b*num_v_heads*d_v+h*d_v;\n"
" float4 s=(float4)(0);\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" float4 rec=convert_float4(vload4(0,recurrent_state+state_offset+i*d_v))* decay_val;\n"
" float key=(float)(conv_out[conv_base+key_dim+k_head*K_SIZE+i]);\n"
" s += rec*(float4)(key);\n"
" rec_local[i]=rec;\n"
" key_local[i]=key;\n"
" }\n"
" __sum[lid]=s;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" s=__sum[0];\n"
" float4 v_data=convert_float4(vload4(0,conv_out+conv_base+2*key_dim+h*d_v+x));\n"
" float4 delta=beta_t*(v_data-s);\n"
" s=(float4)(0);\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" float4 recurrent_state_data=rec_local[i]+(float4)(key_local[i])*delta;\n"
" s += recurrent_state_data*(float4)(conv_out[conv_base+(k_head*K_SIZE+i)])*(float4)(q_scale);\n"
" vstore4(CONVERT_FLOAT4(recurrent_state_data),0,recurrent_state+state_offset+i*d_v);\n"
" }\n"
" __sum[lid]=s;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" s=__sum[0];\n"
" if(lid == 0){\n"
" vstore4(CONVERT_FLOAT4(s),0,attn_out+out_offset+x);\n"
" }\n"
" #else\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" rec_local[i]=convert_float4(vload4(0,recurrent_state+state_offset+i*d_v));\n"
" }\n"
" for (int t=0; t<seq_len; ++t) {\n"
" const int conv_base=b*seq_len*conv_dim;\n"
" float g_t=(float)(gate[b*seq_len*num_v_heads+t*num_v_heads+h]);\n"
" float4 beta_t=(float4)(beta_in[b*seq_len*num_v_heads+t*num_v_heads+h]);\n"
" float4 decay_val=(float4)(exp(g_t));\n"
" const int out_offset=(b*seq_len+t)*num_v_heads*d_v+h*d_v;\n"
" float4 s=(float4)(0);\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" float4 rec=rec_local[i]*decay_val;\n"
" float key=(float)(conv_out[conv_base+(key_dim+k_head*K_SIZE+i)*seq_len+t]);\n"
" s += rec*(float4)(key);\n"
" key_local[i]=key;\n"
" }\n"
" __sum[lid]=s;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" s=__sum[0];\n"
" float4 v_data;\n"
" v_data.x=(float)(conv_out[conv_base+(2*key_dim+h*d_v+x)*seq_len+t]);\n"
" v_data.y=(float)(conv_out[conv_base+(2*key_dim+h*d_v+x+1)*seq_len+t]);\n"
" v_data.z=(float)(conv_out[conv_base+(2*key_dim+h*d_v+x+2)*seq_len+t]);\n"
" v_data.w=(float)(conv_out[conv_base+(2*key_dim+h*d_v+x+3)*seq_len+t]);\n"
" float4 delta=beta_t*(v_data-s);\n"
" s=(float4)(0);\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" float4 recurrent_state_data=rec_local[i]*decay_val+(float4)(key_local[i])*delta;\n"
" s += recurrent_state_data*(float4)(conv_out[conv_base+(k_head*K_SIZE+i)*seq_len+t])*(float4)(q_scale);\n"
" rec_local[i]=recurrent_state_data;\n"
" }\n"
" __sum[lid]=s;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=LOCAL_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" s=__sum[0];\n"
" if(lid == 0){\n"
" vstore4(CONVERT_FLOAT4(s),0,attn_out+out_offset+x);\n"
" }\n"
" }\n"
" for (int i=lid; i<K_SIZE; i+=LOCAL_SIZE) {\n"
" vstore4(CONVERT_FLOAT4(rec_local[i]),0,recurrent_state+state_offset+i*d_v);\n"
" }\n"
" #endif\n"
"}\n"
"__kernel void l2_norm(__global const FLOAT* input,\n"
" __global FLOAT* output,\n"
" __private const int conv_dim,\n"
" __private const int head_k_dim,\n"
" __private const int gqa_factor,\n"
" __private const int key_dim,\n"
" __private const int seq_len)\n"
"{\n"
" #ifdef USE_VEC\n"
" const int hl=get_global_id(1);\n"
" const int bk=get_global_id(2);\n"
" const int seq_len4=(seq_len+3)/4;\n"
" const int h=hl/seq_len4;\n"
" const int sq=hl % seq_len4;\n"
" const int b=bk/2;\n"
" const int k=bk % 2;\n"
" const int lid=get_local_id(0);\n"
" const int k_head=h/gqa_factor; // GQA: corresponding K-head\n"
" const int input_offset=(b*conv_dim+k*key_dim+k_head*head_k_dim)*seq_len+(sq << 2);\n"
" __local float4 __sum[K_SIZE];\n"
" float4 sum=0.0f;\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float4 in=convert_float4(vload4(0,input+input_offset+i*seq_len));\n"
" sum += in*in;\n"
" }\n"
" __sum[lid]=sum;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=K_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" sum=__sum[0];\n"
" int remain=seq_len-(sq << 2);\n"
" float4 invNorm=(float4)1.0f/sqrt(sum+(float4)1e-6f);\n"
" if(remain == 1){\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float4 out=convert_float4(vload4(0,input+input_offset+i*seq_len))*invNorm;\n"
" output[input_offset+i*seq_len]=(FLOAT)out.s0;\n"
" }\n"
" }else if(remain == 2){\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float4 out=convert_float4(vload4(0,input+input_offset+i*seq_len))*invNorm;\n"
" vstore2(CONVERT_FLOAT2(out.s01),0,output+input_offset+i*seq_len);\n"
" }\n"
" }else if(remain == 3){\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float4 out=convert_float4(vload4(0,input+input_offset+i*seq_len))*invNorm;\n"
" vstore3(CONVERT_FLOAT3(out.s012),0,output+input_offset+i*seq_len);\n"
" }\n"
" }else{\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float4 out=convert_float4(vload4(0,input+input_offset+i*seq_len))*invNorm;\n"
" vstore4(CONVERT_FLOAT4(out),0,output+input_offset+i*seq_len);\n"
" }\n"
" }\n"
" #else\n"
" const int h=get_global_id(1);\n"
" const int bk=get_global_id(2);\n"
" const int b=bk/2;\n"
" const int k=bk % 2;\n"
" const int lid=get_local_id(0);\n"
" const int k_head=h/gqa_factor; // GQA: corresponding K-head\n"
" const int input_offset=b*conv_dim+k*key_dim+k_head*head_k_dim;\n"
" __local float __sum[K_SIZE];\n"
" float sum=0.0f;\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float in=(float)(input[input_offset+i]);\n"
" sum += in*in;\n"
" }\n"
" __sum[lid]=sum;\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" for(int i=K_SIZE/2; i>0; i /= 2){\n"
" if (lid<i)\n"
" __sum[lid] += __sum[lid+i];\n"
" barrier(CLK_LOCAL_MEM_FENCE);\n"
" }\n"
" sum=__sum[0];\n"
" float invNorm=1.0f/sqrt(sum+1e-6f);\n"
" for(int i=lid; i<K_SIZE; i += K_SIZE){\n"
" float out=(float)(input[input_offset+i])*invNorm;\n"
" output[input_offset+i]=(FLOAT)out;\n"
" }\n"
" #endif\n"
"}\n"
;
#endif
}
