#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* shared_gather_buf = 
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_2_DIMS __private const int global_size_dim0,__private const int global_size_dim1,\n"
"#define DEAL_NON_UNIFORM_DIM2(input1, input2) "" if ((input1) >= global_size_dim0 || (input2) >= global_size_dim1) { "" return; "" }\n"
"__constant sampler_t SAMPLER=CLK_NORMALIZED_COORDS_FALSE | CLK_ADDRESS_CLAMP | CLK_FILTER_NEAREST;\n"
"__kernel void shared_gather_quant_buffer(\n"
" GLOBAL_SIZE_2_DIMS\n"
" __global OUTPUT_TYPE* output,\n"
"#ifdef USE_LOW_BIT_WEIGHT_INT8\n"
" __global const char* weight,\n"
"#elif defined(USE_LOW_BIT_WEIGHT_INT4)\n"
" __global const uchar* weight,\n"
"#else\n"
" __global const FLOAT* weight,\n"
"#endif\n"
" __global const int* indices,\n"
" __global const FLOAT* dequantScaleOffset,\n"
" __private const int ic,\n"
" __private const int oc,\n"
" __private const int blockSize,\n"
" __private const float coef\n"
") {\n"
" const int select_idx=get_global_id(0);\n"
" const int k4=get_global_id(1);\n"
" DEAL_NON_UNIFORM_DIM2(select_idx,k4);\n"
" const int base_ic=k4 << 2;\n"
" if (base_ic >= ic) {\n"
" return;\n"
" }\n"
" const int ocIndex=indices[select_idx];\n"
" if (ocIndex<0 || ocIndex >= oc) {\n"
" return;\n"
" }\n"
" const int icC4=(ic+3) >> 2;\n"
" const int out_c_idx=ocIndex >> 2;\n"
" const int oc_in4=ocIndex & 3;\n"
" const int ocBlock=ocIndex >> 3;\n"
" const int oc_in8=ocIndex & 7;\n"
" const int dstChannelC4=((oc+3) >> 2) << 2;\n"
" const int tileIndex=ocBlock*icC4+k4;\n"
"#ifdef USE_LOW_BIT_WEIGHT_INT8\n"
" const int weightTileStride=32;\n"
" const int weightBase=tileIndex*weightTileStride;\n"
"#elif defined(USE_LOW_BIT_WEIGHT_INT4)\n"
" const int weightTileStride=16;\n"
" const int weightBase=tileIndex*weightTileStride;\n"
"#else\n"
" const int weightTileStride=0;\n"
" const int weightBase=0;\n"
"#endif\n"
" const int outBase=select_idx*ic+base_ic;\n"
" COMPUTE_FLOAT4 out4=(COMPUTE_FLOAT4)(0,0,0,0);\n"
" for (int i=0; i<4; ++i) {\n"
" const int icIndex=base_ic+i;\n"
" if (icIndex >= ic) {\n"
" break;\n"
" }\n"
" const int blockIndex=icIndex/blockSize;\n"
" const int channelIndex=(out_c_idx << 2)+oc_in4;\n"
" int scaleIndex=blockIndex*dstChannelC4+channelIndex;\n"
"#ifdef ASYMMETRIC\n"
" scaleIndex=scaleIndex*2;\n"
" FLOAT sRaw=dequantScaleOffset[scaleIndex+0];\n"
" FLOAT bRaw=dequantScaleOffset[scaleIndex+1];\n"
" COMPUTE_FLOAT scale=(COMPUTE_FLOAT)(convert_float(sRaw)/coef);\n"
" COMPUTE_FLOAT offset=(COMPUTE_FLOAT)(convert_float(bRaw)/coef);\n"
"#else\n"
" FLOAT sRaw=dequantScaleOffset[scaleIndex];\n"
" COMPUTE_FLOAT scale=(COMPUTE_FLOAT)(convert_float(sRaw)/coef);\n"
" COMPUTE_FLOAT offset=(COMPUTE_FLOAT)0;\n"
"#endif\n"
" COMPUTE_FLOAT wVal=(COMPUTE_FLOAT)0;\n"
"#ifdef USE_LOW_BIT_WEIGHT_INT8\n"
" const int byteIndex=weightBase+i*8+oc_in8;\n"
" char qw=weight[byteIndex];\n"
" wVal=(COMPUTE_FLOAT)qw;\n"
"#elif defined(USE_LOW_BIT_WEIGHT_INT4)\n"
" const int byteIndex=weightBase+i*4+(oc_in8 >> 1);\n"
" uchar packed=weight[byteIndex];\n"
" int nibble=(oc_in8 & 1) == 0 ? ((packed >> 4) & 0x0F) : (packed & 0x0F);\n"
"#ifdef ASYMMETRIC\n"
" wVal=(COMPUTE_FLOAT)nibble;\n"
"#else\n"
" wVal=(COMPUTE_FLOAT)((int)nibble-8);\n"
"#endif\n"
"#else\n"
" const int byteIndex=weightBase+i*8+oc_in8;\n"
" wVal=(COMPUTE_FLOAT)weight[byteIndex];\n"
"#endif\n"
" COMPUTE_FLOAT v=mad(wVal,scale,offset);\n"
" if (i == 0) {\n"
" out4.s0=v;\n"
" } else if (i == 1) {\n"
" out4.s1=v;\n"
" } else if (i == 2) {\n"
" out4.s2=v;\n"
" } else {\n"
" out4.s3=v;\n"
" }\n"
" }\n"
" OUTPUT_TYPE4 outVec=CONVERT_OUTPUT4(out4);\n"
" if (base_ic+3<ic) {\n"
" vstore4(outVec,0,output+outBase);\n"
" } else {\n"
" OUTPUT_TYPE* outPtr=(OUTPUT_TYPE*)(&outVec);\n"
" const int remain=ic-base_ic;\n"
" for (int i=0; i<remain; ++i) {\n"
" output[outBase+i]=outPtr[i];\n"
" }\n"
" }\n"
"}\n"
"__kernel void shared_gather_quant_image(\n"
" GLOBAL_SIZE_2_DIMS\n"
" __global OUTPUT_TYPE* output,\n"
" __read_only image2d_t weight,\n"
" __global const int* indices,\n"
" __global const FLOAT* dequantScaleOffset,\n"
" __private const int ic,\n"
" __private const int oc,\n"
" __private const int blockSize,\n"
" __private const float coef\n"
") {\n"
" const int select_idx=get_global_id(0);\n"
" const int k4=get_global_id(1);\n"
" DEAL_NON_UNIFORM_DIM2(select_idx,k4);\n"
" const int base_ic=k4 << 2;\n"
" if (base_ic >= ic) {\n"
" return;\n"
" }\n"
" const int ocIndex=indices[select_idx];\n"
" if (ocIndex<0 || ocIndex >= oc) {\n"
" return;\n"
" }\n"
" const int out_c_idx=ocIndex >> 2;\n"
" const int oc_in4=ocIndex & 3;\n"
" const int ocBlock=ocIndex >> 3;\n"
" const int oc_in8=ocIndex & 7;\n"
" const int dstChannelC4=((oc+3) >> 2) << 2;\n"
" const int outBase=select_idx*ic+base_ic;\n"
" COMPUTE_FLOAT4 out4=(COMPUTE_FLOAT4)(0,0,0,0);\n"
"#ifdef USE_LOW_BIT_WEIGHT_INT4\n"
" const uchar16 weightBytes=as_uchar16(read_imagei(weight,SAMPLER,(int2)(k4,ocBlock)));\n"
"#endif\n"
" for (int i=0; i<4; ++i) {\n"
" const int icIndex=base_ic+i;\n"
" if (icIndex >= ic) {\n"
" break;\n"
" }\n"
" const int blockIndex=icIndex/blockSize;\n"
" const int channelIndex=(out_c_idx << 2)+oc_in4;\n"
" int scaleIndex=blockIndex*dstChannelC4+channelIndex;\n"
"#ifdef ASYMMETRIC\n"
" scaleIndex=scaleIndex*2;\n"
" FLOAT sRaw=dequantScaleOffset[scaleIndex+0];\n"
" FLOAT bRaw=dequantScaleOffset[scaleIndex+1];\n"
" COMPUTE_FLOAT scale=(COMPUTE_FLOAT)(convert_float(sRaw)/coef);\n"
" COMPUTE_FLOAT offset=(COMPUTE_FLOAT)(convert_float(bRaw)/coef);\n"
"#else\n"
" FLOAT sRaw=dequantScaleOffset[scaleIndex];\n"
" COMPUTE_FLOAT scale=(COMPUTE_FLOAT)(convert_float(sRaw)/coef);\n"
" COMPUTE_FLOAT offset=(COMPUTE_FLOAT)0;\n"
"#endif\n"
" COMPUTE_FLOAT wVal=(COMPUTE_FLOAT)0;\n"
"#ifdef USE_LOW_BIT_WEIGHT_INT8\n"
" const int imageX=(k4 << 1)+(i >> 1);\n"
" const char16 weightBytes=as_char16(read_imagei(weight,SAMPLER,(int2)(imageX,ocBlock)));\n"
" char qw=weightBytes[(i & 1)*8+oc_in8];\n"
" wVal=(COMPUTE_FLOAT)qw;\n"
"#elif defined(USE_LOW_BIT_WEIGHT_INT4)\n"
" uchar packed=weightBytes[i*4+(oc_in8 >> 1)];\n"
" int nibble=(oc_in8 & 1) == 0 ? ((packed >> 4) & 0x0F) : (packed & 0x0F);\n"
"#ifdef ASYMMETRIC\n"
" wVal=(COMPUTE_FLOAT)nibble;\n"
"#else\n"
" wVal=(COMPUTE_FLOAT)((int)nibble-8);\n"
"#endif\n"
"#else\n"
" const int imageX=(k4 << 1)+(i >> 1);\n"
" const char16 weightBytes=as_char16(read_imagei(weight,SAMPLER,(int2)(imageX,ocBlock)));\n"
" wVal=(COMPUTE_FLOAT)weightBytes[(i & 1)*8+oc_in8];\n"
"#endif\n"
" COMPUTE_FLOAT v=mad(wVal,scale,offset);\n"
" if (i == 0) {\n"
" out4.s0=v;\n"
" } else if (i == 1) {\n"
" out4.s1=v;\n"
" } else if (i == 2) {\n"
" out4.s2=v;\n"
" } else {\n"
" out4.s3=v;\n"
" }\n"
" }\n"
" OUTPUT_TYPE4 outVec=CONVERT_OUTPUT4(out4);\n"
" if (base_ic+3<ic) {\n"
" vstore4(outVec,0,output+outBase);\n"
" } else {\n"
" OUTPUT_TYPE* outPtr=(OUTPUT_TYPE*)(&outVec);\n"
" const int remain=ic-base_ic;\n"
" for (int i=0; i<remain; ++i) {\n"
" output[outBase+i]=outPtr[i];\n"
" }\n"
" }\n"
"}\n"
;
#endif
}
