#ifndef VK_GLSL_SHADER_AUTO_GENERATE_H
#define VK_GLSL_SHADER_AUTO_GENERATE_H
extern const unsigned char glsl_nhwcToimage_comp[];
extern unsigned int glsl_nhwcToimage_comp_len;
extern const unsigned char glsl_elementwiseAddBuffer_comp[];
extern unsigned int glsl_elementwiseAddBuffer_comp_len;
extern const unsigned char glsl_lstm_comp[];
extern unsigned int glsl_lstm_comp_len;
extern const unsigned char glsl_deconvCol2Im_comp[];
extern unsigned int glsl_deconvCol2Im_comp_len;
extern const unsigned char glsl_lrnAcrossChannel_comp[];
extern unsigned int glsl_lrnAcrossChannel_comp_len;
extern const unsigned char glsl_softmaxHeight_comp[];
extern unsigned int glsl_softmaxHeight_comp_len;
extern const unsigned char glsl_normalizeChannel_comp[];
extern unsigned int glsl_normalizeChannel_comp_len;
extern const unsigned char glsl_col2ImMali_comp[];
extern unsigned int glsl_col2ImMali_comp_len;
extern const unsigned char glsl_col2ImMali_RELU_comp[];
extern unsigned int glsl_col2ImMali_RELU_comp_len;
extern const unsigned char glsl_col2ImMali_RELU6_comp[];
extern unsigned int glsl_col2ImMali_RELU6_comp_len;
extern const unsigned char glsl_convolutionDepthwiseMali_comp[];
extern unsigned int glsl_convolutionDepthwiseMali_comp_len;
extern const unsigned char glsl_convolutionDepthwiseMali_RELU_comp[];
extern unsigned int glsl_convolutionDepthwiseMali_RELU_comp_len;
extern const unsigned char glsl_convolutionDepthwiseMali_RELU6_comp[];
extern unsigned int glsl_convolutionDepthwiseMali_RELU6_comp_len;
extern const unsigned char glsl_relu_comp[];
extern unsigned int glsl_relu_comp_len;
extern const unsigned char glsl_im2col_comp[];
extern unsigned int glsl_im2col_comp_len;
extern const unsigned char glsl_convolutionDepthwiseUint_comp[];
extern unsigned int glsl_convolutionDepthwiseUint_comp_len;
extern const unsigned char glsl_convolutionDepthwise_comp[];
extern unsigned int glsl_convolutionDepthwise_comp_len;
extern const unsigned char glsl_convolutionDepthwise_RELU_comp[];
extern unsigned int glsl_convolutionDepthwise_RELU_comp_len;
extern const unsigned char glsl_convolutionDepthwise_RELU6_comp[];
extern unsigned int glsl_convolutionDepthwise_RELU6_comp_len;
extern const unsigned char glsl_permute_comp[];
extern unsigned int glsl_permute_comp_len;
extern const unsigned char glsl_imageTonhwc_comp[];
extern unsigned int glsl_imageTonhwc_comp_len;
extern const unsigned char glsl_BatchToSpaceND_comp[];
extern unsigned int glsl_BatchToSpaceND_comp_len;
extern const unsigned char glsl_relu6_comp[];
extern unsigned int glsl_relu6_comp_len;
extern const unsigned char glsl_convolution_comp[];
extern unsigned int glsl_convolution_comp_len;
extern const unsigned char glsl_convolution_RELU_comp[];
extern unsigned int glsl_convolution_RELU_comp_len;
extern const unsigned char glsl_convolution_RELU6_comp[];
extern unsigned int glsl_convolution_RELU6_comp_len;
extern const unsigned char glsl_sqrt_comp[];
extern unsigned int glsl_sqrt_comp_len;
extern const unsigned char glsl_concatBuffer_comp[];
extern unsigned int glsl_concatBuffer_comp_len;
extern const unsigned char glsl_elementwiseSubBuffer_comp[];
extern unsigned int glsl_elementwiseSubBuffer_comp_len;
extern const unsigned char glsl_nchwToimage_comp[];
extern unsigned int glsl_nchwToimage_comp_len;
extern const unsigned char glsl_nc4hw4Tonhwc_comp[];
extern unsigned int glsl_nc4hw4Tonhwc_comp_len;
extern const unsigned char glsl_roipooling_comp[];
extern unsigned int glsl_roipooling_comp_len;
extern const unsigned char glsl_softmax_comp[];
extern unsigned int glsl_softmax_comp_len;
extern const unsigned char glsl_tanh_comp[];
extern unsigned int glsl_tanh_comp_len;
extern const unsigned char glsl_exp_comp[];
extern unsigned int glsl_exp_comp_len;
extern const unsigned char glsl_lstmSave_comp[];
extern unsigned int glsl_lstmSave_comp_len;
extern const unsigned char glsl_imageTonchw_comp[];
extern unsigned int glsl_imageTonchw_comp_len;
extern const unsigned char glsl_rsqrt_comp[];
extern unsigned int glsl_rsqrt_comp_len;
extern const unsigned char glsl_softmaxHeight_NHWC_comp[];
extern unsigned int glsl_softmaxHeight_NHWC_comp_len;
extern const unsigned char glsl_resizeNearest_comp[];
extern unsigned int glsl_resizeNearest_comp_len;
extern const unsigned char glsl_elementwiseMulBuffer_comp[];
extern unsigned int glsl_elementwiseMulBuffer_comp_len;
extern const unsigned char glsl_resizeBilinear_comp[];
extern unsigned int glsl_resizeBilinear_comp_len;
extern const unsigned char glsl_nchwTonc4hw4_comp[];
extern unsigned int glsl_nchwTonc4hw4_comp_len;
extern const unsigned char glsl_nc4hw4Tonchw_comp[];
extern unsigned int glsl_nc4hw4Tonchw_comp_len;
extern const unsigned char glsl_buffer2Image2D_comp[];
extern unsigned int glsl_buffer2Image2D_comp_len;
extern const unsigned char glsl_lstmGate_comp[];
extern unsigned int glsl_lstmGate_comp_len;
extern const unsigned char glsl_SpatialProduct_comp[];
extern unsigned int glsl_SpatialProduct_comp_len;
extern const unsigned char glsl_im2col1x1_comp[];
extern unsigned int glsl_im2col1x1_comp_len;
extern const unsigned char glsl_elementwiseAdd_comp[];
extern unsigned int glsl_elementwiseAdd_comp_len;
extern const unsigned char glsl_sigmoidimage_comp[];
extern unsigned int glsl_sigmoidimage_comp_len;
extern const unsigned char glsl_abs_comp[];
extern unsigned int glsl_abs_comp_len;
extern const unsigned char glsl_avgpool_comp[];
extern unsigned int glsl_avgpool_comp_len;
extern const unsigned char glsl_SpaceToBatchND_comp[];
extern unsigned int glsl_SpaceToBatchND_comp_len;
extern const unsigned char glsl_maxpool_comp[];
extern unsigned int glsl_maxpool_comp_len;
extern const unsigned char glsl_winogradTransformDest2_3_1_comp[];
extern unsigned int glsl_winogradTransformDest2_3_1_comp_len;
extern const unsigned char glsl_winogradTransformDest2_3_1_RELU_comp[];
extern unsigned int glsl_winogradTransformDest2_3_1_RELU_comp_len;
extern const unsigned char glsl_winogradTransformDest2_3_1_RELU6_comp[];
extern unsigned int glsl_winogradTransformDest2_3_1_RELU6_comp_len;
extern const unsigned char glsl_winogradTransformSource2_3_1_comp[];
extern unsigned int glsl_winogradTransformSource2_3_1_comp_len;
extern const unsigned char glsl_blitC4_comp[];
extern unsigned int glsl_blitC4_comp_len;
extern const unsigned char glsl_col2Im_comp[];
extern unsigned int glsl_col2Im_comp_len;
extern const unsigned char glsl_col2Im_RELU_comp[];
extern unsigned int glsl_col2Im_RELU_comp_len;
extern const unsigned char glsl_col2Im_RELU6_comp[];
extern unsigned int glsl_col2Im_RELU6_comp_len;
extern const unsigned char glsl_nc4hw4toimage_comp[];
extern unsigned int glsl_nc4hw4toimage_comp_len;
extern const unsigned char glsl_imageTonc4hw4_comp[];
extern unsigned int glsl_imageTonc4hw4_comp_len;
extern const unsigned char glsl_gemm16x16Half_comp[];
extern unsigned int glsl_gemm16x16Half_comp_len;
extern const unsigned char glsl_elementwiseMul_comp[];
extern unsigned int glsl_elementwiseMul_comp_len;
extern const unsigned char glsl_gemm16x16_comp[];
extern unsigned int glsl_gemm16x16_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_comp[];
extern unsigned int glsl_deconvolutionDepthwise_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_RELU_comp[];
extern unsigned int glsl_deconvolutionDepthwise_RELU_comp_len;
extern const unsigned char glsl_deconvolutionDepthwise_RELU6_comp[];
extern unsigned int glsl_deconvolutionDepthwise_RELU6_comp_len;
extern const unsigned char glsl_preluWithChannel_comp[];
extern unsigned int glsl_preluWithChannel_comp_len;
extern const unsigned char glsl_deconvIm2Col_comp[];
extern unsigned int glsl_deconvIm2Col_comp_len;
extern const unsigned char glsl_deconvIm2Col_RELU_comp[];
extern unsigned int glsl_deconvIm2Col_RELU_comp_len;
extern const unsigned char glsl_deconvIm2Col_RELU6_comp[];
extern unsigned int glsl_deconvIm2Col_RELU6_comp_len;
extern const unsigned char glsl_buffer2Image1D_comp[];
extern unsigned int glsl_buffer2Image1D_comp_len;
extern const unsigned char glsl_scale_comp[];
extern unsigned int glsl_scale_comp_len;
extern const unsigned char glsl_buffer2Image3D_comp[];
extern unsigned int glsl_buffer2Image3D_comp_len;
extern const unsigned char glsl_softmaxWidth_comp[];
extern unsigned int glsl_softmaxWidth_comp_len;
extern const unsigned char glsl_nhwcTonc4hw4_comp[];
extern unsigned int glsl_nhwcTonc4hw4_comp_len;
extern const unsigned char glsl_softmaxChannel_comp[];
extern unsigned int glsl_softmaxChannel_comp_len;
#endif