// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMAND_DSPCOMMAND_H_
#define FLATBUFFERS_GENERATED_COMMAND_DSPCOMMAND_H_

#include "flatbuffers/flatbuffers.h"

namespace DSPCOMMAND {

struct Tensor;
struct TensorT;

struct Command;
struct CommandT;

struct SyncGroup;
struct SyncGroupT;

inline const flatbuffers::TypeTable *TensorTypeTable();

inline const flatbuffers::TypeTable *CommandTypeTable();

inline const flatbuffers::TypeTable *SyncGroupTypeTable();

struct TensorT : public flatbuffers::NativeTable {
  typedef Tensor TableType;
  int32_t fd;
  int32_t offset;
  int32_t size;
  TensorT()
      : fd(0),
        offset(0),
        size(0) {
  }
};

struct Tensor FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TensorT NativeTableType;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return TensorTypeTable();
  }
  int32_t fd() const {
    return GetField<int32_t>(4, 0);
  }
  bool mutate_fd(int32_t _fd) {
    return SetField<int32_t>(4, _fd, 0);
  }
  int32_t offset() const {
    return GetField<int32_t>(6, 0);
  }
  bool mutate_offset(int32_t _offset) {
    return SetField<int32_t>(6, _offset, 0);
  }
  int32_t size() const {
    return GetField<int32_t>(8, 0);
  }
  bool mutate_size(int32_t _size) {
    return SetField<int32_t>(8, _size, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, 4) &&
           VerifyField<int32_t>(verifier, 6) &&
           VerifyField<int32_t>(verifier, 8) &&
           verifier.EndTable();
  }
  TensorT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TensorT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Tensor> Pack(flatbuffers::FlatBufferBuilder &_fbb, const TensorT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TensorBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_fd(int32_t fd) {
    fbb_.AddElement<int32_t>(4, fd, 0);
  }
  void add_offset(int32_t offset) {
    fbb_.AddElement<int32_t>(6, offset, 0);
  }
  void add_size(int32_t size) {
    fbb_.AddElement<int32_t>(8, size, 0);
  }
  explicit TensorBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  TensorBuilder &operator=(const TensorBuilder &);
  flatbuffers::Offset<Tensor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Tensor>(end);
    return o;
  }
};

inline flatbuffers::Offset<Tensor> CreateTensor(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t fd = 0,
    int32_t offset = 0,
    int32_t size = 0) {
  TensorBuilder builder_(_fbb);
  builder_.add_size(size);
  builder_.add_offset(offset);
  builder_.add_fd(fd);
  return builder_.Finish();
}

flatbuffers::Offset<Tensor> CreateTensor(flatbuffers::FlatBufferBuilder &_fbb, const TensorT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CommandT : public flatbuffers::NativeTable {
  typedef Command TableType;
  int32_t type;
  std::vector<std::unique_ptr<TensorT>> inputs;
  std::vector<std::unique_ptr<TensorT>> outputs;
  std::vector<int32_t> params;
  CommandT()
      : type(0) {
  }
};

struct Command FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CommandT NativeTableType;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CommandTypeTable();
  }
  int32_t type() const {
    return GetField<int32_t>(4, 0);
  }
  bool mutate_type(int32_t _type) {
    return SetField<int32_t>(4, _type, 0);
  }
  const flatbuffers::Vector<flatbuffers::Offset<Tensor>> *inputs() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Tensor>> *>(6);
  }
  flatbuffers::Vector<flatbuffers::Offset<Tensor>> *mutable_inputs() {
    return GetPointer<flatbuffers::Vector<flatbuffers::Offset<Tensor>> *>(6);
  }
  const flatbuffers::Vector<flatbuffers::Offset<Tensor>> *outputs() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Tensor>> *>(8);
  }
  flatbuffers::Vector<flatbuffers::Offset<Tensor>> *mutable_outputs() {
    return GetPointer<flatbuffers::Vector<flatbuffers::Offset<Tensor>> *>(8);
  }
  const flatbuffers::Vector<int32_t> *params() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(10);
  }
  flatbuffers::Vector<int32_t> *mutable_params() {
    return GetPointer<flatbuffers::Vector<int32_t> *>(10);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, 4) &&
           VerifyOffset(verifier, 6) &&
           verifier.VerifyVector(inputs()) &&
           verifier.VerifyVectorOfTables(inputs()) &&
           VerifyOffset(verifier, 8) &&
           verifier.VerifyVector(outputs()) &&
           verifier.VerifyVectorOfTables(outputs()) &&
           VerifyOffset(verifier, 10) &&
           verifier.VerifyVector(params()) &&
           verifier.EndTable();
  }
  CommandT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CommandT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Command> Pack(flatbuffers::FlatBufferBuilder &_fbb, const CommandT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CommandBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_type(int32_t type) {
    fbb_.AddElement<int32_t>(4, type, 0);
  }
  void add_inputs(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Tensor>>> inputs) {
    fbb_.AddOffset(6, inputs);
  }
  void add_outputs(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Tensor>>> outputs) {
    fbb_.AddOffset(8, outputs);
  }
  void add_params(flatbuffers::Offset<flatbuffers::Vector<int32_t>> params) {
    fbb_.AddOffset(10, params);
  }
  explicit CommandBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  CommandBuilder &operator=(const CommandBuilder &);
  flatbuffers::Offset<Command> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Command>(end);
    return o;
  }
};

inline flatbuffers::Offset<Command> CreateCommand(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t type = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Tensor>>> inputs = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Tensor>>> outputs = 0,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> params = 0) {
  CommandBuilder builder_(_fbb);
  builder_.add_params(params);
  builder_.add_outputs(outputs);
  builder_.add_inputs(inputs);
  builder_.add_type(type);
  return builder_.Finish();
}

flatbuffers::Offset<Command> CreateCommand(flatbuffers::FlatBufferBuilder &_fbb, const CommandT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct SyncGroupT : public flatbuffers::NativeTable {
  typedef SyncGroup TableType;
  std::vector<std::unique_ptr<TensorT>> inputs;
  std::vector<std::unique_ptr<TensorT>> outputs;
  SyncGroupT() {
  }
};

struct SyncGroup FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SyncGroupT NativeTableType;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return SyncGroupTypeTable();
  }
  const flatbuffers::Vector<flatbuffers::Offset<Tensor>> *inputs() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Tensor>> *>(4);
  }
  flatbuffers::Vector<flatbuffers::Offset<Tensor>> *mutable_inputs() {
    return GetPointer<flatbuffers::Vector<flatbuffers::Offset<Tensor>> *>(4);
  }
  const flatbuffers::Vector<flatbuffers::Offset<Tensor>> *outputs() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Tensor>> *>(6);
  }
  flatbuffers::Vector<flatbuffers::Offset<Tensor>> *mutable_outputs() {
    return GetPointer<flatbuffers::Vector<flatbuffers::Offset<Tensor>> *>(6);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, 4) &&
           verifier.VerifyVector(inputs()) &&
           verifier.VerifyVectorOfTables(inputs()) &&
           VerifyOffset(verifier, 6) &&
           verifier.VerifyVector(outputs()) &&
           verifier.VerifyVectorOfTables(outputs()) &&
           verifier.EndTable();
  }
  SyncGroupT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(SyncGroupT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<SyncGroup> Pack(flatbuffers::FlatBufferBuilder &_fbb, const SyncGroupT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct SyncGroupBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_inputs(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Tensor>>> inputs) {
    fbb_.AddOffset(4, inputs);
  }
  void add_outputs(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Tensor>>> outputs) {
    fbb_.AddOffset(6, outputs);
  }
  explicit SyncGroupBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  SyncGroupBuilder &operator=(const SyncGroupBuilder &);
  flatbuffers::Offset<SyncGroup> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<SyncGroup>(end);
    return o;
  }
};

inline flatbuffers::Offset<SyncGroup> CreateSyncGroup(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Tensor>>> inputs = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Tensor>>> outputs = 0) {
  SyncGroupBuilder builder_(_fbb);
  builder_.add_outputs(outputs);
  builder_.add_inputs(inputs);
  return builder_.Finish();
}

flatbuffers::Offset<SyncGroup> CreateSyncGroup(flatbuffers::FlatBufferBuilder &_fbb, const SyncGroupT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline TensorT *Tensor::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = new TensorT();
  UnPackTo(_o, _resolver);
  return _o;
}

inline void Tensor::UnPackTo(TensorT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = fd(); _o->fd = _e; };
  { auto _e = offset(); _o->offset = _e; };
  { auto _e = size(); _o->size = _e; };
}

inline flatbuffers::Offset<Tensor> Tensor::Pack(flatbuffers::FlatBufferBuilder &_fbb, const TensorT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTensor(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Tensor> CreateTensor(flatbuffers::FlatBufferBuilder &_fbb, const TensorT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const TensorT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _fd = _o->fd;
  auto _offset = _o->offset;
  auto _size = _o->size;
  return DSPCOMMAND::CreateTensor(
      _fbb,
      _fd,
      _offset,
      _size);
}

inline CommandT *Command::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = new CommandT();
  UnPackTo(_o, _resolver);
  return _o;
}

inline void Command::UnPackTo(CommandT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; };
  { auto _e = inputs(); if (_e) { _o->inputs.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->inputs[_i] = std::unique_ptr<TensorT>(_e->Get(_i)->UnPack(_resolver)); } } };
  { auto _e = outputs(); if (_e) { _o->outputs.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->outputs[_i] = std::unique_ptr<TensorT>(_e->Get(_i)->UnPack(_resolver)); } } };
  { auto _e = params(); if (_e) { _o->params.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->params[_i] = _e->Get(_i); } } };
}

inline flatbuffers::Offset<Command> Command::Pack(flatbuffers::FlatBufferBuilder &_fbb, const CommandT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCommand(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Command> CreateCommand(flatbuffers::FlatBufferBuilder &_fbb, const CommandT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const CommandT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _inputs = _o->inputs.size() ? _fbb.CreateVector<flatbuffers::Offset<Tensor>> (_o->inputs.size(), [](size_t i, _VectorArgs *__va) { return CreateTensor(*__va->__fbb, __va->__o->inputs[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _outputs = _o->outputs.size() ? _fbb.CreateVector<flatbuffers::Offset<Tensor>> (_o->outputs.size(), [](size_t i, _VectorArgs *__va) { return CreateTensor(*__va->__fbb, __va->__o->outputs[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _params = _o->params.size() ? _fbb.CreateVector(_o->params) : 0;
  return DSPCOMMAND::CreateCommand(
      _fbb,
      _type,
      _inputs,
      _outputs,
      _params);
}

inline SyncGroupT *SyncGroup::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = new SyncGroupT();
  UnPackTo(_o, _resolver);
  return _o;
}

inline void SyncGroup::UnPackTo(SyncGroupT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = inputs(); if (_e) { _o->inputs.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->inputs[_i] = std::unique_ptr<TensorT>(_e->Get(_i)->UnPack(_resolver)); } } };
  { auto _e = outputs(); if (_e) { _o->outputs.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->outputs[_i] = std::unique_ptr<TensorT>(_e->Get(_i)->UnPack(_resolver)); } } };
}

inline flatbuffers::Offset<SyncGroup> SyncGroup::Pack(flatbuffers::FlatBufferBuilder &_fbb, const SyncGroupT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateSyncGroup(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<SyncGroup> CreateSyncGroup(flatbuffers::FlatBufferBuilder &_fbb, const SyncGroupT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const SyncGroupT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _inputs = _o->inputs.size() ? _fbb.CreateVector<flatbuffers::Offset<Tensor>> (_o->inputs.size(), [](size_t i, _VectorArgs *__va) { return CreateTensor(*__va->__fbb, __va->__o->inputs[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _outputs = _o->outputs.size() ? _fbb.CreateVector<flatbuffers::Offset<Tensor>> (_o->outputs.size(), [](size_t i, _VectorArgs *__va) { return CreateTensor(*__va->__fbb, __va->__o->outputs[i].get(), __va->__rehasher); }, &_va ) : 0;
  return DSPCOMMAND::CreateSyncGroup(
      _fbb,
      _inputs,
      _outputs);
}

inline const flatbuffers::TypeTable *TensorTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_INT, 0, -1 },
    { flatbuffers::ET_INT, 0, -1 },
    { flatbuffers::ET_INT, 0, -1 }
  };
  static const char * const names[] = {
    "fd",
    "offset",
    "size"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 3, type_codes, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *CommandTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_INT, 0, -1 },
    { flatbuffers::ET_SEQUENCE, 1, 0 },
    { flatbuffers::ET_SEQUENCE, 1, 0 },
    { flatbuffers::ET_INT, 1, -1 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    TensorTypeTable
  };
  static const char * const names[] = {
    "type",
    "inputs",
    "outputs",
    "params"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 4, type_codes, type_refs, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *SyncGroupTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 1, 0 },
    { flatbuffers::ET_SEQUENCE, 1, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    TensorTypeTable
  };
  static const char * const names[] = {
    "inputs",
    "outputs"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, names
  };
  return &tt;
}

}  // namespace DSPCOMMAND

#endif  // FLATBUFFERS_GENERATED_COMMAND_DSPCOMMAND_H_
